<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/default/roundcorner2.css" />
<h1 align="center"><?php echo $this->escape($this->title); ?></h1>


<?php
    if ( $this->result_error )
    {
        switch ( $this->result_error )
        {
            case 'ERROR_BCONSOLE': // ошибка при запуске bconsole
                $msg = $this->translate->_('ERROR: There was a problem executing bconsole.');
                break;
            case 'NOFOUND_BCONSOLE': // bconsole не найден
                $msg = $this->translate->_('ERROR: bconsole not found.');
                break;
            default: $msg = '';
        }
        echo '<font color="red"><div align="center"><p>', $msg, '</p></div></font>';
        echo '<font color="red">';
        if ( $this->command_output )
        {
            foreach ($this->command_output as $line) {
			 echo $line, '<br>';
		  }
        }
		echo '</font>';
    } else {
        // ***************** все OK *******************
?>


<div class="roundedcornr_box_2" style="width: 60%; margin-left: auto; margin-right: auto; text-align: left;">
   <div class="roundedcornr_top_2"><div></div></div>
      <div class="roundedcornr_content_2">

    <b><?php print $this->translate->_("Director output:"); ?></b>

	<?php
    if ( $this->command_output )
    {
        echo '<pre>';
        foreach ($this->command_output as $line) {
            if ( eregi('.*(ERR|not found|invalid).*', $line) )   {
                echo '<div style="color: white; background-color: red;">', $line, '</div><br>';
            } else {
                echo $line, '<br>';
            }
		}
		echo '</pre>';
    }
    ?>

    <p>&nbsp;</p>
    <div align="center">
    <form action="<?php  echo $this->baseUrl;?>" method="post">
    <?php echo $this->formSubmit('ok1', $this->translate->_('View Desktop') ); ?>
    </form></div>

      </div>
   <div class="roundedcornr_bottom_2"><div></div></div>
</div>

<?php
    }
?>

<p>&nbsp;</p>