<!-- job/statusdir.phtml -->
<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary panel-logoutput">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               <?php if ( $this->result_error ): ?>
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                     <span class="glyphicon glyphicon-alert"></span>
                     <?php
                     echo $this->escape($this->title), '<br>';
                        switch ( $this->result_error ) {
                           case 'ERROR_BCONSOLE': // Error when bconsole starts
                              $msg = $this->translate->_('ERROR: There was a problem executing bconsole.');
                              break;
                           case 'NOFOUND_BCONSOLE': // Bconsole not found
                              $msg = $this->translate->_('ERROR: bconsole not found.');
                              break;
                           default: $msg = '';
                        }
                        echo $msg;
                        if ( $this->command_output ) {
                           foreach ($this->command_output as $line) {
                              echo '<br/>', $line, '<br/>';
                           }
                        }
                  ?>
                  </p>
               </div>
               <!-- end div alert -->
            
               <?php else: ?>
            
               <!-- director output -->
               <b><?php print $this->translate->_("Director output:"); ?></b>
               <?php
               if ( $this->command_output ) {
                  echo '<pre>';
                     foreach ($this->command_output as $line) {
                        if ( preg_match('/(ERR|not found|invalid|Expected)/i', $line) )   {
                           echo '<div>', $line, '</div><br/>';
                        } else {
                           echo $line, '<br/>';
                        }
                  }
                  echo '</pre>';
                } ?>
                <!-- end director output -->
                
               <?php endif; ?>
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div row -->
<!-- end job/statusdir.phtml -->