<!-- formJobrun.phtml -->
<?php $translate = Zend_Registry::get('translate'); ?>

<form  action="<?php echo $this->escape($this->form->getAction()); ?>"
        method="<?php echo $this->escape($this->form->getMethod()); ?>"
        name="form1">
<fieldset>
    <legend><?php echo $translate->_("Run Job"); ?></legend>
    
<?php echo $this->form->from_form;?>

<table border="0" cellpadding="3" cellspacing="3" align="left">
<tr><td style="text-align: right;">
    <label for="jobname" class="ui-select"><b><?php echo $translate->_("Job Name"); ?></b></label>
</td><td>
    <?php echo $this->form->jobname;?>
</td></tr><tr><td style="text-align: right;">
    <label for="client" class="ui-select"><b><?php echo $translate->_("Client"); ?></b></label>
</td><td>
    <?php echo $this->form->client;?>
</td></tr><tr><td style="text-align: right;">
    <label for="fileset" class="ui-select"><b><?php echo $translate->_("Fileset"); ?></b></label>
</td><td>
    <?php echo $this->form->fileset;?>

<?php /*
    <?php echo $this->formSelect('fileset', null, array('class' => 'ui-select', 'style' => 'width: 25em;'), $this->filesets); ?>
</td></tr><tr><td style="text-align: right;">
    <label for="storage" class="ui-select"><b><?php print $this->translate->_("Storage"); ?></b></label>
</td><td>
    <?php echo $this->formSelect('storage', null, array('class' => 'ui-select', 'style' => 'width: 25em;'), $this->storages); ?>
</td></tr><tr><td style="text-align: right;">
    <label for="level" class="ui-select"><b><?php print $this->translate->_("Level"); ?></b></label>
</td><td>
    <?php echo $this->formSelect('level', null, array('class' => 'ui-select', 'style' => 'width: 20em;'), $this->levels); ?>
</td></tr><tr><td style="text-align: right;">
    <label for="spool" class="ui-select"><b><?php print $this->translate->_("Spool"); ?></b></label>
</td><td>
    <?php echo $this->formSelect('spool', null, array('class' => 'ui-select', 'style' => 'width: 10em;'), $this->spools); ?>
</td></tr><tr><td style="text-align: right;">
    <label for="date_when" class="ui-select"><b><?php print $this->translate->_("When"); ?></b></label>
</td><td>
    <?php print $this->translate->_("Now"); ?><input type="checkbox" name="checkbox_now" onclick="whenNow(this)" checked>
    <br>
    <?php echo $this->formText('date_when', date('Y-m-d', time()), array('size' => 10, 'maxlength' => 10, 'disabled'=>'true')) ?>
    <?php echo $this->formText('time_when', date('H:i:s', time()), array('size' => 8, 'maxlength' => 8  , 'disabled'=>'true')) ?>
    <br><div style="font-size:0.6em;"><?php print $this->translate->_("YYYY-MM-DD HH:MM:SS"); ?></div>

*/?>

</td></tr><tr><td colspan="2">
    <div style="text-align: center; margin-left: auto; margin-right: auto;">
        <?php echo $this->form->submit; ?>
    </div>
</td></tr>
</table>
</fieldset>
</form>
