<?php echo $this->render('header.phtml'); ?>
<h1 align="center"><?php echo $this->escape($this->title); ?></h1>

<?php if ($this->result): ?>

<table class="t1" border="0" cellspacing="0" align="center">
<tr>
<td class="t3"><pre>
<?php foreach($this->result as $line) : ?>
  <?php echo $this->escape($line['logtime']) . "   " . rtrim( $this->escape($line['logtext']) , "\r\n\t \0") . "<br>";?>
<?php endforeach; ?>
</pre></td>
</table>

<?php else: ?>
	<div align="center"><p><b><?php print $this->translate->_("No Console messages found."); ?></b></p></div>
<?php endif; ?>


<?php echo $this->render('footer.phtml'); ?>