<!-- log/view-log-id.phtml -->
<h1><?php echo $this->escape($this->title); ?></h1>

<?php if ($this->result): ?>

<table class="t1" border="0" cellspacing="0">
<tr>
<td class="t3"><pre>
<?php
    foreach($this->result as $line) {
        //echo $this->escape($line['logtime']) . "   " . rtrim( $this->escape($line['logtext']) , "\r\n\t \0") . "<br>";
        $line = $this->escape($line['logtime']) . "   " . rtrim($line['logtext'] , "\r\n\t \0");
        if(preg_match ("/ERR/", $line)) {
            echo '<div style="color: white; background-color: red;">' . $line . ' </div><br />';
        } else {
            echo $line, '<br />';
        }
    }
?>
</pre></td>
</table>

<?php else: ?>
	<p><b><?php print $this->translate->_("No Console messages found."); ?></b></p>
<?php endif; ?>
