<script type="text/javascript" src="<?php echo $this->baseUrl , '/scripts/jquery-ui.datepicker-', $this->language, '.js';?>"></script>
<script type="text/javascript">
  // select
  $j(function(){
      $j('select').each(function() {
          var t = $j(this).selectmenu({maxHeight: 300});
          eval(t);
      });
  });
</script>

<script type="text/javascript">
$j(function() {
	$j('#date_begin').datepicker({
			changeMonth: true,
			changeYear: true
	});
	$j('#date_end').datepicker({
			changeMonth: true,
			changeYear: true
	});

	$j('#date_begin').datepicker('setDate', '-1d' );
	$j('#date_begin').datepicker('option', {dateFormat: $j.datepicker.ISO_8601} );

	$j("#date_end").datepicker('option', {dateFormat: $j.datepicker.ISO_8601} );
});
</script>

<script type="text/javascript">
$j(function() {
	$j("#accordion").accordion({
			autoHeight: false
		});
});
</script>



<h1 align="center"><?php echo $this->escape($this->title); ?></h1>

<?php

// create array clients for Form
$aclients[''] = $this->translate->_('ANY');
foreach($this->clients as $client) :
	$aclients[$this->escape($client->name)] = $this->escape($client->name);
endforeach;
$aclients[''] = $this->translate->_('ANY');	// if empty client exists in database

// create array filesets for Form
$afilesets[''] = $this->translate->_('ANY');
foreach($this->filesets as $fileset) :
	$afilesets[$this->escape($fileset->fileset)] = $this->escape($fileset->fileset);
endforeach;
$afilesets[''] = $this->translate->_('ANY');	// if empty FileSet exists in database

// create array levels for Form
$alevels = array(
    "" =>  $this->translate->_("ANY"),
    "F" => $this->translate->_("Full level"),
    "I" => $this->translate->_("Incremental level"),
    "D" => $this->translate->_("Differential level")
);

// create array JobStatus for Form
$astatus = array(
    ""  => $this->translate->_("ANY"),
    "R" => $this->translate->_("Running"),
    "T" => $this->translate->_("Completed successfully"),
    "E" => $this->translate->_("Terminated with errors"),
	"A" => $this->translate->_("Canceled by user"),
	"W" => $this->translate->_("Waiting anything")
);

// create array Job Type for Form
$atype = array(
    "" => $this->translate->_("ANY"),
    "B" => $this->translate->_("Backup type"),
    "R" => $this->translate->_("Restore type"),
    "V" => $this->translate->_("Verify type"),
    "D" => $this->translate->_("Admin Job type")
);

?>


<div style="width: 80%; margin-left: auto; margin-right: auto;">
<div id="accordion" style="text-align: left;">

<!-- // find by JobId -->
<h3><a href="#"><?php print $this->translate->_("Job Id"); ?></a></h3>
<div>
<form action="<?php  echo $this->baseUrl.'/job/find-job-id';?>" method="post">
	<b><?php print $this->translate->_("Job Id"); ?></b> <?php echo $this->formText('jobid', "", array('size' => 10)) ?>
	<?php echo $this->formSubmit('ok1', $this->translate->_('Search'), array('class' => 'prefer_btn') ); ?>
</form>
</div>

<!-- // find by many filters -->
<h3><a href="#"><?php print $this->translate->_("Time, Client, Fileset, Level, Status, Type"); ?></a></h3>
<div>
<form action="<?php  echo $this->baseUrl.'/job/find-filters';?>" method="post">
<table border="0" cellpadding="5" cellspacing="5" align="left">
<tr><td>
	<b><?php print $this->translate->_("Time of start of the Jobs with"); ?></b>
	<br><div style="font-size:70%;"><?php print $this->translate->_("YYYY-MM-DD HH:MM:SS"); ?></div>
</td><td>
	<?php echo $this->formText('date_begin', date('Y-m-d', time()-86400), array('size' => 10, 'maxlength' => 10)) ?>
	<?php echo $this->formText('time_begin', date('H:i:s', time()-86400), array('size' => 8, 'maxlength' => 8 )) ?>
	&nbsp;&nbsp;<b><?php print $this->translate->_("up to"); ?></b>&nbsp;
	<?php echo $this->formText('date_end', date('Y-m-d', time()), array('size' => 10, 'maxlength' => 10)) ?>
	<?php echo $this->formText('time_end', date('H:i:s', time()), array('size' => 8, 'maxlength' => 8)) ?>
</td></tr><tr><td style="text-align: right;">
	<label for="client" class="ui-select"><b><?php print $this->translate->_("Client"); ?></b></label>
</td><td>
	<?php echo $this->formSelect('client', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $aclients) ?>
</td></tr><tr><td style="text-align: right;">
   	<label for="fileset" class="ui-select"><b><?php print $this->translate->_("Fileset"); ?></b></label>
</td><td>
   	<?php echo $this->formSelect('fileset', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $afilesets) ?>
</td></tr><tr><td style="text-align: right;">
	<label for="jlevel" class="ui-select"><b><?php print $this->translate->_("Level"); ?></b></label>
</td><td>
	<?php echo $this->formSelect('jlevel', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $alevels) ?>
</td></tr><tr><td style="text-align: right;">
	<label for="jstatus" class="ui-select"><b><?php print $this->translate->_("Status"); ?></b></label>
</td><td>
	<?php echo $this->formSelect('jstatus', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $astatus) ?>
</td></tr><tr><td style="text-align: right;">
	<label for="jtype" class="ui-select"><b><?php print $this->translate->_("Type"); ?></b></label>
</td><td>
  	<?php echo $this->formSelect('jtype', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $atype) ?>
</td></tr><tr><td colspan="2">
   	<?php echo $this->formSubmit('ok2', $this->translate->_('Search'), array('class'=>'prefer_btn', 'style'=>'margin-top: 0px; margin-bottom: 0px;') ); ?>
</td></tr>
</table>
</form>
</div>


<!-- // find by Volume Name -->
<h3><a href="#"><?php print $this->translate->_("Volume Name"); ?></a></h3>
<div>
<form action="<?php  echo $this->baseUrl.'/job/find-volume-name';?>" method="post">
	<b><?php print $this->translate->_("Volume Name"); ?></b>
   	<?php echo $this->formText('volname', "", array('size' => 40)) ?>
   	<?php echo $this->formSubmit('ok3', $this->translate->_('Search'), array('class' => 'prefer_btn') ); ?>
</form>
</div>


<!-- // List last 20 Jobs run -->
<h3><a href="#"><?php echo $this->translate->_("List last"), ' ', $this->translate->_("Jobs run"); ?></a></h3>
<div>
<form action="<?php  echo $this->baseUrl.'/job/list-last-jobs-run';?>" method="post">
	<b><?php print $this->translate->_("List last"); ?></b>
   	<?php echo $this->formText('numjob', "20", array('size' => 5)) ?> <b><?php print $this->translate->_("Jobs run"); ?></b>
   	<?php echo $this->formSubmit('ok4', $this->translate->_('Search'), array('class' => 'prefer_btn') ); ?>
</form>
</div>


<!-- // List Jobs where a given File is saved -->
<h3><a href="#"><?php print $this->translate->_("File Name"); ?></a></h3>
<div>
<form action="<?php  echo $this->baseUrl.'/job/find-file-name';?>" method="post">
<table border="0" cellpadding="5" cellspacing="5" align="left">
<tr><td>
   	<b><?php print $this->translate->_("Enter Filename (no path)"); ?></b>
</td><td>
   	<?php echo $this->formText('namefile', "", array('size' => 40)) ?>
</td></tr><tr><td style="text-align: right;">
	<label for="client_nf" class="ui-select"><b><?php print $this->translate->_("Client"); ?></b></label>
</td><td>
	<?php echo $this->formSelect('client_nf', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $aclients) ?>
</td></tr>
<tr><td colspan="2">
	<?php echo $this->formSubmit('ok5', $this->translate->_('Search'), array('class' => 'prefer_btn', 'style'=>'margin-top: 0px; margin-bottom: 0px;') ); ?>
</td></tr>
</table>
</form>
  </div>

  </div>
</div>