<!-- job/find_filters_pagination_ctrl.phtml -->
<?php $this->translate = Zend_Registry::get('translate'); ?>
<div class="rows">
<?php if ($this->pageCount): ?>

<?php
    //echo $this->firstItemNumber, ' -- ', $this->lastItemNumber, ' ', $this->translate->_('of'), ' ', $this->totalItemCount;
    $opt = array();
    empty($this->options['date_begin']) ? true : $opt['date_begin'] = $this->options['date_begin'];
    empty($this->options['time_begin']) ? true : $opt['time_begin'] = $this->options['time_begin'];
    empty($this->options['date_end'])   ? true : $opt['date_end']   = $this->options['date_end'];
    empty($this->options['time_end'])   ? true : $opt['time_end']   = $this->options['time_end'];
    empty($this->options['client'])     ? true : $opt['client']     = rawurlencode($this->options['client']);
    empty($this->options['fileset'])    ? true : $opt['fileset']    = rawurlencode($this->options['fileset']);
    empty($this->options['jlevel'])     ? true : $opt['jlevel']     = rawurlencode($this->options['jlevel']);
    empty($this->options['jstatus'])    ? true : $opt['jstatus']    = rawurlencode($this->options['jstatus']);
    empty($this->options['jtype'])      ? true : $opt['jtype']      = rawurlencode($this->options['jtype']);
    empty($this->options['volname'])    ? true : $opt['volname']    = rawurlencode($this->options['volname']);
?>
   <div>
      <ul class="pagination">

         <!-- Link to the first page -->
         <?php if (isset($this->previous)): ?>
           <?php echo '<li class="page-item"><a href="', $this->url( array_merge(array('page' => $this->first), $opt) ),'">', $this->translate->_('First page'), '</a></li>'; ?>
         <?php endif; ?>
         
         <!-- Link to the previous page -->
         <?php if (isset($this->previous)): ?>
           <?php echo '<li class="page-item"><a href="', $this->url( array_merge(array('page' => $this->previous), $opt) ), '">', $this->translate->_('Previous page'), '</a></li>'; ?>
         <?php endif; ?>
         
         <!-- Numbered links to pages -->
         <?php if ( sizeof($this->pagesInRange) > 1 ):?>
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                    <?php echo '<li class="page-item"><a href="', $this->url( array_merge(array('page' => $page), $opt) ), '">', $page, '</a></li>'; ?>
                 <?php else: ?>
                    <?php echo '<li class="page-item active"><a href="', $this->url( array_merge(array('page' => $page), $opt) ), '">', $page, '</a></li>'; ?>
                 <?php endif; ?>
             <?php endforeach; ?>
         <?php endif; ?>
         
         <!-- Link to the next page -->
         <?php if (isset($this->next)): ?>
           <?php echo '<li class="page-item"><a href="', $this->url( array_merge(array('page' => $this->next), $opt) ), '">', $this->translate->_('Next page'), '</a></li>'; ?>
         <?php endif; ?>
         
         <!-- Link to the last page -->
         <?php if (isset($this->next)): ?>
           <?php echo '<li class="page-item"><a href="', $this->url( array_merge(array('page' => $this->last), $opt) ), '">', $this->translate->_('Last page'), '</a></li>'; ?>
         <?php endif; ?>

      </ul>
   </div>

<?php endif; ?>
</div><!-- end div rows -->
<!-- job/find_filters_pagination_ctrl.phtml -->