<!-- job/find-form.phtml -->
<script type="text/javascript" src="<?php echo $this->baseUrl , '/scripts/jquery-ui.datepicker-', $this->language, '.js';?>"></script>

<script type="text/javascript">
$(document).ready(function(){
   $('select').each(function() {
          $(this).addClass("select-overflow").addClass("form-control");
   });
  });
</script>

<script type="text/javascript">
$(document).ready(function(){

   var dates1 = $( "#date_begin, #date_end" ).datepicker({
          dateFormat: 'yy-mm-dd',
          changeMonth: true,
          changeYear: true,
          autoSize: true,
          onSelect: function( selectedDate ) {
          var option = this.id == "date_begin" ? "minDate" : "maxDate",
              instance = $( this ).data( "datepicker" ),
              date = $.datepicker.parseDate(
                 instance.settings.dateFormat ||
                 $.datepicker._defaults.dateFormat,
                 selectedDate, instance.settings 
              );
          dates1.not( this ).datepicker( "option", option, date );
          }
       });
       $('#date_begin').datepicker('setDate', '-1d' );
       $('#date_begin').datepicker('option', {dateFormat: $.datepicker.ISO_8601} );

});
</script>

<?php

// create array clients for Form
$aclients[''] = $this->translate->_('ANY');
foreach($this->clients as $client) :
    $aclients[ $this->escape($client['name']) ] = $this->escape($client['name']);
endforeach;
$aclients[''] = $this->translate->_('ANY');  // if empty client exists in database

// create array filesets for Form
$afilesets[''] = $this->translate->_('ANY');
foreach($this->filesets as $fileset) :
    $afilesets[ $this->escape($fileset['fileset']) ] = $this->escape($fileset['fileset']);
endforeach;
$afilesets[''] = $this->translate->_('ANY'); // if empty FileSet exists in database

// create array levels for Form
$alevels = array(
    "" =>  $this->translate->_("ANY"),
    "F" => $this->translate->_("Full level"),
    "I" => $this->translate->_("Incremental level"),
    "D" => $this->translate->_("Differential level")
);

// create array JobStatus for Form
$astatus = array(
   ""  => $this->translate->_("ANY"),
   "R" => $this->translate->_("Running"),
   "T" => $this->translate->_("Completed successfully"),
   "E" => $this->translate->_("Terminated with errors"),
   "A" => $this->translate->_("Canceled by user"),
   "W" => $this->translate->_("Waiting anything")
);

// create array Job Type for Form
$atype = array(
    "" => $this->translate->_("ANY"),
    "B" => $this->translate->_("Backup type"),
    "R" => $this->translate->_("Restore type"),
    "V" => $this->translate->_("Verify type"),
    "D" => $this->translate->_("Admin Job type"),
    "C" => $this->translate->_("Copy of a Job"),
    "c" => $this->translate->_("Copy Job")
);

?>


<!-- ########################################################################## -->
<div class="rows">
   <div class="col-md-6">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>  
               <div class="panel-group" id="accordion">
                  <!-- Find by JobId -->
                  <div class="panel panel-default panel-default">
                     <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapseOne">
                        <a class="accordion-toggle">
                           <?php print $this->translate->_("Job Id"); ?>
                        </a>
                     </div>
                     <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <!-- Find by JobId -->
                            <div>
                               <form action="<?php  echo $this->baseUrl.'/job/find-job-id';?>" method="post">
                                 <b><?php print $this->translate->_("Job Id"); ?></b>&nbsp;&nbsp;&nbsp; <?php echo $this->formText('jobid', "", array('size' => 10)) ?>
                                 <?php echo $this->formSubmit('ok1', $this->translate->_('Search'), array('class' => 'btn btn-default') ); ?>
                               </form>
                            </div>
                            <!-- end Find by JobId -->
                        </div>
                     </div>
                  </div>
                  <!-- end Find by JobId -->
                  
                  <!-- find by Job Name -->
                  <div class="panel panel-default panel-default">
                     <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapseTwo">
                        <a class="accordion-toggle">
                          <?php print $this->translate->_("Job Name"); ?>
                        </a>
                     </div>
                     <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                         <!-- find by Job Name -->
                         <div>
                            <form action="<?php  echo $this->baseUrl.'/job/find-job-name';?>" method="post">
                              <b><?php print $this->translate->_("Job Name"); ?></b> &nbsp;&nbsp;&nbsp;<?php echo $this->formText('jobname', "", array('size' => 40)) ?>
                              <?php echo $this->formSubmit('ok1', $this->translate->_('Search'), array('class' => 'btn btn-default') ); ?>
                            </form>
                         </div>
                         <!-- end find by Job Name -->
                        </div>
                     </div>
                  </div>
                  <!-- end find by Job Name -->
                  
                  <!-- find by many filters -->
                  <div class="panel panel-default panel-default">
                     <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapseThree">
                        <a class="accordion-toggle">
                          <?php print $this->translate->_("Time, Client, Fileset, Level, Status, Type"); ?>
                        </a>
                     </div>
                     <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                           <!-- find by many filters -->
                           <div>
                              <form action="<?php  echo $this->baseUrl.'/job/find-filters';?>" method="post">
                                 <table>
                                    <tr>
                                       <td><b><?php print $this->translate->_("Time of start of the Jobs with"); ?></b></td>
                                       <td>
                                          <?php echo $this->formText('date_begin', date('Y-m-d', time()-86400), array('size' => 10, 'maxlength' => 10)) ?><br/>
                                          <small class="form-text text-muted"><?php print $this->translate->_("YYYY-MM-DD"); ?></small>
                                       </td>
                                       <td>
                                          <?php echo $this->formText('time_begin', date('H:i:s', time()-86400), array('size' => 8, 'maxlength' => 8 )) ?><br/>
                                          <small class="form-text text-muted"><?php print $this->translate->_("HH:MM:SS"); ?></small>
                                       </td>
                                       <td><b><?php print $this->translate->_("up to"); ?></b></td>
                                       <td>
                                          <?php echo $this->formText('date_end', date('Y-m-d', time()), array('size' => 10, 'maxlength' => 10)) ?><br/>
                                          <small class="form-text text-muted"><?php print $this->translate->_("YYYY-MM-DD"); ?></small>
                                       </td>
                                       <td>
                                          <?php echo $this->formText('time_end', date('H:i:s', time()), array('size' => 8, 'maxlength' => 8)) ?><br/>
                                          <small class="form-text text-muted"><?php print $this->translate->_("HH:MM:SS"); ?></small>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                       <label for="client"><b><?php print $this->translate->_("Client"); ?></b>&nbsp;&nbsp;&nbsp;</label>
                                       </td>
                                       <td colspan="5">
                                          <?php echo $this->formSelect('client', null, array('style' => 'width: 60%;'), $aclients) ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                          <label for="fileset" class="ui-select"><b><?php print $this->translate->_("Fileset"); ?></b>&nbsp;&nbsp;&nbsp;</label>
                                       </td>
                                       <td colspan="5">
                                          <?php echo $this->formSelect('fileset', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $afilesets) ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                          <label for="jlevel" class="ui-select"><b><?php print $this->translate->_("Level"); ?></b>&nbsp;&nbsp;&nbsp;</label>
                                       </td>
                                       <td colspan="5">
                                          <?php echo $this->formSelect('jlevel', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $alevels) ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                          <label for="jstatus" class="ui-select"><b><?php print $this->translate->_("Status"); ?></b>&nbsp;&nbsp;&nbsp;</label>
                                       </td>
                                       <td colspan="5">
                                          <?php echo $this->formSelect('jstatus', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $astatus) ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                          <label for="jtype" class="ui-select"><b><?php print $this->translate->_("Type"); ?></b>&nbsp;&nbsp;&nbsp;</label>
                                       </td>
                                       <td colspan="5">
                                          <?php echo $this->formSelect('jtype', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $atype) ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td colspan="6">
                                          <br/>
                                          <?php echo $this->formSubmit('ok2', $this->translate->_('Search'), array('class'=>'btn btn-default') ); ?>
                                       </td>
                                    </tr>
                                 </table>
                              </form>
                           </div>
                           <!-- end Find by many filters -->
                        </div>
                     </div>
                  </div>
                  <!-- end find by many filters -->
                  
                    <!-- Find by Volume Name -->  
                  <div class="panel panel-default panel-default">
                     <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapseFour">
                        <a class="accordion-toggle">
                          <?php print $this->translate->_("Volume Name"); ?>
                        </a>
                     </div>
                     <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                           <!-- Find by Volume Name -->
                           <div>
                              <form action="<?php  echo $this->baseUrl.'/job/find-volume-name';?>" method="post">
                                 <b><?php print $this->translate->_("Volume Name"); ?></b>&nbsp;&nbsp;&nbsp;
                                 <?php echo $this->formText('volname', "", array('size' => 40)) ?>
                                 <?php echo $this->formSubmit('ok3', $this->translate->_('Search'), array('class' => 'btn btn-default') ); ?>
                              </form>
                           </div>
                           <!-- end Find by Volume Name -->
                        </div>
                     </div>
                  </div>
                  <!-- end Find by Volume Name -->
                  
                  <!-- List last 20 Jobs run -->
                  <div class="panel panel-default panel-default">
                     <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapseFive">
                        <a class="accordion-toggle">
                          <?php echo $this->translate->_("List last"), ' ', $this->translate->_("Jobs run"); ?>
                        </a>
                     </div>
                     <div id="collapseFive" class="panel-collapse collapse">
                        <div class="panel-body">
                           <!-- List last 20 Jobs run -->
                           <div>
                              <form action="<?php  echo $this->baseUrl.'/job/list-last-jobs-run';?>" method="post">
                                 <b><?php print $this->translate->_("List last"); ?></b>&nbsp;&nbsp;&nbsp;
                                 <?php echo $this->formText('numjob', "20", array('size' => 5)) ?> &nbsp;&nbsp;&nbsp;<b><?php print $this->translate->_("Jobs run"); ?></b>
                                 <?php echo $this->formSubmit('ok4', $this->translate->_('Search'), array('class' => 'btn btn-default') ); ?>
                              </form>
                           </div>
                           <!-- end List last 20 Jobs run -->
                        </div>
                     </div>
                  </div>
                  <!-- end List last 20 Jobs run -->
                  
                  <!-- List Jobs where a given File is saved -->
                  <div class="panel panel-default panel-default panel-default">
                     <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapseSix">
                         <a class="accordion-toggle">
                           <?php print $this->translate->_("File Name"); ?>
                         </a>
                     </div>
                     <div id="collapseSix" class="panel-collapse collapse">
                        <div class="panel-body">
                           <!-- List Jobs where a given File is saved -->
                           <div>
                              <form action="<?php  echo $this->baseUrl.'/job/find-file-name';?>" method="post">
                                 <table>
                                    <tr>
                                       <td class="text-right">
                                          <b><?php print $this->translate->_("Enter path with trailing slash"); ?></b>&nbsp;&nbsp;&nbsp;
                                       </td>
                                       <td>
                                          <?php echo $this->formText('path', "", array('size' => 35)) ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                          <b><sup>*</sup><?php print $this->translate->_("Enter Filename (no path)"); ?></b>&nbsp;&nbsp;&nbsp;
                                       </td>
                                       <td>
                                          <?php echo $this->formText('namefile', "", array('size' => 30)); ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                          <b><?php print $this->translate->_("Type of search<br>(case sensitive)"); ?></b>&nbsp;&nbsp;&nbsp;
                                       </td>
                                       <td class="text-left">
                                          <?php echo $this->formRadio('type_file_search', 'ordinary', null, $this->atype_file_search); ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td class="text-right">
                                          <label for="client_nf"><b><?php print $this->translate->_("Client"); ?></b></label>&nbsp;&nbsp;&nbsp;
                                       </td>
                                       <td>
                                          <?php echo $this->formSelect('client_nf', null, array('class' => 'ui-select', 'style' => 'width: 60%;'), $aclients); ?>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td colspan="2">
                                          <?php echo $this->formSubmit('ok5', $this->translate->_('Search'), array('class' => 'btn btn-default') ); ?>
                                       </td>
                                    </tr>
                                 </table>
                              </form>
                           </div>
                           <!-- end List Jobs where a given File is saved -->
                        </div>
                     </div>
                  </div>
                  <!-- end List Jobs where a given File is saved -->
               </div>
               <!-- end div accordion -->
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-6 -->
</div><!-- end div rows -->
<!-- job/find-form.phtml -->