<!-- job/find-file-name.phtml -->
<div class="rows">
   <div class="col-md-10">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               
               <?php if ($this->msg): ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon-alert"></span>
                 <?php echo $this->msg; ?>
                 </p>
               </div>
               <!-- end div alert -->
               
               <?php endif; ?>
               
               <?php if ($this->result): ?>
               
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                           <th>&nbsp;</th>
                           <th><?php print $this->translate->_("Job Id"); ?></th>
                           <th>&nbsp;</th>
                           <th><?php print $this->translate->_("Name File"); ?></th>
                           <th>
                             <?php 
                                switch ($this->show_job_description) {
                                    case 0 :
                                        echo $this->translate->_("Job Name"); 
                                        break;
                                    case 1 :
                                        echo $this->translate->_("Short Job Description"); 
                                        break;
                                    case 2 :
                                        echo $this->translate->_("Job Name"), ' /<br>',
                                             $this->translate->_("Short Job Description"); 
                                        break;
                                    default :
                                        echo $this->translate->_("Job Name"); 
                                        break;
                                }
                             ?> 
                           </th>
                           <th> <?php print $this->translate->_("Status"); ?> </th>
                           <th> <?php print $this->translate->_("Level"); ?> </th>
                           <th> <?php print $this->translate->_("Client"); ?> </th>
                           <th> <?php print $this->translate->_("Pool"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Start Time"); ?></th>
                           <th class="text-center"> <?php print $this->translate->_("Files"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Bytes"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Errors"); ?> </th>
                        </tr>
                     </thead>
                     <tbody>
                        <?php foreach($this->result as $line) : ?>
                        <tr>
                           <td>
                               <?php
                                   if ( isset($line['poolid'], $line['poolname']) )   {
                                       echo '<a href="',
                                           $this->baseUrl, '/restorejob/main-form/jobid/', $this->escape($line['jobid']),
                                           '" title="', $this->translate->_("Restore Job") , '">',
                                           '<img src="', $this->baseUrl .'/images/restore.png" alt="',
                                           $this->translate->_("Restore Job"), '" border="0" hspace="5"></a>';
                                   }
                               ?>
                           </td>
                           <td>
                              <?php
                                 if ( isset($line['poolid'], $line['poolname']) )   {
                                    echo '<a href="',
                                        $this->baseUrl, '/job/detail/jobid/', $this->escape($line['jobid']),
                                        '" title="', $this->translate->_("Detail Job"), '">';
                                 }
                                 echo $line['jobid'];
                                 if ( isset($line['poolid'], $line['poolname']) )   {
                                    echo '</a>';
                                 }
                              ?>
                           </td>
                        
                           <!-- restore single file -->
                           <td>
                               <?php
                                   if ( isset($line['poolid'], $line['fileid']) )    {
                                       echo '<a href="',
                                           $this->baseUrl, '/restorejob/restore-single-file/fileid/', $this->escape($line['fileid']),
                                           '" title="', $this->translate->_("Restore File") , '">',
                                           '<img src="', $this->baseUrl .'/images/restore-small.png" alt="',
                                           $this->translate->_("Restore File"), '" border="0" hspace="2"></a>';
                                   }
                               ?>
                           </td>
                        
                           <!-- FileName -->
                           <td><?php echo $this->escape($line['path']), $this->escape($line['filename']);?></td>
                        
                           <!-- Job.Name -->
                           <td>
                               <?php  
                               switch ($this->show_job_description) {
                                   case 0 :
                                       // only show Bacula Job Name (behavior as in earlier versions)
                                       echo $this->escape($line['jobname']);
                                       break;
                                   case 1 :
                                       // only show human readable short Job description instead of Bacula Job Name
                                       if ( empty($line['short_desc']) ) 
                                           echo '<i>', $this->escape($line['jobname']), '</i>';
                                       else 
                                           echo $this->escape($line['short_desc']);
                                       break;
                                   case 2 :
                                       // both
                                       echo $this->escape($line['jobname']);
                                       if ( !empty($line['short_desc']) ) 
                                           echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                                       break;
                                   default :
                                       echo $this->escape($line['jobname']);
                                       break;
                               }
                               ?>
                           </td>
                        
                           <!-- Status -->
                           <?php
                              $class_td = 'class="text-center"';
                              if ( $line['joberrors'] != 0 )   {
                                  if ( $line['jobstatus'] == 'T' )   {
                                      $class_td = 'class="text-center warning"';
                                  } else {
                                      // 100% That there was some mistake
                                      $class_td = 'class="text-center danger"';
                                  }
                                 echo '<td ', $class_td, ' class="text-center"> ', $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
                              }
                              elseif   ( $line['jobstatus'] == 'T' ) {
                                 echo '<td class="text-center">OK</td>';
                              } else {
                                  // Errors like no, but something is wrong
                                  if ( $line['jobstatus'] == 'f' )   {
                                      // fatal error
                                        $class_td = 'class="text-center danger"';
                                  } else {
                                      $class_td = 'class="text-center warning"';
                                  }
                                 echo '<td ', $class_td, ' class="text-center">', $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
                              }
                           ?>
                        
                           <td class="text-center"><?php echo $this->escape($line['level']);?></td>
                           <td><?php echo $line['clientname'];?></td>
                        
                           <td>
                              <?php
                                 if ( isset($line['poolid']) && isset($line['poolname']) )   {
                                    echo '<a href="',
                                        $this->baseUrl, "/volume/find-pool-id/id/", $this->escape($line['poolid']),
                                        "/name/", $this->escape($line['poolname']),
                                        '" title="', $this->translate->_("Detail Pool"), '">';
                                 }  else  {
                                    echo "&nbsp;";
                                 }
                        
                                 if ( isset($line['poolid']) && isset($line['poolname']) )   {
                                    echo $this->escape($line['poolname']);
                                    echo '</a>';
                                 }  else {
                                    echo '&nbsp;';
                                 }
                              ?>
                           </td>
                        
                           <td><?php echo $this->escape(date($this->datetime_format,strtotime($line['starttime'])));?></td>
                        
                           <?php
                              if ( ($line['jobfiles'] == 0) && ($line['type'] != 'D') )
                                    $class = 'class="warning"';
                              else
                                    $class = '';
                              echo '<td ', $class, ' class="text-right">', number_format($line['jobfiles']), '</td>';
                           ?>
                        
                           <?php
                                if ( ($line['jobbytes'] == 0) && ($line['type'] != 'D') )
                                    $class = 'class="warning"';
                                else
                                    $class = '';
                              echo '<td ', $class, ' class="text-right">', $this->convBytes($line['jobbytes']), '</td>';
                           ?>
                        
                           <!-- Errors -->
                           <?php
                              if ( $line['joberrors'] == 0 )
                                 echo '<td class="text-right">&nbsp;</td>';
                              else  {
                                  echo '<td class="danger" class="text-right">';
                                  echo '<a href="';
                                 echo $this->baseUrl, '/log/view-log-id/jobid/', $this->escape($line['jobid']),
                                      '" title="', $this->translate->_("View Messages"), '" class="danger">';
                                 echo $this->escape($line['joberrors']), '</a></td>';
                              }
                           ?>
                        </tr>
                        <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
               
               <?php else: ?>

               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon-alert"></span>
                 <?php print $this->translate->_("No Files found."); ?>
                 </p>
               </div>
               <!-- end alert -->
               
               <?php endif; ?>
               
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-10 -->
</div><!-- end div rows -->
<!-- job/find-file-name.phtml -->