<!-- job/find-filters.phtml -->
<?php $urlp = $this->baseUrl . '/job/find-filters' .
    '/date_begin/' . $this->date_begin . '/time_begin/' . $this->time_begin .
    '/date_end/'   . $this->date_end   . '/time_end/'   . $this->time_end .
    '/client/' 	   . $this->client .
    '/fileset/'    . $this->fileset .
    '/jlevel/'     . $this->jlevel .
    '/jstatus/'    . $this->jstatus .
    '/jtype/'      . $this->jtype .
    '/volname/'    . $this->volname .
    '/pool_id/'    . $this->pool_id .
    '/pool_name/'  . $this->pool_name;
?>

<div class="rows">
   <div class="col-md-12">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               
               <?php if (count($this->paginator)): ?>
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                           <th>&nbsp;</th>
                        	<th><a href="<?php echo $urlp; ?>/order/j.JobId">    <?php echo $this->translate->_("Job Id"); ?> </a></th>
                           <th><a href="<?php echo $urlp; ?>/order/j.Name">     
                                <?php 
                                switch ($this->show_job_description) {
                                    case 0 :
                                        echo $this->translate->_("Job Name"); 
                                        break;
                                    case 1 :
                                        echo $this->translate->_("Short Job Description"); 
                                        break;
                                    case 2 :
                                        echo $this->translate->_("Job Name"), ' /<br>',
                                             $this->translate->_("Short Job Description"); 
                                        break;
                                    default :
                                        echo $this->translate->_("Job Name"); 
                                        break;
                                }
                                ?> 
                             </a>
                             </th>
                             <th class="text-center"><a href="<?php echo $urlp; ?>/order/j.JobStatus"><?php echo $this->translate->_("Status"); ?></a></th>
                             <th class="text-center"><a href="<?php echo $urlp; ?>/order/j.Level">    <?php echo $this->translate->_("Level"); ?></a></th>
                             <th class="text-right"><a href="<?php echo $urlp; ?>/order/j.JobFiles"> <?php echo $this->translate->_("Files"); ?></a></th>
                             <th class="text-right"><a href="<?php echo $urlp; ?>/order/j.JobBytes"> <?php echo $this->translate->_("Bytes Stored"); ?></a></th>
                             <th class="text-right"><?php echo $this->translate->_("Bytes Copied"); ?></th>
                             <th class="text-right"><?php echo $this->translate->_("Software Compression"); ?></th>
                             <th class="text-center"><a href="<?php echo $urlp; ?>/order/j.JobErrors"><?php echo $this->translate->_("Errors"); ?></a></th>
                             <th class="text-left"><a href="<?php echo $urlp; ?>/order/c.Name">     <?php echo $this->translate->_("Client"); ?></a></th>
                             <th class="text-left"><a href="<?php echo $urlp; ?>/order/p.Name">     <?php echo $this->translate->_("Pool"); ?></a></th>
                             <th class="text-center"><a href="<?php echo $urlp; ?>/order/j.StartTime"><?php echo $this->translate->_("Start Time"); ?></a></th>
                             <th class="text-center"><a href="<?php echo $urlp; ?>/order/j.EndTime">  <?php echo $this->translate->_("End Time"); ?></a></th>
                             <th class="text-center"><a href="<?php echo $urlp; ?>/order/DurationTime"><?php echo $this->translate->_("Duration"); ?></a></th>
                        </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->paginator as $line): ?>
                        <tr>
                           <td>
                              <?php
                                 if ( isset($line['poolid'], $line['poolname']) ){
                                    echo '<a href="';
                        			   echo $this->baseUrl, '/restorejob/main-form/jobid/', $this->escape($line['jobid']);
                        			   echo '" title="', $this->translate->_("Restore Job"), '">';
                        			   echo '<img src="', $this->baseUrl, '/images/restore.png" alt="', $this->translate->_("Restore Job 2"),'">';
                        			   echo '</a>';
                                 } else {
                                      echo '';
                                 }
                              ?>
                           </td>
                        	<td>
                        		<?php
                        			if ( isset($line['poolid'], $line['poolname']) ){
                        				echo '<a href="';
                        				echo $this->baseUrl, '/job/detail/jobid/', $this->escape($line['jobid']);
                        				echo '" title="', $this->translate->_("Detail Job"), '">';
                        			}
                        			echo $line['jobid'];
                        			if ( isset($line['poolid'], $line['poolname']) ){
                        				echo '</a>';
                        			}
                                 
                        		?>
                        	</td>
                        
                            <!-- Job.Name -->
                           <td>
                               <?php  
                               switch ($this->show_job_description) {
                                   case 0 :
                                       // only show Bacula Job Name (behavior as in earlier versions)
                                       echo $this->escape($line['jobname']);
                                       break;
                                   case 1 :
                                       // only show human readable short Job description instead of Bacula Job Name
                                       if ( empty($line['short_desc']) ) 
                                           echo '<i>', $this->escape($line['jobname']), '</i>';
                                       else 
                                           echo $this->escape($line['short_desc']);
                                       break;
                                   case 2 :
                                       // both
                                       echo $this->escape($line['jobname']);
                                       if ( !empty($line['short_desc']) ) 
                                           echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                                       break;
                                   default :
                                       echo $this->escape($line['jobname']);
                                       break;
                               }
                               ?>
                           </td>
                        
                        	<!-- Status -->
                        	<?php
                        		if ( $line['joberrors'] != 0 )	{
                        		    if ( $line['jobstatus'] == 'T' )	{
                        		        $class_td = 'class="warning"';
                        		    } else {
                        		        // 100% That there was some mistake
                        		        $class_td = 'class="danger"';
                        		    }
                        			echo '<td ', $class_td, ' class="text-center"> ', $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
                        		}
                        		elseif	( $line['jobstatus'] == 'T' )	{
                        			echo '<td class="text-center">OK</td>';
                        		} else {
                        		    // Errors like no, but something is wrong
                        		    if ( ($line['jobstatus'] == 'f') OR ($line['jobstatus'] == 'E') )	{
                        		        // fatal error
                                        $class_td = 'class="danger"';
                        		    } else {
                        		        $class_td = 'class="warning"';
                        		    }
                        			echo '<td ', $class_td, ' class="text-center">',
                        			     $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
                        		}
                        	?>
                        
                        	<td class="text-center"><?php echo $this->escape($line['level']);?></td>
                        	<?php
                                if ( ($line['jobfiles'] == 0) && ($line['type'] != 'B') )
                                    $class = 'class="warning"';
                                else
                                    $class = '';
                        		echo '<td ', $class, ' class="text-right">', number_format($line['jobfiles']), '</td>';
                        	?>
                        
                        	<?php
                                if ( ($line['jobbytes'] == 0) && ($line['type'] != 'B') )
                                    $class = 'class="warning"';
                                else
                                    $class = '';
                         		echo '<td ', $class, ' class="text-right">', $this->convBytes($line['jobbytes']), '</td>';
                        	?>
                       
                                <?php
                                   if ( ($line['filesize'] == 0) && ($line['type'] != 'B') ) {
                                      $class = 'class="text-right warning"';
                                   } else {
                                      $class = 'class="text-right"';
                                   }
                                   echo '<td ', $class, '>', $this->convBytes($line['filesize']), '</td>';
                                ?>
                                
                                <?php
                                   $jobbytes=$line['jobbytes'];
                                   $filesize=$line['filesize'];
                                   if (( $jobbytes != 0) && ($filesize != 0) ){
                                      $filesize == 0 ? 1 : $filesize;
                                      $class = '';
                                      echo '<td class="text-center">', $this->escape( number_format((1-($jobbytes/$filesize))*100,2) ), ' %</td>';
                                    } else {
                                       echo '<td class="text-center">-</td>';
                                    }
                                ?>
 
                        	<!-- Errors -->
                        	<?php
                        		if ( $line['joberrors'] == 0 )
                        			echo '<td class="text-center">-</td>';
                        		else  {
                        		    echo '<td class="danger" text-right">',
                        		         '<a href="',
                        			     $this->baseUrl, '/log/view-log-id/jobid/', $this->escape($line['jobid']), '" title="',
                        			     $this->translate->_("View Messages"), '" class="danger">',
                        			     $this->escape($line['joberrors']), '</a></td>';
                        		}
                        	?>
                        
                        	<td><?php echo $line['clientname'];?></td>
                        
                        	<td>
                        		<?php
                        			if ( isset($line['poolid']) && isset($line['poolname']) )	{
                        				echo '<a href="';
                        				echo $this->baseUrl, "/volume/find-pool-id/id/", $this->escape($line['poolid']),
                        				"/name/", $this->escape($line['poolname']);
                        				echo '" title="', $this->translate->_("Detail Pool"), '">';
                        			}	else 	{
                        				echo "&nbsp;";
                        			}
                        
                        			if ( isset($line['poolid']) && isset($line['poolname']) )	{
                        				echo $this->escape($line['poolname']);
                        				echo '</a>';
                        			}	else {
                        				echo '&nbsp;';
                        			}
                        		?>
                        	</td>
                        
                        	<td class="text-center"><?php echo $this->escape(date($this->datetime_format,strtotime($line['starttime'])));?></td>
                        	<td class="text-center"><?php echo $this->escape(date($this->datetime_format,strtotime($line['endtime'])));?></td>
                        	<td class="text-center"><?php echo $this->escape($line['durationtime']);?></td>
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                     <tfoot></tfoot>
                  </table>
               </div><!-- end div table-responsive -->
               
               <!-- start paginationControl -->
               <?php
                   echo $this->paginationControl($this->paginator, 'Sliding', 'job/find_filters_pagination_ctrl.phtml',
                       array('options' => array(
                       'date_begin' => $this->date_begin,
                       'time_begin' => $this->time_begin,
                       'date_end' => $this->date_end,
                       'time_end' => $this->time_end,
                       'client' => $this->client,
                       'fileset' => $this->fileset,
                       'jlevel' => $this->jlevel,
                       'jstatus' => $this->jstatus,
                       'jtype' => $this->jtype,
                       'volname' => $this->volname
                       ))
                   );
               ?>
               <!-- end paginationControl -->
               
               <?php else: ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                  <span class="glyphicon glyphicon-alert"></span>
                  <?php print $this->translate->_("No Jobs found.");; ?>
                  </p>
                  <p>
                     <a href="<?php echo $this->baseUrl, '/job/list-last-jobs-run/numjob/20'; ?>">
                      <?php print $this->translate->_("See List last 20 Jobs run"); ?>
                     </a>
                  </p>
               </div>
               <!-- end div alert -->
               
               <?php endif; ?>
               
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div rows -->
<!-- job/find-filters.phtml -->
