<!-- job/next-dashboard.phtml -->
<div class="panel panel-default panel-primary">
   <div class="panel-heading">
      <a href="<?php echo $this->baseUrl;?>/job/next" id="dashboard"><?php echo $this->escape($this->title); ?></a>
   </div>
   <div class="panel-body">
      <p>
         
         <?php if ($this->result): ?>
         <?php
            if ($this->result[0] == 'NOFOUND') {
         ?>
               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon-alert"></span>
                 <?php print $this->translate->_("ERROR: Cannot execute bconsole. File not found.") ?>
                 </p>
               </div>
               <!-- end div alert -->        

         <?php
            }
            elseif ($this->result[0] == 'ERROR') {
         ?>
                  <!-- div alert -->
                  <div class="alert alert-danger">
                    <p>
                    <span class="glyphicon glyphicon-alert"></span>
                    <?php print $this->translate->_("ERROR: There was a problem executing bconsole. See below.").'<br/>';
                    foreach ($this->result as $line) {
                      echo $line, '<br/>';
                    }
                    ?>
                    </p>
                  </div>
                  <!-- end div alert -->
                 
         <?php
            } else   {
         ?>
         <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed">
               <thead>
                  <tr>
                     <th class="text-left"><?php
                         switch ($this->show_job_description) {
                             case 0 :
                                 echo $this->translate->_("Job Name"); 
                                 break;
                             case 1 :
                                 echo $this->translate->_("Short Job Description"); 
                                 break;
                             case 2 :
                                 echo $this->translate->_("Job Name"), ' /<br>',
                                      $this->translate->_("Short Job Description");
                                 break;
                             default :
                                 echo $this->translate->_("Job Name");
                                 break;
                         }
                      ?> 
                     </th>
                     <th class="text-center"> <?php print $this->translate->_("Level"); ?></th>
                     <th class="text-left"> <?php print $this->translate->_("Type"); ?></th>
                     <th class="text-center"> <?php print $this->translate->_("Priority"); ?></th>
                     <th class="text-center"> <?php print $this->translate->_("Scheduled"); ?></th>
                     <th class="text-left"> <?php print $this->translate->_("Volume"); ?></th>
                  </tr>
               </thead>
               <tbody>
               <?php foreach($this->result as $line) : ?>
                  <tr>
                     <!-- Job.Name -->
                     <td><?php  
                         switch ($this->show_job_description) {
                             case 0 :
                                 // only show Bacula Job Name (behavior as in earlier versions)
                                 //echo $this->escape($line['name']);
                                 echo "<a href='".$this->baseUrl . "/job/show-job/jobname/" . $this->escape($line['name']) ."' title='" . $this->translate->_("Detail Job"). "'>".$this->escape($line['name'])."</a>";
                                 break;
                             case 1 :
                                 // only show human readable short Job description instead of Bacula Job Name
                                 if ( empty($line['short_desc']) ) 
                                     echo '<i>', $this->escape($line['name']), '</i>';
                                 else 
                                     echo $this->escape($line['short_desc']);
                                 break;
                             case 2 :
                                 // both
                                 echo $this->escape($line['name']);
                                 if ( !empty($line['short_desc']) ) 
                                     echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                                 break;
                             default :
                                 echo $this->escape($line['name']);
                                 break;
                         }
                         ?>
                     </td>
                     <td class="text-center"><?php echo $this->escape($line['level']);?></td>
                     <td class="text-left"><?php echo $this->escape($line['type']);?></td>
                     <td class="text-center"><?php echo $this->escape($line['pri']);?></td>
                     <td class="text-center"><?php echo $this->escape($line['date']);?></td>
                     <td class="text-left"><?php if ($this->escape($line['vol']) === '*unknown*') : ?>
                         <?php echo $this->escape($line['vol']); ?>
                         <?php else : ?><a href="<?php echo $this->baseUrl, "/volume/find-name/volname/", $this->escape($line['vol']);?>"  title="<?php print $this->translate->_("Detail Volume");?>">
                         <?php echo $this->escape($line['vol']);?></a><?php endif; ?>
                     </td>
                  </tr>
               <?php endforeach; ?>
               </tbody>
            </table>
         </div><!-- end div table-responsive -->
         
         <?php
         } // end else
         ?>
         
         <?php else : ?>
         
         <!-- div alert -->
         <div class="alert alert-danger">
           <p>
           <span class="glyphicon glyphicon-alert"></span>
           <?php print $this->translate->_("No Scheduled Jobs found."); ?>
           </p>
         </div>
         <!-- end div alert -->  
         
         <?php endif; ?>
         
      </p><!-- end p -->
   </div><!-- end  div panel-body -->
</div><!-- end div panel panel-default -->
<!-- job/next-dashboard.phtml -->