<!-- job/next.phtml -->
<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               <?php if ($this->result): ?>
               <?php
               	if ($this->result[0] == 'NOFOUND') {
               ?>
                       <!-- div alert -->
                       <div class="alert alert-danger">
                         <p>
                         <span class="glyphicon glyphicon-alert"></span>
                         <?php print $this->translate->_("ERROR: Cannot execute bconsole. File not found.") ?>
                         </p>
                       </div>
                       <!-- end div alert -->
               <?php
               	}
                	elseif ($this->result[0] == 'ERROR') {
               ?>
                       <!-- div alert -->
                       <div class="alert alert-danger">
                         <p>
                         <span class="glyphicon glyphicon-alert"></span>
                         <?php print $this->translate->_("ERROR: There was a problem executing bconsole. See below.").'<br/>';
                		    foreach ($this->result as $line) {
               		    	echo $line, '<br/>';
               		    }
                         ?>
                         </p>
                       </div>
                       <!-- end div alert -->
                       
               <?php
                	} else {
               ?>
               
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                            <th>
                            <?php 
                                switch ($this->show_job_description) {
                                    case 0 :
                                        echo $this->translate->_("Job Name"); 
                                        break;
                                    case 1 :
                                        echo $this->translate->_("Short Job Description"); 
                                        break;
                                    case 2 :
                                        echo $this->translate->_("Job Name"), ' /<br>',
                                             $this->translate->_("Short Job Description"); 
                                        break;
                                    default :
                                        echo $this->translate->_("Job Name"); 
                                        break;
                                }
                             ?> 
                             </th>
                            <th class="text-center"><?php print $this->translate->_("Level"); ?></th>
                            <th class="text-left"><?php print $this->translate->_("Type"); ?></th>
                            <th class="text-center"><?php print $this->translate->_("Priority"); ?></th>
                            <th class="text-center"> <?php print $this->translate->_("Scheduled"); ?></th>
                            <th><?php print $this->translate->_("Volume"); ?></th>
                            <th class="text-center"> <?php print $this->translate->_("% Free space<br /> on Volume"); ?></th>
                        </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->result as $line) : ?>
                        <tr>
                            <!-- Job.Name -->
                            <td>
                                <?php  
                                switch ($this->show_job_description) {
                                    case 0 :
                                        // only show Bacula Job Name (behavior as in earlier versions)
                                        echo $this->escape($line['name']);
                                        break;
                                    case 1 :
                                        // only show human readable short Job description instead of Bacula Job Name
                                        if ( empty($line['short_desc']) ) 
                                            echo '<i>', $this->escape($line['name']), '</i>';
                                        else 
                                            echo $this->escape($line['short_desc']);
                                        break;
                                    case 2 :
                                        // both
                                        echo $this->escape($line['name']);
                                        if ( !empty($line['short_desc']) ) 
                                            echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                                        break;
                                    default :
                                        echo $this->escape($line['name']);
                                        break;
                                }
                                ?>
                            </td>
                        
                            <td class="text-center"><?php echo $this->escape($line['level']);?></td>
                            <td><?php echo $this->escape($line['type']);?></td>
                            <td class="text-center"><?php echo $this->escape($line['pri']);?></td>
                            <td class="text-center"><?php echo $this->escape($line['date']);?></td>
                            <td class="text-left"><?php if ($this->escape($line['vol']) === '*unknown*') : ?>
                                    <?php echo $this->escape($line['vol']); ?>
                                <?php else : ?>
                                    <a href="<?php echo $this->baseUrl, "/volume/find-name/volname/",
                        			$this->escape($line['vol']);?>"  title="<?php print $this->translate->_("Detail Volume");?>">
                                        <?php echo $this->escape($line['vol']);?></a>
                                <?php endif; ?>
                            </td>
                        
                            <?php
                        	$class = '';
                        	switch ($line['volfree'])  {
                        	case $this->unknown_volume_capacity:
                                    $line['volfree'] = $this->translate->_('Unknown');
                        	    break;
                        	case $this->err_volume:
                                    $class = 'class="text-center danger"';
                                    $line['volfree'] = $this->translate->_('Volume with Errors');
                        	    break;
                        	case $this->new_volume:
                                    $line['volfree'] = $this->translate->_('New Volume');
                                    break;
                            	default:
                                    if ( $line['volfree'] < 3 )
                                        $class = 'class="text-center warning"';
                                    elseif ( $line['volfree'] < 7 )
                                        $class = 'class="text-center warning"';
                        	    else
                                        $class = 'class="text-center"';
                                    break;
                        	}
                        	echo '<td ',$class,'>',$line['volfree'] ,' %</td>';
                            ?>
                        
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
               
               <?php
               }
               ?>
               
               <?php else : ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon-alert"></span>
                 <?php print $this->translate->_("No Scheduled Jobs found."); ?>
                 </p>
               </div>
               <!-- end div alert -->               
               
               <?php endif; ?>
               
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div rows -->
<!-- job/next.phtml -->
