<!-- job/problem-dashboard.phtml -->
<div class="panel panel-default panel-danger">
   <div class="panel-heading">
      <a href="<?php echo $this->baseUrl;?>/job/problem" id="dashboard"><?php echo $this->escape($this->title); ?></a>
   </div>
   <div class="panel-body">
      <p>
         <?php if ($this->result): ?>
         <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed">
               <thead>
                  <tr>
                     <th>&nbsp;</th>
                     <th> <?php print $this->translate->_("JobId"); ?> </th>
                     <th> 
                       <?php 
                          switch ($this->show_job_description) {
                              case 0 :
                                  echo $this->translate->_("Job Name"); 
                                  break;
                              case 1 :
                                  echo $this->translate->_("Short Job Description"); 
                                  break;
                              case 2 :
                                  echo $this->translate->_("Job Name"), ' /<br>',
                                       $this->translate->_("Short Job Description"); 
                                  break;
                              default :
                                  echo $this->translate->_("Job Name"); 
                                  break;
                          }
                       ?> 
                     </th>
                     <th class="text-center"><?php print $this->translate->_("Status"); ?></th>
                     <th class="text-center"><?php print $this->translate->_("Level"); ?></th>
                     <th class="text-right"><?php print $this->translate->_("Files"); ?></th>
                     <th class="text-right"><?php print $this->translate->_("Bytes"); ?></th>
                     <th class="text-center"><?php print $this->translate->_("Errors"); ?></th>
                     <th class="text-center"><?php print $this->translate->_("End Time"); ?></th>
                  </tr>
               </thead>
               <tbody>
               <?php foreach($this->result as $line) : ?>
                  <tr>
                     <td>
                          <?php
                              if ( isset($line['jobname']) && ($line['type'] != 'R') )    {
                                 // re-run button
                                 echo '<a href="';
                                 echo $this->baseUrl, '/job/run-job/jobname/', $this->escape($line['jobname']);
                                 echo '" title="', $this->translate->_("Re-run Job"), '">';
                                 echo '<img src="', $this->baseUrl, '/images/re-run-job-small.png" alt="', $this->translate->_("Re-run Job"), '" border="0" hspace="2">';
                                 echo '</a>';
                              }
                          ?>
                     </td>
                  	<td>
                  		<?php
                  			if ( isset($line['poolid']) && isset($line['poolname']) )	{
                  				echo '<a href="';
                  				echo $this->baseUrl, '/job/detail/jobid/', $this->escape($line['jobid']);
                  				echo '" title="', $this->translate->_("Detail Job"), '">';
                  			}
                  			echo $line['jobid'];
                  			if ( isset($line['poolid']) && isset($line['poolname']) )	{
                  				echo '</a>';
                  			}
                  		?>
                  	</td>

                  	<!-- Job Name -->
                     <td>
                         <?php  
                         switch ($this->show_job_description) {
                             case 0 :
                                 // only show Bacula Job Name (behavior as in earlier versions)
                                 echo $this->escape($line['jobname']);
                                 break;
                             case 1 :
                                 // only show human readable short Job description instead of Bacula Job Name
                                 if ( empty($line['short_desc']) ) 
                                     echo '<i>', $this->escape($line['jobname']), '</i>';
                                 else 
                                     echo $this->escape($line['short_desc']);
                                 break;
                             case 2 :
                                 // both
                                 echo $this->escape($line['jobname']);
                                 if ( !empty($line['short_desc']) ) 
                                     echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                                 break;
                             default :
                                 echo $this->escape($line['jobname']);
                                 break;
                         }
                         ?>
                     </td>
                  
                  	<!-- Status -->
                  	<?php
                  		$class_td = 'class="text-center"';
                  		if ( $line['joberrors'] != 0 )	{
                  		    if ( $line['jobstatus'] == 'T' )	{
                  		        $class_td = 'class="text-center warning"';
                  		    } else {
                  		        // 100% That there was some mistake
                  		        $class_td = 'class="text-center danger"';
                  		    }
                  			echo '<td ', $class_td, '> ',
                  			     $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
                  		}
                  		elseif	( $line['jobstatus'] == 'T' )	{
                  			echo '<td class="text-center">OK</td>';
                  		} else {
                  		    // Errors like no, but something is wrong
                  		    if ( ($line['jobstatus'] == 'f') OR ($line['jobstatus'] == 'E') )	{
                  		        // fatal error
                  		        $class_td = 'class="text-center danger"';
                  		    } else {
                  		    	$class_td = 'class="text-center warning"';
                  		    }
                  			echo '<td ', $class_td, '>',
                  			     $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
                  		}
                  	?>
                     <!-- Level -->
                  	<td class="text-center"><?php echo $this->escape($line['level']);?></td>
                  
                  	<!-- Job Files / JobBytes -->
                     <?php
                  		$class = 'class="text-right"';
                  		if ( ($line['jobfiles'] == 0) && ($line['type'] != 'D') ) $class = 'class="text-right warning"';
                  		echo '<td ', $class, '>', number_format($line['jobfiles']), '</td>';
                  		if ( ($line['jobbytes'] == 0) && ($line['type'] != 'D') ) $class_td = 'class="text-right warning"';
                  		echo '<td ', $class, '>', $this->convBytes($line['jobbytes']), '</td>';
                  	?>
                  
                  	<!-- Errors -->
                  	<?php
                  		if ( $line['joberrors'] == 0 )
                  			echo '<td class="text-center">-</td>';
                  		else {
                  		    echo '<td class="text-center danger">';
                  		    echo '<a href="';
                  			echo $this->baseUrl, '/log/view-log-id/jobid/', $this->escape($line['jobid']), '" title="',
                  			     $this->translate->_("View Messages"), '" class="danger">';
                  			echo $this->escape($line['joberrors']), '</a></td>';
                  		}
                  	?>
                     <!-- End Time -->
                  	<td><?php echo $this->escape(date($this->datetime_format, strtotime($line['endtime'])));?></td>
                  </tr>
               <?php endforeach; ?>
               </tbody>
            </table>
         </div><!-- end div table-responsive -->
         
         <?php else: ?>
         
         <!-- div alert -->
         <div class="alert alert-danger">
           <p>
           <span class="glyphicon glyphicon-alert"></span>
           <?php print $this->translate->_("No Jobs found."); ?>
           </p>
         </div>
         <!-- end div alert -->         
         
         <?php endif; ?>
         
      </p><!-- end p -->
   </div><!-- end div panel-body -->
</div><!-- end div panel panel-default -->
<!-- job/problem-dashboard.phtml -->