<!-- job/run-job.phtml -->
<style>
  .select-overflow { height: auto; max-height: 200px;}
</style>
<script type="text/javascript">
$(document).ready(function() {
	$('#ok1').click(function() {
    	$.blockUI({
        	message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
        	css: { backgroundColor: '#f3fcf2' },
        	centerX: true,
        	centerY: true
        });
    });
});
</script>
<script type="text/javascript">
  //select
  $(function(){
      $('select').each(function() {
          //var t = $(this).selectmenu({maxHeight: 300});
	      //    eval(t);
		  //$(this).selectmenu().selectmenu("menuWidget").addClass("select-overflow");
	  });
  });
</script>
<script type="text/javascript">
function whenNow(elm)
{
    // console.log('checkbox : ' + elm.checked); // for debug firebug
    if (elm.checked)
    {
        document.form1.date_when.disabled = true;
        document.form1.time_when.disabled = true;
    }
    else    {
        document.form1.date_when.disabled = false;
        document.form1.time_when.disabled = false;
    }
}
</script>

<script type="text/javascript" src="<?php echo $this->baseUrl , '/scripts/jquery-ui.datepicker-', $this->language, '.js';?>"></script>
<script type="text/javascript">
$(function() {
    $('#date_when').datepicker({
        dateFormat: 'yy-mm-dd',
        changeMonth: true,
        changeYear: true
    });
});
</script>

<div>
<?php
    if ( $this->result_error )
    {
        switch ( $this->result_error )
        {
            case 'ERROR_BCONSOLE': // ошибка при запуске bconsole
                $msg = $this->translate->_('ERROR: There was a problem executing bconsole.');
                break;
            case 'NOFOUND_BCONSOLE': // bconsole не найден
                $msg = $this->translate->_('ERROR: bconsole not found.');
                break;
            default: $msg = '';
        }
        echo '<font color="red"><div align="center"><p>' . $msg . '</p></div></font>';
        echo '<font color="red">';
        if ( $this->command_output )
        {
            foreach ($this->command_output as $line) {
             echo $line . '<br>';
          }
        }
        echo '</font>';
    }
?>

</div>
<?php
    $this->form->setAction( $this->url());
	 $this->form->setActionCancel( $this->baseUrl . "/index/index" );
    //echo $this->form;
?>

<div class="rows">
  <div class="col-md-8">

<div class="panel panel-default panel-primary">
	<div class="panel-heading">
	   <?php echo $this->escape($this->title); ?>
	</div>
	<div class="panel-body">
	   <p>

      <?php echo $this->form; ?>

	   </p><!-- close p -->
    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->

</div><!-- fim div col-md-8 -->
</div><!-- fim da div row -->
