<!-- job/run-job.phtml -->
<script type="text/javascript">
$(document).ready(function(){
   $('#ok1').click(function() {
      $.blockUI({
         message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
         css: { backgroundColor: '#f3fcf2' },
         centerX: true,
         centerY: true
        });
    });
});
</script>
<script type="text/javascript">
$(document).ready(function(){
   $('select').each(function() {
          $(this).addClass("select-overflow").addClass("form-control");
   });
  });
</script>
<script type="text/javascript">
function whenNow(elm)
{
    // console.log('checkbox : ' + elm.checked); // for debug firebug
    if (elm.checked)
    {
        document.form1.date_when.disabled = true;
        document.form1.time_when.disabled = true;
    }
    else    {
        document.form1.date_when.disabled = false;
        document.form1.time_when.disabled = false;
    }
}
</script>

<script type="text/javascript" src="<?php echo $this->baseUrl , '/scripts/jquery-ui.datepicker-', $this->language, '.js';?>"></script>
<script type="text/javascript">
$(function() {
    $('#date_when').datepicker({
        dateFormat: 'yy-mm-dd',
        changeMonth: true,
        changeYear: true
    });
    
    $('#date_when').on('change',function(){
        var dt = new Date();
        var currentTime = dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();
        $('#time_when').val(currentTime);
    });    
});
</script>

<?php
    $this->form->setAction( $this->url());
    $this->form->setActionCancel( $this->baseUrl . "/index/index" );
?>

<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
            
               <?php if ( $this->result_error ): ?>
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                     <span class="glyphicon glyphicon-alert"></span>
                     <?php
                     echo $this->escape($this->title), '<br>';
                        switch ( $this->result_error ) {
                           case 'ERROR_BCONSOLE': // Error when bconsole starts
                              $msg = $this->translate->_('ERROR: There was a problem executing bconsole.');
                              break;
                           case 'NOFOUND_BCONSOLE': // Bconsole not found
                              $msg = $this->translate->_('ERROR: bconsole not found.');
                              break;
                           default: $msg = '';
                        }
                        echo $msg;
                        if ( $this->command_output ) {
                           foreach ($this->command_output as $line) {
                              echo '<br/>', $line, '<br/>';
                           }
                        }
                     ?>
                  </p>
               </div>
               <!-- end div alert -->
                               
               <?php endif; ?>    

               <!-- form -->
               <?php echo $this->form; ?>
               <!-- end form -->
            
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div row -->
<!-- job/run-job.phtml -->