<!-- job/running.phtml -->
<h1 align="center"><?php echo $this->escape($this->titleDirRunningJobs); ?></h1>

<?php if ($this->resultDirRunningJobs): ?>
<?php
	if ($this->resultDirRunningJobs[0] == 'NOFOUND') {
		echo '<font color="red"><div align="center"><p>',
		      $this->translate->_("ERROR: Cannot execute bconsole. File not found."), '</p></div></font>';
	}
 	elseif ($this->resultDirRunningJobs[0] == 'ERROR') {
 		echo '<font color="red"><div align="center"><p>',
 		     $this->translate->_("ERROR: There was a problem executing bconsole. See below."), '</p></div>';
 		foreach ($this->resultDirRunningJobs as $line) {
			echo $line, '<br>';
		}
		echo '</font>';
 	} else	{
?>

<div align="center">
<table id="box-table">
<thead>
<tr>
	 <th scope="col"> <?php print $this->translate->_("Job Id");   ?> </th>
     <th scope="col"> <?php print $this->translate->_("Level");    ?> </th>
     <th scope="col"> <?php print $this->translate->_("Job Name"); ?> </th>
     <th scope="col"> <?php print $this->translate->_("Status");   ?> </th>
</tr>
</thead>
<tbody>
<?php foreach($this->resultDirRunningJobs as $line) : ?>
<tr>
	<td><?php echo $this->escape($line['id']);?></td>
	<td><?php echo $this->escape($line['level']);?></td>
	<td><?php echo $this->escape($line['name']);?></td>
	<td><?php echo $this->escape($line['status']);?></td>
</tr>
<?php endforeach; ?>
<tbody>
</table>
</div>

<?php
}
?>

<?php else : ?>
<div class="ui-widget" style="width: 50%; margin-left: auto; margin-right: auto;">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;"> 
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("Information from Director : No Running Jobs found."); ?></strong></p>
	</div>
</div>
<?php endif; ?>


<p>&nbsp;</p>



<h1 align="center"><?php echo $this->escape($this->titleRunningJobs); ?></h1>

<?php if ($this->resultRunningJobs): ?>

<div align="center">
<table id="box-table">
<thead>
<tr>
	 <th scope="col"> <?php print $this->translate->_("Job Id"); 	 ?> </th>
     <th scope="col"> <?php print $this->translate->_("Job Name"); ?> </th>
     <th scope="col"> <?php print $this->translate->_("Status"); 	 ?> </th>
     <th scope="col"> <?php print $this->translate->_("Level");    ?> </th>
     <th scope="col"> <?php print $this->translate->_("Errors"); ?> </th>
     <th scope="col"> <?php print $this->translate->_("Client");   ?> </th>
     <th scope="col"> <?php print $this->translate->_("Pool"); 	 ?> </th>
     <th scope="col"> <?php print $this->translate->_("Start Time"); ?><br /> <?php print $this->translate->_("yy-mm-dd"); ?> </th>
     <th scope="col"> <?php print $this->translate->_("Duration"); ?> <br /> <?php print $this->translate->_("hh-mm-ss"); ?> </th>
</tr>
</thead>
<tbody>
<?php foreach($this->resultRunningJobs as $line) : ?>
<tr>
	<td><?php echo $this->escape($line['jobid']);?></td>

	<td><?php echo $this->escape($line['jobname']);?></td>

	<?php
		if ( $this->escape($line['joberrors']) != 0 )	{
			echo '<td class="err" align="center"> ',
			     $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
		}
		else
			echo '<td align="center">',
			     $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
	?>

	<td align="center"><?php echo $this->escape($line['level']);?></td>
	
	<?php
		if ( $this->escape($line['joberrors']) == 0 )
			echo '<td align="right">-</td>';
		else
			echo '<td class="err" align="right">', $this->escape($line['joberrors']), '</td>';
	?>
	
	<td ><?php echo $this->escape($line['clientname']);?></td>

	<td><a href="<?php echo $this->baseUrl, "/volume/find-pool-id/id/", $this->escape($line['poolid']),
		"/name/", $this->escape($line['poolname']);?>" title="<?php print $this->translate->_("Detail Pool"); ?>">
		<?php echo $this->escape($line['poolname']);?></a>
	</td>

	<td><?php echo $this->escape($line['starttime']);?></td>
	<td align="right"><?php echo $this->escape($line['durationtime']);?></td>

</tr>
<?php endforeach; ?>
</tbody>
</table>
</div>

<?php else: ?>
<div class="ui-widget" style="width: 50%; margin-left: auto; margin-right: auto;">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;"> 
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("Information from DB Catalog : No Running Jobs found.");?></strong></p>
	</div>
</div>
<?php endif; ?>