<!-- job/running-dashboard.phtml -->
<div class="panel panel-default panel-success">
   <div class="panel-heading">
      <a href="<?php echo $this->baseUrl;?>/job/running" id="dashboard"><?php echo $this->escape($this->titleDirRunningJobs); ?></a>
   </div>
   <div class="panel-body">
      <p>
         
         <?php if ($this->resultDirRunningJobs): ?>
         <?php
            if ($this->resultDirRunningJobs[0] == 'NOFOUND') {
         ?>
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                  <span class="glyphicon glyphicon-alert"></span>
                  <?php print $this->translate->_("ERROR: Cannot execute bconsole. File not found.") ?>
                  </p>
               </div>
               <!-- end div alert -->
         <?php
            }
            elseif ($this->resultDirRunningJobs[0] == 'ERROR') {
         ?>
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                  <span class="glyphicon glyphicon-alert"></span>
                  <?php print $this->translate->_("ERROR: There was a problem executing bconsole. See below.").'<br/>';
                foreach ($this->resultDirRunningJobs as $line) {
                   echo $line, '<br/>';
                }
                  ?>
                  </p>
               </div>
               <!-- end div alert -->
         <?php
            } else   {
         ?>
         <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed">
               <thead>
                  <tr>
                     <th class="text-center">&nbsp;&nbsp; <?php print $this->translate->_("Job Id");?>&nbsp;&nbsp;</th>
                     <th class="text-center">&nbsp;&nbsp; <?php print $this->translate->_("Type"); ?>&nbsp;&nbsp; </th>
                     <th class="text-center"> <?php print $this->translate->_("Level");  ?> </th>
                     <th><?php echo $this->translate->_("Job Name").'/'.$this->translate->_("Status");?></th>
                  </tr>
               </thead>
               <tbody>
               <?php foreach($this->resultDirRunningJobs as $line) : ?>
                  <tr>
                     <td class="text-center"> 
                         <i class="fa fa-refresh fa-spin"></i>
                         <a href="<?php echo $this->baseUrl .'/log/view-log-id/jobid/'. $this->escape($line['id']). '/jobname/' . $this->escape($line['name']); ?>" title="<?php echo $this->translate->_("The Job is Running"); ?>">
                             &nbsp;<?php echo $this->escape($line['id']);?>
                        </a>
                     </td>
                     <td class="text-center"><?php echo $this->escape($line['level']);?></td>
                     <!-- Job Name -->
                     <td> <?php  echo $this->escape($line['name']);?> </td>
                     <td><?php echo $this->escape($line['status']);?></td>
                  </tr>
               <?php endforeach; ?>
               </tbody>
            </table>
         </div><!-- end div table-responsive -->
         
         <?php
         }
         ?>
         
         <?php else : ?>

         <!-- div alert -->
         <div class="alert alert-warning">
           <p>
           <span class="glyphicon glyphicon-info-sign"></span>
           <?php print $this->translate->_("Information from Director : No Running Jobs found."); ?>
           </p>
         </div>
         <!-- end div alert -->
         
         <?php endif; ?>
         
         
      </p><!-- close p -->
   </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->
         
<div class="panel panel-default panel-success">
   <div class="panel-heading">
      <a href="<?php echo $this->baseUrl;?>/job/running" id="dashboard"><?php echo $this->escape($this->titleRunningJobs); ?></a>
   </div>
   <div class="panel-body">
      <p>
                  
         <?php if ($this->resultRunningJobs): ?>
                  
         <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed">
               <thead>
                  <tr>
                     <th class="text-center">&nbsp;&nbsp;<?php print $this->translate->_("Job Id"); ?>&nbsp;&nbsp;</th>
                     <th> 
                       <?php 
                          switch ($this->show_job_description) {
                              case 0 :
                                  echo $this->translate->_("Job Name"); 
                                  break;
                              case 1 :
                                  echo $this->translate->_("Short Job Description"); 
                                  break;
                              case 2 :
                                  echo $this->translate->_("Job Name"), ' /<br>',
                                       $this->translate->_("Short Job Description"); 
                                  break;
                              default :
                                  echo $this->translate->_("Job Name"); 
                                  break;
                          }
                       ?> 
                     </th>
                     <th><?php print $this->translate->_("Status");   ?> </th>
                     <th class="text-center"> <?php print $this->translate->_("Level");    ?></th>
                     <th class="text-center"> <?php print $this->translate->_("Errors"); ?></th>
                     <th><?php print $this->translate->_("Client");   ?> </th>
                     <th class="text-center"> <?php print $this->translate->_("Start Time"); ?></th>
                  </tr>
               </thead>
               <tbody>
                  <?php foreach($this->resultRunningJobs as $line) : ?>
                  <tr>
                     <td class="text-center">
                        <i class="fa fa-refresh fa-spin"></i>
                        <a href="<?php echo $this->baseUrl .'/log/view-log-id/jobid/'. $this->escape($line['jobid']). '/jobname/' . $this->escape($line['jobname']); ?>" title="<?php echo $this->translate->_("The Job is Running"); ?>">
                            &nbsp;<?php echo $this->escape($line['jobid']);?>
                        </a>
                     </td>
                      <!-- Job Name -->
                     <td>
                        <?php  
                        switch ($this->show_job_description) {
                            case 0 :
                                // only show Bacula Job Name (behavior as in earlier versions)
                                echo $this->escape($line['jobname']);
                                break;
                            case 1 :
                                // only show human readable short Job description instead of Bacula Job Name
                                if ( empty($line['short_desc']) ) 
                                    echo '<i>', $this->escape($line['jobname']), '</i>';
                                else 
                                    echo $this->escape($line['short_desc']);
                                break;
                            case 2 :
                                // both
                                echo $this->escape($line['jobname']);
                                if ( !empty($line['short_desc']) ) 
                                    echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                                break;
                            default :
                                echo $this->escape($line['jobname']);
                                break;
                        }
                        ?>
                     </td>
                      
                      <?php
                          if ( $this->escape($line['joberrors']) != 0 ) {
                              echo '<td class="text-left danger"> ',
                                  $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
                          }
                          else
                              echo '<td class="text-left">',
                                  $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
                      ?>
                  
                      <td class="text-center"><?php echo $this->escape($line['level']);?></td>
                  
                      <?php
                          if ( $this->escape($line['joberrors']) == 0 )
                              echo '<td class="text-center">-</td>';
                          else
                              echo '<td class="text-center danger">', $this->escape($line['joberrors']), '</td>';
                      ?>
                  
                     <td><?php echo $this->escape($line['clientname']);?></td>
                     <td><?php echo $this->escape(date($this->datetime_format,strtotime($line['starttime'])));?></td>
                  </tr>
               <?php endforeach; ?>
               </tbody>
            </table>
         </div><!-- end div table-responsive -->
                  
         <?php else: ?>
                  
         <!-- div alert -->
         <div class="alert alert-warning">
           <p>
           <span class="glyphicon glyphicon-info-sign"></span>
           <?php print $this->translate->_("Information from DB Catalog : No Running Jobs found.");?>
           </p>
         </div>
         <!-- end div alert -->
                  
         <?php endif; ?>
      </p><!-- end p -->
   </div><!-- end div panel-body -->
</div><!-- end div panel panel-default -->
<!-- job/running-dashboard.phtml -->
