<!-- job/running.phtml -->

<div class="rows">
  <div class="col-md-8">

<div class="panel panel-default panel-success">
	<div class="panel-heading">
	   <?php echo $this->escape($this->titleDirRunningJobs); ?>
	</div>
	<div class="panel-body">
	   <p>

<?php if ( $this->resultDirRunningJobs ): ?>
<?php
	if ($this->resultDirRunningJobs[0] == 'NOFOUND') {
?>
        <div class="alert alert-danger">
          <p>
          <span class="glyphicon glyphicon-alert"></span>
          <?php print $this->translate->_("ERROR: Cannot execute bconsole. File not found.") ?>
          </p>
        </div>
<?php
	}
 	elseif ($this->resultDirRunningJobs[0] == 'ERROR') {
?>
        <div class="alert alert-danger">
          <p>
          <span class="glyphicon glyphicon-alert"></span>
          <?php print $this->translate->_("ERROR: There was a problem executing bconsole. See below.").'<br/>';
 		    foreach ($this->resultDirRunningJobs as $line) {
		    	echo $line, '<br/>';
		    }
          ?>
          </p>
        </div>
<?php
 	} else	{
?>
<div class="table-responsive">
<table id="box-table2" class="table table-striped table-hover table-condensed">
<!--<caption><?php echo $this->escape($this->titleDirRunningJobs); ?></caption>-->
<thead>
<tr>
     <th scope="col"> <?php print $this->translate->_("Job Id");   ?> </th>
     <th scope="col"> <?php print $this->translate->_("Type");    ?> </th>
     <th scope="col"> <?php print $this->translate->_("Level");    ?> </th>
     <th scope="col"> <?php echo $this->translate->_("Job Name").'/'.$this->translate->_("Status");  ?> </th>
</tr>
</thead>
<tbody>
<?php foreach($this->resultDirRunningJobs as $line) : ?>
<tr>
    <td>
	    <i class="fa fa-spinner fa-spin"></i>
        <a href="<?php echo $this->baseUrl .'/log/view-log-id/jobid/'. $this->escape($line['id']). '/jobname/' . $this->escape($line['name']); ?>" title="<?php echo $this->translate->_("The Job is Running"); ?>">
            &nbsp;<?php echo $this->escape($line['id']);?>
        </a>
    </td>
    <td><?php echo $this->escape($line['level']);?></td>
    
    <!-- Job Name -->
    <td> <?php echo $this->escape($line['name']);?> </td>
    
    <td><?php echo $this->escape($line['status']);?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
</div><!-- end div table-responsive -->

<?php
}
?>

<?php else : ?>
<!--
<div class="ui-widget" style="float: left;">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("Information from Director : No Running Jobs found."); ?></strong></p>
	</div>
</div>
-->

<div class="alert alert-warning">
  <p>
  <span class="glyphicon glyphicon-info-sign"></span>
  <?php print $this->translate->_("Information from Director : No Running Jobs found."); ?>
  </p>
</div>

<!--<div style="clear: both;"></div> -->
<?php endif; ?>



<!--<div style="margin-top: 1.5em;">&nbsp;</div>-->

	   </p><!-- close p -->
    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->

<div class="panel panel-default panel-success">
	<div class="panel-heading">
	   <?php echo $this->escape($this->titleRunningJobs); ?>
	</div>
	<div class="panel-body">
	   <p>


<?php if ( $this->resultRunningJobs ): ?>

<div class="table-responsive">
<table id="box-table2" class="table table-striped table-hover table-condensed">
<!--<caption><?php echo $this->escape($this->titleRunningJobs); ?></caption>-->
<thead>
<tr>
	 <th scope="col"> <?php print $this->translate->_("Job Id"); 	 ?> </th>
     <th scope="col"> 
     <?php 
        switch ($this->show_job_description) {
            case 0 :
                echo $this->translate->_("Job Name"); 
                break;
            case 1 :
                echo $this->translate->_("Short Job Description"); 
                break;
            case 2 :
                echo $this->translate->_("Job Name"), ' /<br>',
                     $this->translate->_("Short Job Description"); 
                break;
            default :
                echo $this->translate->_("Job Name"); 
                break;
        }
     ?> </th>
     <th align="center"> <?php print $this->translate->_("Status"); 	 ?> </th>
     <th align="center"> <?php print $this->translate->_("Level");    ?> </th>
     <th align="center"> <?php print $this->translate->_("Errors"); ?> </th>
     <th align="center"> <?php print $this->translate->_("Client");   ?> </th>
     <th align="center"> <?php print $this->translate->_("Pool"); 	 ?> </th>
     <th align="center"> <?php print $this->translate->_("Start Time"); ?></th>
     <th align="center"> <?php print $this->translate->_("Duration"); ?> </th>
     <th align="center">&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach($this->resultRunningJobs as $line) : ?>
<tr>
    <td>
	    <i class="fa fa-spinner fa-spin"></i>
        <a href="<?php echo $this->baseUrl .'/log/view-log-id/jobid/'. $this->escape($line['jobid']). '/jobname/' . $this->escape($line['jobname']); ?>" title="<?php echo $this->translate->_("The Job is Running"); ?>">
            &nbsp;<?php echo $this->escape($line['jobid']);?>
        </a>
    </td>
    
    <!-- Job Name -->
    <td>
        <?php  
        switch ($this->show_job_description) {
            case 0 :
                // only show Bacula Job Name (behavior as in earlier versions)
                echo $this->escape($line['jobname']);
                break;
            case 1 :
                // only show human readable short Job description instead of Bacula Job Name
                if ( empty($line['short_desc']) ) 
                    echo '<i>', $this->escape($line['jobname']), '</i>';
                else 
                    echo $this->escape($line['short_desc']);
                break;
            case 2 :
                // both
                echo $this->escape($line['jobname']);
                if ( !empty($line['short_desc']) ) 
                    echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                break;
            default :
                echo $this->escape($line['jobname']);
                break;
        }
        ?>
    </td>

    <?php
        if ( $this->escape($line['joberrors']) != 0 )	{
            echo '<td class="err" align="center"> ',
                 $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
        }
        else
            echo '<td align="center">',
                 $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
    ?>

    <td align="center"><?php echo $this->escape($line['level']);?></td>

	<?php
		if ( $this->escape($line['joberrors']) == 0 )
			echo '<td align="center">-</td>';
		else
			echo '<td class="err" align="center">', $this->escape($line['joberrors']), '</td>';
	?>

	<td ><?php echo $this->escape($line['clientname']);?></td>

	<td><a href="<?php echo $this->baseUrl, "/volume/find-pool-id/id/", $this->escape($line['poolid']),
		"/name/", $this->escape($line['poolname']);?>" title="<?php print $this->translate->_("Detail Pool"); ?>">
		<?php echo $this->escape($line['poolname']);?></a>
	</td>

	<td><?php echo $this->escape(date($this->datetime_format,strtotime($line['starttime'])));?></td>
	<td align="right"><?php echo $this->escape($line['durationtime']);?></td>

    <!-- cancel jobid -->
    <td style="padding: 0px; width:16px;"><?php
        echo '<a href="';
        echo $this->baseUrl, '/job/cancel-job/jobid/', $this->escape($line['jobid']);
        echo '" title="', $this->translate->_("Cancel"), '">';
        echo '<img src="', $this->baseUrl, '/images/process-stop.png" alt="', $this->translate->_("Cancel"), '" border="0" hspace="1">';
        echo '</a>';
    ?>
    </td>

</tr>
<?php endforeach; ?>
</tbody>
</table>
</div><!-- end div table-responsive -->

<?php else: ?>
<!--
<div class="ui-widget" style="float: left;">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("Information from DB Catalog : No Running Jobs found.");?></strong></p>
	</div>
</div>
-->

<div class="alert alert-warning">
  <p>
  <span class="glyphicon glyphicon-info-sign"></span>
  <?php print $this->translate->_("Information from DB Catalog : No Running Jobs found."); ?>
  </p>
</div>

<!--<div style="clear: both;"></div>-->
<?php endif; ?>

	   </p><!-- close p -->
    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->

</div><!-- fim div col-md-8 -->
</div><!-- fim da div row -->
