<!-- job/terminated-dashboard.phtml -->
<div class="panel panel-default panel-primary">
   <div class="panel-heading">
      <a href="<?php echo $this->baseUrl;?>/job/terminated" id="dashboard"><?php echo $this->escape($this->title); ?></a>
   </div>
   <div class="panel-body">
      <p>
         
         <?php if ($this->result): ?>
         <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed">
               <thead>
                  <tr>
                     <th>&nbsp;</th>
                     <th>&nbsp;</th>
                     <th><?php print $this->translate->_("Job Id"); ?></th>
                     <th>
                     <?php 
                        switch ($this->show_job_description) {
                            case 0 :
                                echo $this->translate->_("Job Name"); 
                                break;
                            case 1 :
                                echo $this->translate->_("Short Job Description"); 
                                break;
                            case 2 :
                                echo $this->translate->_("Job Name"), ' /<br>',
                                     $this->translate->_("Short Job Description"); 
                                break;
                            default :
                                echo $this->translate->_("Job Name"); 
                                break;
                        }
                     ?> 
                     </th>
                     <th class="text-center"> <?php print $this->translate->_("Status"); ?></th>
                     <th class="text-center"> <?php print $this->translate->_("Level"); ?></th>
                     <th class="text-right"> <?php print $this->translate->_("Files"); ?></th>
                     <th class="text-right"> <?php print $this->translate->_("Bytes"); ?></th>
                     <th class="text-center"> <?php print $this->translate->_("Errors"); ?></th>
                  </tr>
               </thead>
               <tbody>
               <?php foreach($this->result as $line) : ?>
                  <tr>
                     <td>
                        <?php
                           if ( isset($line['poolid'], $line['poolname']) )   {
                              echo '<a href="';
                              echo $this->baseUrl, '/restorejob/main-form/jobid/', $this->escape($line['jobid']);
                              echo '" title="', $this->translate->_("Restore Job"), '">';
                              echo '<img src="', $this->baseUrl, '/images/restore-small.png" alt="', $this->translate->_("Restore Job"), '" border="0" hspace="2">';
                              echo '</a>';
                           }
                        ?>
                     </td>
                     <td>
                        <?php
                           if ( isset($line['jobname']) && ($line['type'] != 'R') )    {
                              // re-run button
                              echo '<a href="';
                              echo $this->baseUrl, '/job/run-job/jobname/', $this->escape($line['jobname']);
                              echo '" title="', $this->translate->_("Re-run Job"), '">';
                              echo '<img src="', $this->baseUrl, '/images/re-run-job-small.png" alt="', $this->translate->_("Re-run Job"), '" border="0" hspace="2">';
                              echo '</a>';
                           }
                        ?>
                     </td>
                     <td>
                        <a href="<?php echo $this->baseUrl, '/job/detail/jobid/', $this->escape($line['jobid']); ?>"
                           title="<?php echo $this->translate->_("Detail Job"); ?>">
                           <?php echo $line['jobid']; ?>
                        </a>
                     </td>
                  
                     <!-- Job.Name -->
                     <td>
                     <?php  
                        switch ($this->show_job_description) {
                           case 0 :
                               // only show Bacula Job Name (behavior as in earlier versions)
                               echo $this->escape($line['jobname']);
                               break;
                           case 1 :
                               // only show human readable short Job description instead of Bacula Job Name
                               if ( empty($line['short_desc']) ) 
                                   echo '<i>', $this->escape($line['jobname']), '</i>';
                               else 
                                   echo $this->escape($line['short_desc']);
                               break;
                           case 2 :
                               // both
                               echo $this->escape($line['jobname']);
                               if ( !empty($line['short_desc']) ) 
                                   echo '<br><i>', $this->escape($line['short_desc']), '</i>'; 
                               break;
                           default :
                               echo $this->escape($line['jobname']);
                               break;
                        }
                     ?>
                     </td>
                  
                     <!-- Status -->
                     <?php
                        $class_td = 'class="text-center"';
                        if ( $line['joberrors'] != 0 )   {
                            if ( $line['jobstatus'] == 'T' )   {
                                $class_td = 'class="text-center warning"';
                            } else {
                                // 100% That there was some mistake
                                $class_td = 'class="text-center danger"';
                            }
                           echo '<td ', $class_td, '> ',
                                $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
                        }
                        elseif   ( $line['jobstatus'] == 'T' ) {
                           echo '<td class="text-center">OK</td>';
                        } else {
                            // Errors like no, but something is wrong
                            if ( ($line['jobstatus'] == 'f') OR ($line['jobstatus'] == 'E') )   {
                                // fatal error
                                  $class_td = 'class="text-center danger"';
                            } else {
                                $class_td = 'class="text-center warning"';
                            }
                           echo '<td ', $class_td, '">',
                                $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
                        }
                     ?>
                  
                     <td class="text-center"><?php echo $this->escape($line['level']);?></td>
                  
                     <?php
                        if ( ($line['jobfiles'] == 0) && ($line['type'] != 'D') ) {
                           $class = 'class="text-right warning"';
                        } else {
                           $class = 'class="text-right"';
                        }
                        echo '<td ', $class, '>', number_format($line['jobfiles']), '</td>';
                     ?>
                  
                     <?php
                        if ( ($line['jobbytes'] == 0) && ($line['type'] != 'D') ) {
                           $class = 'class="text-right warning"';
                        } else {
                           $class = 'class="text-right"';
                        }
                        echo '<td ', $class, '>', $this->convBytes($line['jobbytes']), '</td>';
                     ?>
                  
                     <!-- Errors -->
                     <?php
                      if ( $line['joberrors'] == 0 )
                          echo '<td class="text-center">-</td>';
                      else  {
                          if ( $line['reviewed'] > 0 )  {
                              // reviewed icon
                              echo '<td class="text-center">';
                              echo '<img src="', $this->baseUrl, '/images/dialog-ok-apply-small.png" align="absmiddle" ',
                                  ' alt="', $this->translate->_("Bacula Job Reviewed"),'"',
                                  ' title="', $this->translate->_("Bacula Job Reviewed"),'"',
                                  ' border="0" hspace="4">';
                          } else
                              echo '<td class="text-center danger">';
                          echo '<a href="',
                              $this->baseUrl, '/log/view-log-id/jobid/', $this->escape($line['jobid']), '" title="',
                              $this->translate->_("View Messages"), '"';
                          if ( $line['reviewed'] == 0 )
                              echo ' class="text-center danger" ';
                          echo '>', $this->escape($line['joberrors']), '</a></td>';
                      }
                     ?>
                  </tr>
               <?php endforeach; ?>
               </tbody>
            </table>
         </div><!-- end div table-responsive -->
         
         <?php else: ?>
         
         <!-- div alert -->
         <div class="alert alert-danger">
           <p>
           <span class="glyphicon glyphicon-info-sign"></span>
           <?php print $this->translate->_("No Jobs found.");; ?>
           </p>
         </div>
         <!-- end div alert -->
         
         <?php endif; ?>
         
      </p><!-- close p -->
   </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->
<!-- job/terminated-dashboard.phtml -->