<!-- job/terminated.phtml -->
<div class="rows">
   <div class="col-md-12">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
         <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               <?php if ( $this->result ): ?>
                      
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                     <tr>
                          <th scope="col">&nbsp;</th>
                          <th scope="col">&nbsp;</th>
                          <th scope="col"> <?php print $this->translate->_("Job Id"); ?> </th>
                          <th scope="col"> 
                          <?php 
                             switch ($this->show_job_description) {
                                 case 0 :
                                     echo $this->translate->_("Job Name"); 
                                     break;
                                 case 1 :
                                     echo $this->translate->_("Short Job Description"); 
                                     break;
                                 case 2 :
                                     echo $this->translate->_("Job Name"), ' /<br>',
                                          $this->translate->_("Short Job Description"); 
                                     break;
                                 default :
                                     echo $this->translate->_("Job Name"); 
                                     break;
                             }
                          ?> 
                          </th>
                          <th class="text-center"> <?php print $this->translate->_("Status"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("Level"); ?> </th>
                          <th class="text-right"> <?php print $this->translate->_("Files"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("Bytes Stored"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("Bytes Copied"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("Software Compression"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("Errors"); ?> </th>
                          <th> <?php print $this->translate->_("Client"); ?> </th>
                          <th> <?php print $this->translate->_("Pool"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("Start Time"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("End Time"); ?> </th>
                          <th class="text-center"> <?php print $this->translate->_("Duration"); ?> <br /> </th>
                          <th class="text-center">&nbsp;</th>
                     </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->result as $line) : ?>
                        <tr>
                           <td>
                              <?php
                                 if ( isset($line['poolid'], $line['poolname']) )    {
                                    // restore button
                                    echo '<a href="';
                                    echo $this->baseUrl, '/restorejob/main-form/jobid/', $this->escape($line['jobid']);
                                    echo '" title="', $this->translate->_("Restore Job"), '">';
                                    echo '<img src="', $this->baseUrl, '/images/restore.png" alt="', $this->translate->_("Restore Job"), '" border="0" hspace="2">';
                                    echo '</a>';
                                 }
                              ?>
                           </td>
                           <td>
                              <?php
                                 if ( isset($line['jobname']) && ($line['type'] != 'R') )    {
                                    // re-run button
                                    echo '<a href="';
                                    echo $this->baseUrl, '/job/run-job/jobname/', $this->escape($line['jobname']);
                                    echo '" title="', $this->translate->_("Re-run Job"), '">';
                                    echo '<img src="', $this->baseUrl, '/images/re-run-job.png" alt="', $this->translate->_("Re-run Job"), '" border="0" hspace="2">';
                                    echo '</a>';
                                 }
                              ?>
                           </td>
                           <td>
                              <a href="<?php echo $this->baseUrl, '/job/detail/jobid/', $this->escape($line['jobid']); ?>"
                                 title="<?php echo $this->translate->_("Detail Job"); ?>">
                                 <?php echo $line['jobid']; ?>
                              </a>
                           </td>
                        
                            <!-- Job.Name -->
                           <td>
                              <?php  
                              switch ($this->show_job_description) {
                                  case 0 :
                                      // only show Bacula Job Name (behavior as in earlier versions)
                                      echo $this->escape($line['jobname']);
                                      break;
                                  case 1 :
                                      // only show human readable short Job description instead of Bacula Job Name
                                      if ( empty($line['short_desc']) ) 
                                          echo '<i>', $this->escape($line['jobname']), '</i>';
                                      else 
                                          echo $this->escape($line['short_desc']);
                                      break;
                                  case 2 :
                                      // both
                                      echo $this->escape($line['jobname']);
                                      if ( !empty($line['short_desc']) ) 
                                          echo '<br/><i>', $this->escape($line['short_desc']), '</i>';
                                      break;
                                  default :
                                      echo $this->escape($line['jobname']);
                                      break;
                              }
                              ?>
                           </td>
                        
                           <!-- Status -->
                           <?php
                              $class_td = 'class="text-center"';
                              if ( $line['joberrors'] != 0 )   {
                                  if ( $line['jobstatus'] == 'T' )   {
                                      $class_td = 'class="text-center warning"';
                                  } else {
                                      // 100% That there was some mistake
                                      $class_td = 'class="text-center danger"';
                                  }
                                 echo '<td ', $class_td, '> ',
                                      $this->translate->_( $this->escape($line['jobstatuslong']) ), ' </td>';
                              }
                              elseif   ( $line['jobstatus'] == 'T' ) {
                                 echo '<td class="text-center">OK</td>';
                              } else {
                                  // Errors like no, but something is wrong
                                  if ( ($line['jobstatus'] == 'f') OR ($line['jobstatus'] == 'E') )   {
                                      // fatal error
                                        $class_td = 'class="text-center danger"';
                                  } else {
                                      $class_td = 'class="text-center warning"';
                                  }
                                 echo '<td ', $class_td, '>',
                                      $this->translate->_( $this->escape($line['jobstatuslong']) ), '</td>';
                              }
                           ?>
                        
                           <td class="text-center"><?php echo $this->escape($line['level']);?></td>
                        
                           <?php
                              if ( ($line['jobfiles'] == 0) && ($line['type'] != 'D') ) {
                                 $class = 'class="text-right warning"';
                              } else {
                                 $class = 'class="text-right"';
                              }
                              echo '<td ', $class, '>', number_format($line['jobfiles']), '</td>';
                           ?>
                        
                           <?php
                              if ( ($line['jobbytes'] == 0) && ($line['type'] != 'B') ) {
                                 $class = 'class="text-right warning"';
                              } else {
                                 $class = 'class="text-right"';
                              }
                              echo '<td ', $class, '>', $this->convBytes($line['jobbytes']), '</td>';
                           ?>

                           <?php
                              if ( ($line['filesize'] == 0) && ($line['type'] != 'B') ) {
                                 $class = 'class="text-right warning"';
                              } else {
                                 $class = 'class="text-right"';
                              }
                              echo '<td ', $class, '>', $this->convBytes($line['filesize']), '</td>';
                           ?>

                           <?php
                              $jobbytes=$line['jobbytes'];
                              $filesize=$line['filesize'];
                              if (( $jobbytes != 0) && ($filesize != 0) ){
                                 $filesize == 0 ? 1 : $filesize;
                                 $class = '';
                                 echo '<td class="text-center">', $this->escape( number_format((1-($jobbytes/$filesize))*100,2) ), ' %</td>';
                               } else {
                                  echo '<td class="text-center">-</td>';
                               }
                           ?>
                           <!-- Errors -->
                           <?php
                               if ( $line['joberrors'] == 0 )
                                   echo '<td class="text-center">-</td>';
                               else {
                                   if ( $line['reviewed'] > 0 )  {
                                       // reviewed icon
                                       echo '<td class="text-center">';
                                       echo '<img src="', $this->baseUrl, '/images/dialog-ok-apply.png" align="absmiddle" ',
                                           ' alt="', $this->translate->_("Bacula Job Reviewed"),'"',
                                           ' title="', $this->translate->_("Bacula Job Reviewed"),'"',
                                           ' border="0" hspace="4">';
                                   } else
                                       echo '<td class="text-center danger">';
                                   echo '<a href="',
                                       $this->baseUrl, '/log/view-log-id/jobid/', $this->escape($line['jobid']), '" title="',
                                       $this->translate->_("View Messages"), '"';
                                   if ( $line['reviewed'] == 0 )
                                       echo ' class="text-center danger" ';
                                   echo '>', $this->escape($line['joberrors']), '</a></td>';
                               }
                           ?>
                        
                           <td><?php echo $line['clientname'];?></td>
                           <td>
                              <?php
                                 if ( isset($line['poolid']) && isset($line['poolname']) )   {
                                    echo '<a href="';
                                    echo $this->baseUrl, "/volume/find-pool-id/id/", $this->escape($line['poolid']),
                                    "/name/", $this->escape($line['poolname']);
                                    echo '" title="', $this->translate->_("Detail Pool"), '">';
                                 }  else  {
                                    echo "&nbsp;";
                                 }
                        
                                 if ( isset($line['poolid']) && isset($line['poolname']) )   {
                                    echo $this->escape($line['poolname']);
                                    echo '</a>';
                                 }  else {
                                    echo '&nbsp;';
                                 }
                              ?>
                           </td>
                           <td class="text-center"><?php echo $this->escape(date($this->datetime_format, strtotime($line['starttime'])));?></td>
                           <td class="text-center"><?php echo $this->escape(date($this->datetime_format, strtotime($line['endtime'])));?></td>
                           <td class="text-center">&nbsp;<?php echo $this->escape($line['durationtime']);?></td>

                           <!-- add to logbook button -->
                           <td><?php
                              if ( isset($line['poolid'], $line['poolname']) )    {
                                   echo '<a href="';
                                   echo $this->baseUrl, '/wblogbook/writelogbook/name_job/', $this->escape($line['jobname']),
                                       '/endtime/', $this->escape($line['endtime']),
                                       '/jobid/', $this->escape($line['jobid']),
                                       '/joberrors/', $this->escape($line['joberrors']);
                                   echo '" title="', $this->translate->_("Written in Logbook"), '">';
                                   echo '<img src="', $this->baseUrl, '/images/bookmark-new.png" alt="', $this->translate->_("Written in Logbook"), '" border="0" hspace="2">';
                                   echo '</a>';
                              }
                              ?>
                           </td>
                        
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
               
               <?php else: ?>

               <!-- div alert -->
               <div class="alert alert-warning">
                  <p>
                  <span class="glyphicon glyphicon-info-sign"></span>
                  <?php print $this->translate->_("No Jobs found.");; ?>
                  </p>
                  <p><a href="<?php echo $this->baseUrl, '/job/list-last-jobs-run/numjob/20'; ?>">
                  <?php print $this->translate->_("See List last 20 Jobs run"); ?>
                  </a>
                  </p>
               </div>
               <!-- end div alert -->
               
               <?php endif; ?>
            </p><!-- close p -->
         </div><!-- close div panel-body -->
      </div><!-- close div panel panel-default -->
   </div><!-- end div col-md-10 -->
</div><!-- end da div rows -->
<!-- job/terminated.phtml -->
