<style type="text/css">@import url("<?php echo $this->baseUrl; ?>/styles/default/jquery-ui-1.7.2.custom.css");</style>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-ui-1.7.2.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl , '/scripts/jquery-ui.datepicker-', $this->language, '.js';?>"></script>

<script type="text/javascript">
$j(function() {
	$j('#datetimeline').datepicker({
			changeMonth: true,
			changeYear: true
	});
	$j('#datetimeline').datepicker('setDate', '-1d' );
	$j('#datetimeline').datepicker('option', {dateFormat: $j.datepicker.ISO_8601} );
});
</script>

<h1 align="center"><?php echo $this->escape($this->title); ?></h1>
<div align="center">

<!--  date form -->
<form action="<?php echo $this->baseUrl; ?>/job/timeline" method="POST">
<table cellspacing="0" cellpadding="10" border="0" align="center">
<tr>
	<td align="right" valign="top">
		<b><?php print $this->translate->_("Date"); ?></b> :
	</td>
	<td>
<?php echo $this->formText('datetimeline', date('Y-m-d', time()-86400), array('size' => 12)) ?>
<br><div style="font-size:70%;"><?php print $this->translate->_("YYYY-MM-DD"); ?></div>
	</td>
	<td valign="top">
	<INPUT type="submit" name="ok" value="<?php print $this->translate->_("Show Timeline"); ?>">
	</td>
</tr>
</tr>
</table>
</form>

<?php
// check GD lib (php-gd)
if ( extension_loaded('gd') ) {
	if ( $this->result )	{
		// show image
		echo '<img src="', $this->baseUrl, '/chart/timeline/datetimeline/', $this->result, '"  alt="', $this->escape($this->title), '" />';
	} else	{
	    // не прошел валидацию; вывод причин этого
        foreach ($this->err_msg as $message) {
                echo "<b>$message</b><br />";
        }
		echo $this->translate->_('No Jobs found.');
	}
}	else {
	echo $this->translate->_('ERROR: The GD extension isn`t loaded. Please install php-gd package.');
}
?>

<?php // draw table
if ($this->atime) : ?>
	<div align="center">
	<table id="box-table">
	<thead>
		<tr>
			<th scope="col"> <?php print $this->translate->_("Job Id"); ?> </th>
			<th scope="col"> <?php print $this->translate->_("Job Name"); ?> </th>
			<th scope="col"> <?php print $this->translate->_("Start Time"); ?> </th>
			<th scope="col"> <?php print $this->translate->_("End Time"); ?> </th>
		</tr>
	</thead>
	<?php foreach($this->atime as $line) : ?>
		<tr>
			<td>
				<a href="<?php echo $this->baseUrl, '/job/detail/jobid/', $line['jobid'];?>" title="<?php print $this->translate->_("Detail Job"); ?>"><?php echo $line['jobid']?></a>
			</td>
			<td><?php echo $line['name'];?></td>
			<td><?php echo $line['start'];?></td>
			<td><?php echo $line['end'];?></td>
		</tr>
	<?php endforeach; ?>

		</tr>
	</table>
	</div>
<?php else : ?>
<div class="ui-widget" style="width: 40%; margin-left: auto; margin-right: auto;">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("No Jobs found."); ?></strong></p>
	</div>
</div>
<?php endif; ?>

</div>