<!-- job/timeline-dashboard.phtml -->
<?php
// check GD lib (php-gd)
if ( extension_loaded('gd') ) : ?>

<h1 class="dashboard">
    <a href="<?php echo $this->baseUrl;?>/job/timeline" id="dashboard">
        <?php echo $this->escape($this->title); ?>
    </a>
</h1>

<?php if ( $this->img_map ) : ?>
<div align="center">
<map name="map1">
    <?php
        $count = count($this->img_map);
        for ($i = 0; $i < $count; $i++) :
    ?>
<area
   href="<?php echo $this->baseUrl, '/job/detail/jobid/', $this->img_map[$i]['jobid'];?>"
   alt="<?php echo $this->translate->_("Detail Job"), ' : ', $this->img_map[$i]['name'], ' (', $this->img_map[$i]['jobid'], ')'; ?>"
   title="<?php echo $this->translate->_("Detail Job"), ' : ', $this->img_map[$i]['name'], ' (', $this->img_map[$i]['jobid'], ')'; ?>"
   shape=rect coords="<?php echo $this->img_map[$i]['x1'], ',', $this->img_map[$i]['y1'], ',',
        $this->img_map[$i]['x2'], ',', $this->img_map[$i]['y2'];?>">
    <?php endfor; ?>
</map>
    <?php
        echo '<img src="', $this->baseUrl, '/chart/timeline-dashboard"  alt="', $this->escape($this->title), '" usemap="#map1" border="0" />';
    ?>
</div>
<?php endif; ?>

<?php endif; ?>