<!-- volume/detail.phtml -->

<script type="text/javascript">
$(document).ready(function() {
    $('#ok').click(function() {
        $.blockUI({
            message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
            css: { backgroundColor: '#f3fcf2' },
            centerX: true,
            centerY: true
        });
    });
});
</script>

<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               
               <?php
               // Volume Status
               $astatus = array(
                   "Append"    => $this->translate->_("Append"),
                   "Full"      => $this->translate->_("Full"),
                   "Recycle"   => $this->translate->_("Recycle"),
                   "Purged"    => $this->translate->_("Purged"),
                   "Read-Only" => $this->translate->_("Read-Only"),
                   "Disabled"  => $this->translate->_("Disabled"),
                   "Error"     => $this->translate->_("Error"),
                   "Busy"      => $this->translate->_("Busy"),
                   "Used"      => $this->translate->_("Used"),
                   "Cleaning"  => $this->translate->_("Cleaning"),
                   "Archive"   => $this->translate->_("Archive")
               );
               // Pools
               foreach($this->pools as $pool) {
                   $apool[ $this->escape($pool['poolid']) ] = $this->escape($pool['name']);
               }
               // Recycle Flag
               $arecycle = array(
                   '0' => $this->translate->_("no"),
                   '1' => $this->translate->_("yes")
               );
               // InChanger Flag
               $ainchanger = array(
                   '0' => $this->translate->_("no"),
                   '1' => $this->translate->_("yes")
               );
               ?>
               
               <?php if ($this->result): ?>
               
               <form action="<?php  echo $this->baseUrl.'/volume/update/';?>" method="post">
               
               <!-- column 1 -->
               <div class="col-md-6">
                  <table class="table table-striped table-hover table-condensed">
                     <thead></thead>
                     <tbody>
                        <?php foreach($this->result as $line) : ?>
                        <?php echo $this->formHidden('mediaid', $this->escape($line['mediaid']), null); ?>
                        <?php echo $this->formHidden('volumename', $this->escape($line['volumename']), null); ?>
                        <tr>
                           <td> <?php print $this->translate->_("Media Id"); ?> </td>
                           <td><?php echo $this->escape($line['mediaid']);?></td>
                        </tr>
                        <tr>
                           <td><b><?php print $this->translate->_("Volume Name"); ?></b></td>
                           <td><?php echo $this->escape($line['volumename']);?></td>
                        </tr>
                        <tr>
                           <td><b><?php print $this->translate->_("Pool"); ?></b></td>
                           <td><?php echo $this->formSelect('poolid', $this->escape($line['poolid']), null, $apool); ?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Status"); ?></td>
                           <td><?php echo $this->formSelect('volstatus', $this->escape($line['volstatus']), null, $astatus); ?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Bytes"); ?> </td>
                           <td><?php echo $this->ConvBytes( $this->escape($line['volbytes']) );?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Max Bytes"); ?> </td>
                           <td><?php echo $this->ConvBytes( $this->escape($line['maxvolbytes']) );?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Jobs"); ?> </td>
                           <td><?php echo '<a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                                     'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                                     number_format($this->escape($line['voljobs'])), '</a>'; ?>
                           </td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate->_("Retention")," (",$this->translate->_("days"), ")"; ?> </td>
                            <td>
                            <?php echo $this->formText('volretention', $this->ConvSecondsToDays( $this->escape($line['volretention']) ),
                                array('size' => 5)) ?>
                            </td>
                        </tr>
                        <tr>
                           <td><?php echo $this->translate->_("Use Duration")," (",$this->translate->_("seconds"), ")"; ?> </td>
                           <td>
                           <?php echo $this->formText('voluseduration', $this->escape($line['voluseduration'] ),
                               array('size' => 10)) ?>
                           </td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Recycle "); ?> </td>
                           <td><?php echo $this->formSelect('recycle', $this->escape($line['recycle']), null, $arecycle); ?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Autochanger<br />Slot<br />Number"); ?> </td>
                           <td><?php echo $this->formText('slot', $this->escape($line['slot']), array('size' => 5)) ?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("In Changer"); ?> </td>
                           <td><?php echo $this->formSelect('inchanger', $this->escape($line['inchanger']), null, $ainchanger); ?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Media Type"); ?> </td>
                           <td><?php echo $this->escape($line['mediatype']);?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("First Written"); ?> </td>
                           <td><?php echo $this->escape(date($this->datetime_format, strtotime($line['firstwritten'])));?></td>
                        </tr>
                        <tr>
                           <td><?php print $this->translate->_("Last Written"); ?> </td>
                           <td><?php echo $this->escape(date($this->datetime_format, strtotime($line['lastwritten'])));?></td>
                        </tr>
                     <tbody>
                  </table>
               </div><!-- end div col-mds-6 -->
               <!-- end column 1 -->
               
               <!-- column 2 -->
               <div class="col-md-6">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                     </thead>
                     <tbody>
                     <tr>
                        <td><?php print $this->translate->_("Label Date"); ?> </td>
                        <td><?php echo $this->escape(date($this->datetime_format, strtotime($line['labeldate'])));?></td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Files"); ?> </td>
                        <td><?php echo $this->escape($line['volfiles']);?></td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Blocks"); ?> </td>
                        <td><?php echo $this->escape($line['volblocks']);?></td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Mounts"); ?> </td>
                        <td><?php echo $this->escape($line['volmounts']);?></td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Errors"); ?> </td>
                        <?php
                            if ( $this->escape($line['volerrors']) == 0 )
                                echo '<td></td>';
                            else
                                echo '<td class="err">' . $this->escape($line['volerrors']) . '</td>';
                        ?>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Number of writes"); ?> </td>
                        <td><?php echo $this->escape($line['volwrites']);?></td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Enabled"); ?> </td>
                        <?php
                            if ( $this->escape($line['enabled']) == 0 )
                                echo '<td class="err">'.$this->translate->_("no").'</td>';
                            else
                                echo '<td>'.$this->translate->_("yes").'</td>';
                        ?>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Max Volume Jobs"); ?> </td>
                        <td><?php echo $this->formText('maxvoljobs', $this->escape($line['maxvoljobs']), array('size' => 9)) ?> </td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Max Volume Files"); ?> </td>
                        <td><?php echo $this->formText('maxvolfiles', $this->escape($line['maxvolfiles']), array('size' => 9)) ?> </td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Read Time"); ?> </td>
                        <td><?php
                                if ( $this->escape($line['volreadtime']) != 0) {
                                    echo $this->escape($line['volreadtime']);
                                } else {
                                    echo '&nbsp;';
                                }
                            ?>
                        </td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Write Time"); ?> </td>
                        <td><?php
                                if ( $this->escape($line['volwritetime']) != 0) {
                                    echo $this->escape($line['volwritetime']);
                                } else {
                                    echo '&nbsp;';
                                }
                            ?>
                        </td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Recycle Count"); ?> </td>
                        <td><?php echo $this->escape($line['recyclecount']);?></td>
                     </tr>
                     <tr>
                        <td><?php print $this->translate->_("Comment"); ?> </td>
                        <td><?php echo $this->formTextarea('comment', $this->escape($line['comment']), array('cols' => "25", 'rows' => "2")); ?></td>
                     </tr>
                     <?php endforeach; ?>
                     <tbody>
                  </table>
               </div><!-- end div col-mds-6 -->
               <!-- end column 2 -->
               
               <div class="col-md-6">
                 <?php echo $this->formSubmit('ok', $this->translate->_('Submit Form'), array('class' => 'btn btn-default')); ?>
                 &nbsp;&nbsp;&nbsp;&nbsp;
                 <?php echo $this->formReset('reset', $this->translate->_('Reset Form'), array('class' => 'btn btn-default')); ?>
               </div>
               </form>
               
               <?php else: ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon-alert"></span>
                 <?php print $this->translate->_("No Volumes found."); ?>
                 </p>
               </div>
               <!-- end div alert -->
                  
               <?php endif; ?>
               
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div rows -->
