<!-- volume/find-pool-id.phtml -->
<div class="rows">
   <div class="col-md-8">   
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
         <?php $urlp = $this->baseUrl . "/pool/show/name/" . $this->escape($this->pool_name); ?>
         <?php echo $this->escape($this->title) . ": <a href='".$urlp."'>".$this->escape($this->pool_name)."</a>"; ?>
         </div>
         <div class="panel-body">
            <p>
               <?php $urlp = $this->baseUrl . "/volume/find-pool-id/id/" . $this->escape($this->pool_id) . "/name/" . $this->escape($this->pool_name); ?>
               <?php if ($this->result): ?>
              
                  <div class="table-responsive">
                     <table class="table table-striped table-hover table-condensed">
                        <thead>
                        <tr>
                           <th><a href="<?php echo $urlp;?>/order/VolumeName"><?php echo $this->translate->_("Volume Name"); ?> </a></th>
                           <th class="text-center"><a href="<?php echo $urlp;?>/order/VolStatus"><?php echo $this->translate->_("Volume Status"); ?> </a></th>
                           <th class="text-center"><a href="<?php echo $urlp;?>/order/VolBytes"><?php echo $this->translate->_("Volume Bytes"); ?> </a></th>
                           <th class="text-center"><a href="<?php echo $urlp;?>/order/MaxVolBytes"><?php echo $this->translate->_("Max Volume<br />Bytes"); ?> </a></th>
                           <th class="text-center"><a href="<?php echo $urlp;?>/order/VolJobs"><?php echo $this->translate->_("Volume Jobs"); ?> </a></th>
                           <th class="text-center"><a href="<?php echo $urlp;?>/order/VolRetention"><?php echo $this->translate->_("Volume<br />Retention<br />(days)"); ?></a></th>
                           <th class="text-center"><a href="<?php echo $urlp;?>/order/MediaType"><?php echo $this->translate->_("Media<br />Type"); ?></a></th>
                           <th class="text-center"><a href="<?php echo $urlp;?>/order/LastWritten"><?php echo $this->translate->_("Last<br />Written"); ?></a></th>
                           <th class="text-center"><?php print $this->translate->_("Autochanger<br />Slot<br />Number"); ?></th>
                           <th class="text-center"><?php print $this->translate->_("Can Recycle<br />Volume"); ?></th>
                           <th class="text-center"><?php echo $this->translate->_("Expires In"); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                           <?php foreach($this->result as $line) : ?>
                           <tr>
                              <td>
                                 <a href="<?php echo $this->baseUrl, '/volume/detail/mediaid/'.$this->escape($line['mediaid']); ?>
                                      " title="<?php echo $this->translate->_("Detail Volume");?>">
                                    <?php echo $this->escape($line['volumename']);?>
                                 </a>
                              </td>
                           
                              <?php
                                 // http://www.bacula.org/developers/Catalog_Services.html
                                 // Status of media: Full, Archive, Append, Recycle, Read-Only, Disabled, Error, Busy
                                 if ( $this->escape($line['volstatus']) == 'Disabled' )
                                    echo '<td class="warn" align="center">', $this->escape($line['volstatus']), '</td>';
                                 elseif ( $this->escape($line['volstatus']) == 'Error' )
                                    echo '<td class="err" align="center">', $this->escape($line['volstatus']), '</td>';
                                 else
                                    echo '<td align="center">', $this->escape($line['volstatus']), '</td>';
                              ?>
                           
                              <td align="center"><?php echo $this->ConvBytes($this->escape($line['volbytes']));?></td>
                                   <?php
                                   if ( $line['maxvolbytes'] <= 0 )
                                       echo '<td align="center">'.$this->translate->_('unlimited').'</td>';
                                   else
                                       echo '<td align="center">' . $this->convBytes($this->escape($line['maxvolbytes'])) . "</td>";
                                   ?>
                           
                              <?php
                                 if ( ( isset($line['firstwritten'])) && ($this->escape($line['voljobs']) <= 0) )
                                    echo '<td class="warn" align="center">', number_format($this->escape($line['voljobs'])), '</td>';
                                 else
                                     echo '<td align="center"> <a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                                           'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                                           number_format($this->escape($line['voljobs'])), '</a></td>';
                              ?>
                              <td class="text-center"><?php echo $this->translate->_($this->ConvSecondsToDays($this->escape($line['volretention']))).' '. $this->translate->_("days");?></td>
                              <td class="text-center"><?php echo $this->escape($line['mediatype']);?></td>
                              <td class="text-center"><?php echo $this->escape(date($this->datetime_format, strtotime($line['lastwritten'])));?></td>
                              <td class="text-center"><?php echo $this->escape($line['slot']);?></td>
                              <td class="text-center"><?php echo $this->translate->_($this->Int2Char($this->escape($line['recycle'])));?></td>
                                   <?php
                                     $expiresin = strtotime($line['lastwritten']) + $line['volretention'];
                                     $line['expiresin'] = strftime("%Y-%m-%d %H:%M:%S", $expiresin);
                                   ?>
                              <td class="text-center"><?php echo $this->escape(date($this->date_format, strtotime($line['expiresin'])));?></td>
                           </tr>
                           <?php endforeach; ?>
                        </tbody>
                     </table>
                  </div><!-- end div table-responsive -->
               
               <?php else: ?>

               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                     <span class="glyphicon glyphicon-alert"></span>
                     <?php print $this->translate->_("No Volumes found."); ?>
                  </p>
               </div>
               <!-- end div alert -->
                  
               <?php endif; ?>
               
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div rows -->
<!-- volume/find-pool-id.phtml -->