<!-- volume/find-name.phtml -->
<h1><?php echo $this->escape($this->title); ?></h1>
<?php $urlp = $this->baseUrl . "/volume/find-name/volname/" . $this->escape($this->volname); ?>
<table id="box-table">
<thead>
<tr>
    <th><a href="<?php echo $urlp;?>/order/VolumeName"><?php echo $this->translate->_("Volume Name"); ?></a></th>
    <th align="center"> <a href="<?php echo $urlp;?>/order/VolStatus"><?php echo $this->translate->_("Volume Status"); ?></a></th>
    <th align="center"> <a href="<?php echo $urlp;?>/order/VolBytes"><?php echo $this->translate->_("Volume Bytes"); ?></a></th>
    <th align="center"> <a href="<?php echo $urlp;?>/order/MaxVolBytes"><?php echo $this->translate->_("Max Volume<br />Bytes"); ?></a></th>
    <th align="center"> <a href="<?php echo $urlp;?>/order/VolJobs"><?php echo $this->translate->_("Volume Jobs"); ?></a></th>
    <th align="center"> <a href="<?php echo $urlp;?>/order/VolRetention"><?php echo $this->translate->_("Volume<br />Retention<br />(days)"); ?></a></th>
    <th align="center"> <a href="<?php echo $urlp;?>/order/MediaType"><?php echo $this->translate->_("Media<br />Type"); ?></a></th>
    <th align="center"> <a href="<?php echo $urlp;?>/order/LastWritten"><?php echo $this->translate->_("Last<br />Written"); ?></a></th>
    <th align="center"> <?php print $this->translate->_("Autochanger<br />Slot<br />Number"); ?> </th>
    <th align="center"> <?php print $this->translate->_("Can Recycle<br />Volume"); ?> </th>
    <th align="center"> <?php echo $this->translate->_("Expires In"); ?></th>
</tr>
</thead>
<tbody>
<?php foreach($this->result as $line) : ?>
<tr>
    <td><a href="<?php echo $this->baseUrl, '/volume/detail/mediaid/'.$this->escape($line['mediaid']);?>"
	   title="<?php echo $this->translate->_("Detail Volume");?>"><?php echo $this->escape($line['volumename']);?>
    </a>
    </td>
	<?php
            $aErrorVolStatus = array('Disabled', 'Error');
	        if ( in_array($this->escape($line['volstatus']), $aErrorVolStatus) )
		    echo '<td class="err" align="center">' . $this->escape($line['volstatus']) . '</td>';
		else
		    echo '<td align="center">' . $this->escape($line['volstatus']) . '</td>';
	?>
    <td align="center"><?php echo $this->ConvBytes($this->escape($line['volbytes']));?></td>
    <?php
    if ( $line['maxvolbytes'] <= 0 )
        echo '<td align="right">'.$this->translate->_('unlimited').'</td>';
    else
        echo '<td align="right">' . $this->convBytes($this->escape($line['maxvolbytes'])) . "</td>";
    ?>

	<?php
        if ( $this->escape($line['voljobs']) <= 0 )
            echo '<td class="warn" align="right">' . number_format($this->escape($line['voljobs'])) . '</td>';
        else
            echo '<td align="center"> <a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                number_format($this->escape($line['voljobs'])), '</a></td>';
	?>
    <td align="center"><?php echo $this->translate->_($this->ConvSecondsToDays($this->escape($line['volretention']))).' '. $this->translate->_("days");?></td>
    <td align="center"><?php echo $this->escape($line['mediatype']);?></td>
    <td align="center"><?php echo $this->escape(date($this->datetime_format, strtotime($line['lastwritten'])));?></td>
    <td align="center"><?php echo $this->escape($line['slot']);?></td>
    <td align="center"><?php echo $this->translate->_($this->Int2Char($this->escape($line['recycle'])));?></td>
    <?php
       $expiresin = strtotime($line['lastwritten']) + $line['volretention'];
       $line['expiresin'] = strftime("%Y-%m-%d %H:%M:%S", $expiresin);
    ?>
    <td align="center"><?php echo $this->escape(date($this->date_format, strtotime($line['expiresin'])));?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
