<!-- volume/problem.phtml -->

<!--<h1><?php echo $this->escape($this->titleProblemVolumes); ?></h1>-->

<div class="panel panel-default panel-primary">
	<div class="panel-heading">
	   <?php echo $this->escape($this->titleProblemVolumes); ?>
	</div>
	<div class="panel-body">
	   <p>

<?php if ($this->resultProblemVolumes): ?>
<table id="box-table-dashboard2" class="table table-striped table-hover table-condensed">
<thead>
<tr>
	<th> <?php print $this->translate->_("Volume Name"); ?> </th>
    <th class="text-center"> <?php print $this->translate->_("Volume Status"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Volume Bytes"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Max Volume<br />Bytes"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Volume Jobs"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Volume<br />Retention<br />(days)"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Media<br />Type"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Last<br />Written"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Autochanger<br />Slot<br />Number"); ?> </th>
	<th class="text-center"> <?php print $this->translate->_("Can Recycle<br />Volume"); ?> </th>
    <th class="text-center"> <?php echo $this->translate->_("Expires In"); ?></th>
</tr>
</thead>
<tbody>
<?php foreach($this->resultProblemVolumes as $line) : ?>
<tr>
	<td>
	<a href="<?php echo $this->baseUrl, '/volume/detail/mediaid/'.$this->escape($line['mediaid']); ?> " title="<?php
	   echo $this->translate->_("Detail Volume"); ?>">
	   <?php echo $this->escape($line['volumename']);?>
    </a>
    </td>

	<?php
		// http://www.bacula.org/developers/Catalog_Services.html
		// Status of media: Full, Archive, Append, Recycle, Read-Only, Disabled, Error, Busy
		if ( $this->escape($line['volstatus']) == 'Disabled' )
			echo '<td class="text-center warning">', $this->escape($line['volstatus']), '</td>';
		elseif ( $this->escape($line['volstatus']) == 'Error' )
			echo '<td class="text-center danger">', $this->escape($line['volstatus']), '</td>';
		else
			echo '<td class="text-center">', $this->escape($line['volstatus']), '</td>';
	?>

	<td align="right"><?php echo $this->ConvBytes($this->escape($line['volbytes']));?></td>
	<td align="right"><?php echo $this->ConvBytes($this->escape($line['maxvolbytes']));?></td>

	<?php
		if ( ( isset($line['firstwritten'])) && ($this->escape($line['voljobs']) <= 0) )
			echo '<td class="text-center warning">', number_format($this->escape($line['voljobs'])), '</td>';
        else
            echo '<td class="text-center"> <a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                number_format($this->escape($line['voljobs'])), '</a></td>';
	?>

        <td class="text-center"><?php echo $this->translate->_($this->ConvSecondsToDays($this->escape($line['volretention']))).' '. $this->translate->_("days");?></td>
	<td class="text-center"><?php echo $this->escape($line['mediatype']);?></td>
        <td class="text-center"><?php echo $this->escape(date($this->datetime_format, strtotime($line['lastwritten'])));?></td>
	<td class="text-center"><?php echo $this->escape($line['slot']);?></td>
        <td class="text-center"><?php echo $this->translate->_($this->Int2Char($this->escape($line['recycle'])));?></td>
        <?php
           $expiresin = strtotime($line['lastwritten']) + $line['volretention'];
           $line['expiresin'] = strftime("%Y-%m-%d %H:%M:%S", $expiresin);
        ?>
        <td class="text-center"><?php echo $this->escape(date($this->date_format, strtotime($line['expiresin'])));?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<?php else: ?>
<div class="ui-widget" style="float: left;">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
		<p><span class="ui-icon ui-icon-circle-check" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("Information from DB Catalog : All Volumes are OK.");?></strong></p>
	</div>
</div>
<div style="clear: both;"><!--  --></div>
<?php endif; ?>

<p>&nbsp;</p>


<!-- <h1><?php echo $this->escape($this->titleVolumesNeedReplacement); ?></h1> -->

<?php if ($this->resultVolumesNeedReplacement): ?>
<table id="box-table-dashboard2" class="table table-striped table-hover table-condensed">
<thead>
<tr>
    <th scope="col"> <?php print $this->translate->_("Volume Name"); ?> </th>
    <th scope="col"> <?php print $this->translate->_("Volume Status"); ?> </th>
    <th scope="col"> <?php print $this->translate->_("Volume Bytes"); ?> </th>
    <th scope="col"> <?php print $this->translate->_("Media<br />Type"); ?> </th>
    <th scope="col"> <?php print $this->translate->_("Volume Jobs"); ?> </th>
    <th scope="col"> <?php print $this->translate->_("Mounts"); ?> </th>
    <th scope="col"> <?php print $this->translate->_("Number of writes"); ?> </th>
    <th scope="col"> <?php print $this->translate->_("Errors"); ?> </th>
</tr>
</thead>
<tbody>
<?php foreach($this->resultVolumesNeedReplacement as $line) : ?>
<tr>
    <td class="text-left">
    <a href="<?php echo $this->baseUrl, '/volume/detail/mediaid/'.$this->escape($line['mediaid']); ?> " title="<?php
       echo $this->translate->_("Detail Volume"); ?>">
       <?php echo $this->escape($line['volumename']);?>
    </a>
    </td>

    <?php
        // http://www.bacula.org/developers/Catalog_Services.html
        // Status of media: Full, Archive, Append, Recycle, Read-Only, Disabled, Error, Busy
        if ( $this->escape($line['volstatus']) == 'Disabled' )
            echo '<td class="text-center warning">', $this->escape($line['volstatus']), '</td>';
        elseif ( $this->escape($line['volstatus']) == 'Error' )
            echo '<td class="text-center danger">', $this->escape($line['volstatus']), '</td>';
        else
            echo '<td class="text-center">', $this->escape($line['volstatus']), '</td>';
    ?>
    <td align="right"><?php echo $this->ConvBytes($this->escape($line['volbytes']));?></td>
    <td align="right"><?php echo $this->escape($line['mediatype']);?></td>
    <?php
        if ( ( isset($line['firstwritten'])) && ($this->escape($line['voljobs']) <= 0) )
            echo '<td class="warning" class="text-right">', number_format($this->escape($line['voljobs'])), '</td>';
        else
            echo '<td class="text-right"> <a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                number_format($this->escape($line['voljobs'])), '</a></td>';
    ?>
    <td align="right"><?php echo $this->escape($line['volmounts']);?></td>
    <td align="right"><?php echo $this->escape($line['volwrites']);?></td>

    <?php
        if ( $this->escape($line['volerrors']) == 0 )
            echo '<td class="text-right"></td>';
        else
            echo '<td  class="text-right danger">' . $this->escape($line['volerrors']) . '</td>';
    ?>

</tr>
<?php endforeach; ?>
</tbody>
</table>

<?php //else: ?>
<div class="ui-widget" style="float: left;">
    <div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
        <p><span class="ui-icon ui-icon-circle-check" style="float: left; margin-right: 0.3em;"></span>
        <strong><?php print $this->translate->_("Information from DB Catalog : All Volumes are OK.");?></strong></p>
    </div>
</div>
<div style="clear: both;"><!--  --></div>
<?php endif; ?>

	   </p><!-- close p -->
    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->