<!-- volume/problem.phtml -->
<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-danger">
         <div class="panel-heading">
            <?php echo $this->escape($this->titleProblemVolumes); ?>
         </div>
         <div class="panel-body">
            <p>
               <?php if ($this->resultProblemVolumes): ?>
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                           <th> <?php print $this->translate->_("Volume Name"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Volume Status"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Volume Bytes"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Max Volume<br />Bytes"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Volume Jobs"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Volume<br />Retention<br />(days)"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Media<br />Type"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Last<br />Written"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Autochanger<br />Slot<br />Number"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Can Recycle<br />Volume"); ?> </th>
                           <th class="text-center"> <?php echo $this->translate->_("Expires In"); ?></th>
                        </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->resultProblemVolumes as $line) : ?>
                        <tr>
                           <td>
                              <a href="<?php echo $this->baseUrl, '/volume/detail/mediaid/'.$this->escape($line['mediaid']); ?> " title="<?php
                                 echo $this->translate->_("Detail Volume"); ?>">
                                 <?php echo $this->escape($line['volumename']);?>
                              </a>
                           </td>
                        
                           <?php
                              // http://www.bacula.org/developers/Catalog_Services.html
                              // Status of media: Full, Archive, Append, Recycle, Read-Only, Disabled, Error, Busy
                              if ( $this->escape($line['volstatus']) == 'Disabled' )
                                 echo '<td class="text-center warning">', $this->escape($line['volstatus']), '</td>';
                              elseif ( $this->escape($line['volstatus']) == 'Error' )
                                 echo '<td class="text-center danger">', $this->escape($line['volstatus']), '</td>';
                              else
                                 echo '<td class="text-center">', $this->escape($line['volstatus']), '</td>';
                           ?>
                        
                           <td class="text-right"><?php echo $this->ConvBytes($this->escape($line['volbytes']));?></td>
                           <td class="text-right"><?php echo $this->ConvBytes($this->escape($line['maxvolbytes']));?></td>
                        
                           <?php
                              if ( ( isset($line['firstwritten'])) && ($this->escape($line['voljobs']) <= 0) )
                                 echo '<td class="text-center warning">', number_format($this->escape($line['voljobs'])), '</td>';
                              else
                                 echo '<td class="text-center"> <a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                                 'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                                 number_format($this->escape($line['voljobs'])), '</a></td>';
                           ?>
                        
                           <td class="text-center"><?php echo $this->translate->_($this->ConvSecondsToDays($this->escape($line['volretention']))).' '. $this->translate->_("days");?></td>
                           <td class="text-center"><?php echo $this->escape($line['mediatype']);?></td>
                           <td class="text-center"><?php echo $this->escape(date($this->datetime_format, strtotime($line['lastwritten'])));?></td>
                           <td class="text-center"><?php echo $this->escape($line['slot']);?></td>
                           <td class="text-center"><?php echo $this->translate->_($this->Int2Char($this->escape($line['recycle'])));?></td>
                           <?php
                              $expiresin = strtotime($line['lastwritten']) + $line['volretention'];
                              $line['expiresin'] = strftime("%Y-%m-%d %H:%M:%S", $expiresin);
                           ?>
                           <td class="text-center"><?php echo $this->escape(date($this->date_format, strtotime($line['expiresin'])));?></td>
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
                     
               <?php else: ?>

               <!-- div alert -->
               <div class="alert alert-warning">
                 <p>
                 <span class="glyphicon glyphicon-info-sign"></span>
                 <?php print $this->translate->_("Information from DB Catalog : All Volumes are OK."); ?>
                 </p>
               </div>
               <!-- end div alert -->
               
               <?php endif; ?>
                     
               <!--<h3><?php echo $this->escape($this->titleVolumesNeedReplacement); ?></h3>-->
               
               <?php if ($this->resultVolumesNeedReplacement): ?>
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                            <th> <?php print $this->translate->_("Volume Name"); ?> </th>
                            <th> <?php print $this->translate->_("Volume Status"); ?> </th>
                            <th> <?php print $this->translate->_("Volume Bytes"); ?> </th>
                            <th> <?php print $this->translate->_("Media<br />Type"); ?> </th>
                            <th> <?php print $this->translate->_("Volume Jobs"); ?> </th>
                            <th> <?php print $this->translate->_("Mounts"); ?> </th>
                            <th> <?php print $this->translate->_("Number of writes"); ?> </th>
                            <th> <?php print $this->translate->_("Errors"); ?> </th>
                        </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->resultVolumesNeedReplacement as $line) : ?>
                        <tr>
                           <td class="text-left">
                           <a href="<?php echo $this->baseUrl, '/volume/detail/mediaid/'.$this->escape($line['mediaid']); ?> " title="<?php
                              echo $this->translate->_("Detail Volume"); ?>">
                              <?php echo $this->escape($line['volumename']);?>
                           </a>
                           </td>
                        
                            <?php
                                // http://www.bacula.org/developers/Catalog_Services.html
                                // Status of media: Full, Archive, Append, Recycle, Read-Only, Disabled, Error, Busy
                                if ( $this->escape($line['volstatus']) == 'Disabled' )
                                    echo '<td class="text-center warning">', $this->escape($line['volstatus']), '</td>';
                                elseif ( $this->escape($line['volstatus']) == 'Error' )
                                    echo '<td class="text-center danger">', $this->escape($line['volstatus']), '</td>';
                                else
                                    echo '<td class="text-center">', $this->escape($line['volstatus']), '</td>';
                            ?>
                           <td class="text-right"><?php echo $this->ConvBytes($this->escape($line['volbytes']));?></td>
                           <td class="text-right"><?php echo $this->escape($line['mediatype']);?></td>
                           <?php
                               if ( ( isset($line['firstwritten'])) && ($this->escape($line['voljobs']) <= 0) )
                                   echo '<td class="warning" class="text-right">', number_format($this->escape($line['voljobs'])), '</td>';
                               else
                                   echo '<td class="text-right"><a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                                       'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                                       number_format($this->escape($line['voljobs'])), '</a></td>';
                           ?>
                           <td class="text-right"><?php echo $this->escape($line['volmounts']);?></td>
                           <td class="text-right"><?php echo $this->escape($line['volwrites']);?></td>
                           
                           <?php
                               if ( $this->escape($line['volerrors']) == 0 )
                                   echo '<td class="text-right"></td>';
                               else
                                   echo '<td  class="text-right danger">' . $this->escape($line['volerrors']) . '</td>';
                           ?>
                           
                           
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
               
               <?php endif; ?>
               
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div rows -->
<!-- volume/problem.phtml -->