<!-- volume/problem-dashboard.phtml -->
<div class="panel panel-default panel-danger">
   <div class="panel-heading">
         <a href="<?php echo $this->baseUrl;?>/volume/problem" id="dashboard"><?php echo $this->escape($this->titleProblemVolumes); ?></a>
   </div>
   <div class="panel-body">
      <p>
         <?php if ($this->resultProblemVolumes): ?>
         <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed">
               <thead>
                  <tr>
                     <th> <?php print $this->translate->_("Volume Name"); ?> </th>
                     <th> <?php print $this->translate->_("Volume Status"); ?> </th>
                     <th> <?php print $this->translate->_("Volume Bytes"); ?> </th>
                     <th> <?php print $this->translate->_("Max Volume<br />Bytes"); ?> </th>
                     <th> <?php print $this->translate->_("Volume Jobs"); ?> </th>
                     <th> <?php print $this->translate->_("Volume<br />Retention<br />(days)"); ?> </th>
                     <th> <?php print $this->translate->_("Media<br />Type"); ?> </th>
                  </tr>
               </thead>
               <tbody>
               <?php foreach($this->resultProblemVolumes as $line) : ?>
                  <tr>
                     <td class="text-left">
                        <a href="<?php echo $this->baseUrl.'/volume/detail/mediaid/'.$this->escape($line['mediaid']);?>"
                           title="<?php echo $this->translate->_("Detail Volume");?>"><?php echo $this->escape($line['volumename']);?>
                        </a>
                     </td>
                  
                     <?php
                        // http://www.bacula.org/developers/Catalog_Services.html
                        // Status of media: Full, Archive, Append, Recycle, Read-Only, Disabled, Error, Busy
                        if ( $this->escape($line['volstatus']) == 'Disabled' )
                           echo '<td class="text-center warning">', $this->escape($line['volstatus']), '</td>';
                        elseif ( $this->escape($line['volstatus']) == 'Error' )
                           echo '<td class="text-center danger">', $this->escape($line['volstatus']), '</td>';
                        else
                           echo '<td class="text-center">', $this->escape($line['volstatus']), '</td>';
                     ?>
                  
                     <td class="text-right"><?php echo $this->ConvBytes($this->escape($line['volbytes']));?></td>
                     <td class="text-right"><?php echo $this->ConvBytes($this->escape($line['maxvolbytes']));?></td>
                  
                     <?php
                        if ( ( isset($line['firstwritten'])) && ($this->escape($line['voljobs']) <= 0) )
                           echo '<td class="text-right warning">', number_format($this->escape($line['voljobs'])), '</td>';
                        else
                            echo '<td class="text-right"> <a href="', $this->baseUrl, '/job/find-volume-name/volname/', $this->escape($line['volumename']), '" ',
                                'title="', $this->translate->_("List Jobs by Volume Name"), '">',
                                  number_format($this->escape($line['voljobs'])), '</a></td>';
                     ?>
                  
                     <td class="text-center"><?php echo $this->ConvSecondsToDays($this->escape($line['volretention']));?></td>
                     <td><?php echo $this->escape($line['mediatype']);?></td>
                  </tr>
               <?php endforeach; ?>
               </tbody>
            </table>
         </div><!-- end div table-responsive -->
         
         <?php else: ?>
         
         <!-- div alert -->
         <div class="alert alert-warning">
           <p>
           <span class="glyphicon glyphicon-info-sign"></span>
           <?php print $this->translate->_("Information from DB Catalog : All Volumes are OK."); ?>
           </p>
         </div>
         <!-- end div alert -->         
         
         
         <?php endif; ?>
      </p><!-- close p -->
   </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->
<!-- volume/problem-dashboard.phtml -->