<!-- bconsole/cmd.phtml -->
 <?php
   echo $this->msg;
   if ( !$this->return_var ){
      //echo "<pre>";
      foreach ($this->command_output as $line){
           echo '<br/>', $line;
       }
       //echo "</pre>";
       echo '<br/>';
   } else {
      echo $this->bcommand,": ", "is a invalid command!";
   }
   
?>
<?php 
   if ($this->return_var )
      echo $this->return_var;
   else
      echo 'null';
?>
<!-- end bconsole/cmd.phtml -->