<!-- bconsole/wterminal.phtml -->
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery.terminal.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery.mousewheel-min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/styles/default/jquery.terminal.min.css" media="screen" />

<script type="text/javascript">

$(function() {
    var cmd = {
        'add':null,
        'autodisplay':null,
        'automount':null,
        'cancel':null,
        'create':null,
        'disable':null,
        'enable':null,
        'estimate':null,
        'help':null,
        'label':null,
        'list':null,
        'llist':null,
        'messages':null,
        'memory':null,
        'mount':null,
        'prune':null,
        'purge':null,
        'python':null,
        'query':null,
        'restore':null,
        'relabel':null,
        'release':null,
        'reload':null,
        'run':null,
        'status':null,
        'stop':null,
        'setdebug':null,
        'setbandwidth':null,
        'show':null,
        'time':null,
        'trace':null,
        'unmount':null,
        'umount':null,
        'use':null,
        'version':null,
        'wait':null
    };
    
   var welcome = '[[b;#337AB7;]All command will be send to Bacula Console (bconsole).\n' +
                 'Bacula Console commands will be written like command line style.\n' +
                 'See Bacula documentation "Running the Console from a Shell Script" for details.\n' +
                 'clear - clear the screen\n]'

    $('#wterm').terminal(function(command, term) {
        term.pause();
        if(command != ""){
           $.post('<?php echo $this->baseUrl, '/bconsole/cmd' ?>', {'bcommand': command, 'command': cmd }).then(function(response) {
               term.echo(response,{raw:true}).resume();
           });
        } else{
          term.exec('clear').resume();  
        } //end if
      }, 
      {
        greetings: welcome,
        prompt: 'bconsole> ',
        height: 400,
        onBlur: function(){
           return false;
        }
        
      }
   );
});

</script>

<div class="rows">
   <div class="col-md-12">
      <div class="panel panel-default panel-primary panel-logoutput">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <div class="table-responsive">
               <pre id='wterm'></pre>
            </div><!-- end div table-responsive -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div row -->
<!-- bconsole/wterminal.phtml -->