<!-- application/views/scripts/auth/forgot-password.phtml -->

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12"> 

<div>
<h4 class="text-center"><?php echo $this->caption; ?></h4>
</div>
	
<!-- ###########################################################################-->
<form  action="<?php echo $this->form->getAction( $this->url() );  ?>"
        method="<?php echo $this->form->getMethod();  ?>">

        <?php echo $this->form->captcha; ?>
        <?php echo $this->form->csrf; ?>
		
		
  <div class="form-group">
    <?php echo $this->form->login; ?>
  </div>
  <div class="form-group">
    <?php echo $this->form->email; ?>
  </div>
  <div class="text-right">
  <!--<button type="submit" class="btn btn-default">Submit</button>-->
  <!--<?php echo $this->formSubmit('ok1', $this->translate->_('Log In'), array('class' => 'btn btn-default', 'style' => 'padding:10px; width: 100px;') ); ?>-->
  <?php echo $this->form->submit; ?>
  </div>
  <div class="text-right">
  </div>
</form>
<!-- ###########################################################################-->	
	
	
	
	
<!--
<p>
<?php echo $this->translate->_('Forgot your password? Enter your user name and email below.'); ?>
</p>

<div style="font-weight:bold; color:red;">
    <?php echo $this->msg; ?> &nbsp;
</div>

<form  action="<?php echo $this->form->getAction( $this->url() );  ?>"
        method="<?php echo $this->form->getMethod();  ?>">

<table border="0" cellspacing="7" class="text-center">
<tr>
    <td class="text-center">
        <span class="ui-icon ui-icon-person"></span>
    </td>
    <td>
        <b><?php echo $this->translate->_('Username'); ?></b>
    </td>
    <td class="text-left" colspan="2">
        <?php echo $this->form->login; ?>
    </td>
</tr>
<tr>
    <td class="text-center">
        <span class="ui-icon ui-icon-mail-closed"></span>
    </td>
    <td>
        <b><?php echo $this->translate->_('Email'); ?></b>
    </td>
    <td class="text-left">
        <?php echo $this->form->email; ?>
    </td>
</tr>

<tr>
    <td colspan="3"> &nbsp;
        <?php echo $this->form->captcha; ?>
        <?php echo $this->form->csrf; ?>
    </td>
</tr>

<tr>
    <td colspan="2">
        <?php echo $this->form->submit; ?>
    </td>
    <td class="text-right">
        <a href="<?php echo $this->baseUrl; ?>/index/index"><b> <?php echo $this->translate->_('Cancel'); ?> </b></a>
    </td>
</tr>

</table>
</form>
-->

    </div><!-- fim da div div class="col-md-12" -->
  </div><!-- fim da div row -->
</div><!-- end div container-fluid -->