<!-- application/views/scripts/auth/forgot-password.phtml -->

<h2 align="center"><?php echo $this->title; ?></h2>

<p>
<?php echo $this->translate->_('Forgot your password? Enter your user name and email below.'); ?>
</p>

<div style="font-weight:bold; color:red;">
    <?php echo $this->msg; ?> &nbsp;
</div>

<form  action="<?php echo $this->form->getAction( $this->url() );  ?>"
        method="<?php echo $this->form->getMethod();  ?>">

<table border="0" cellspacing="7" align="center">
<tr>
    <td align="center">
        <span class="ui-icon ui-icon-person"></span>
    </td>
    <td>
        <b><?php echo $this->translate->_('Username'); ?></b>
    </td>
    <td align="left" colspan="2">
        <?php echo $this->form->login; ?>
    </td>
</tr>
<tr>
    <td align="center">
        <span class="ui-icon ui-icon-mail-closed"></span>
    </td>
    <td>
        <b><?php echo $this->translate->_('Email'); ?></b>
    </td>
    <td align="left">
        <?php echo $this->form->email; ?>
    </td>
</tr>
<tr>
    <td colspan="3"> &nbsp;
        <?php echo $this->form->captcha; ?>
        <?php echo $this->form->csrf; ?>
    </td>
</tr>
<tr>
    <td colspan="2">
        <?php echo $this->form->submit; ?>
    </td>
    <td align="right">
        <a href="<?php echo $this->baseUrl; ?>/index/index"><b> <?php echo $this->translate->_('Cancel'); ?> </b></a>
    </td>
</tr>

</table>
</form>
