<!-- application/views/scripts/auth/login.phtml -->
<script>
  $( function() {
    $( "input" ).checkboxradio();
  } );
  </script>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12"> 
   
<div style="font-weight:bold; color:red;">
    <?php echo $this->msg; ?> &nbsp;
</div>

<!-- ###########################################################################-->
<form  action="<?php echo $this->form->getAction( $this->url() );  ?>"
        method="<?php echo $this->form->getMethod();  ?>">

        <?php echo $this->form->captcha; ?>
        <?php echo $this->form->csrf; ?>

<div>
<h4 align="center"><?php echo $this->caption; ?></h4>
</div>
		
		
  <div class="form-group">
    <?php echo $this->form->login; ?>
  </div>
  <div class="form-group">
    <?php echo $this->form->pwd; ?>
  </div>
  <div class="checkbox text-left">
    <label>
	   <?php echo $this->form->rememberme; ?>
       <?php echo $this->translate->_('Remember me'); ?>
    </label>
  </div>
  <div class="text-right">
  <!--<button type="submit" class="btn btn-default">Submit</button>-->
  <?php echo $this->formSubmit('ok1', $this->translate->_('Log In'), array('class' => 'btn btn-default', 'style' => 'padding:10px; width: 100px;') ); ?>
  </div>
  <div class="text-right">
  <br/>
  <a href="<?php echo $this->baseUrl; ?>/auth/forgot-password"><?php echo $this->translate->_('Forgot?'); ?></a>
  </div>
</form>
<!-- ###########################################################################-->

<!-- ############################################################################################################## -->

    </div><!-- fim da div div class="col-md-12" -->
  </div><!-- fim da div row -->
</div><!-- end div container-fluid -->