<!-- pool/all.phtml -->
<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               <?php $urlp = $this->baseUrl . '/pool/all';?>
               <div class="table-responsive">
                  <table id="box-table-dashboard2" class="table table-striped table-hover table-condensed">
                     <thead>
                     <tr>
                        <th><a href="<?php echo $urlp; ?>/order/Name"><?php echo $this->translate->_("Name Pool"); ?></a></th>
                        <th><a href="<?php echo $urlp; ?>/order/LabelFormat"><?php echo $this->translate->_("Label Format"); ?></a></th>
                        <th class="text-center"><a href="<?php echo $urlp; ?>/order/NumVols"><?php echo $this->translate->_("Number<br />Volumes"); ?></a></th>
                        <th class="text-center"><a href="<?php echo $urlp; ?>/order/MaxVols"><?php echo $this->translate->_("Max<br />Volumes"); ?></a></th>
                        <th class="text-center"><a href="<?php echo $urlp; ?>/order/VolRetention"><?php echo $this->translate->_("Volume<br />Retention<br />(days)"); ?></a></th>
                        <th class="text-center"><a href="<?php echo $urlp; ?>/order/MaxVolBytes"><?php echo $this->translate->_("Max<br />Volume<br />(Bytes)"); ?></a></th>
                        <th class="text-center"><?php print $this->translate->_("Auto Prune"); ?></th>
                        <th class="text-center"><?php print $this->translate->_("Auto Recycle"); ?></th>
                        <th class="text-center"><?php print $this->translate->_("Type"); ?></th>
                     </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->pools as $pool) : ?>
                        <tr>
                           <td>
                              <a href="<?php echo $this->baseUrl;?>/volume/find-pool-id/id/<?php echo $this->escape($pool['poolid']);?>/name/<?php echo $this->escape($pool['name']);?>"
                              title="<?php echo $this->translate->_("Show Volumes"); ?>">
                              <?php echo $this->escape($pool['name']); ?></a>
                           </td>
                           <td><?php echo $this->escape($pool['labelformat']);?></td>
                           <?php
                           if ( $this->escape($pool['numvols']) <= 0 ) {
                               echo '<td class="text-center warning">' . $this->escape($pool['numvols']) . '</td>';
                           } else {
                               echo '<td class="text-center">' . $this->escape($pool['numvols']) . '</td>';
                           }
                           ?>
                        
                           <?php
                           if ( $pool['maxvols'] <= 0 ) {
                              echo '<td class="text-center">' . $this->translate->_('unlimited') . '</td>';
                           } else {
                              echo '<td class="text-center">' . $this->escape($pool['maxvols']) . "</td>";
                           }
                           ?>
                           <td align="center"><?php echo $this->convSecondsToDays($this->escape($pool['volretention'])) . ' ' . $this->translate->_('days');?></td>
                           <?php
                           if ( $pool['maxvolbytes'] <= 0 ) {
                               echo '<td class="text-center">' . $this->translate->_('unlimited') . '</td>';
                           } else {
                               echo '<td class="text-center">' . $this->convBytes($this->escape($pool['maxvolbytes'])) . "</td>";
                           }
                           ?>
                           <td align="center"><?php echo $this->translate->_($this->int2Char($this->escape($pool['autoprune'])));?></td>
                           <td align="center"><?php echo $this->translate->_($this->int2Char($this->escape($pool['recycle'])));?></td>
                           <td align="center"><?php echo $this->escape($pool['pooltype']);?></td>
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
            </p><!-- close p -->
         </div><!-- close div panel-body -->
      </div><!-- close div panel panel-default -->
   </div><!-- end col-md-8 -->
</div><!-- end div row -->
<!-- pool/all.phtml -->