<!-- client/all.phtml -->
<!--
<h1><?php echo $this->escape($this->title); ?></h1>-->
<?php if ($this->schedule): ?>

<div class="rows">
  <div class="col-md-10">

<div class="panel panel-default panel-primary">
	<div class="panel-heading">
	   <?php echo $this->escape($this->title); ?>
	</div>
	<div class="panel-body">
	   <p>
<div class="table-responsive">
<table id="box-table-dashboard2" class="table table-striped table-hover table-condensed">
<thead>
<tr>
    <th><?php print $this->translate->_("Name"); ?></th>
    <th><?php print $this->translate->_("Level"); ?></th>
    <th class="text-center"><?php print $this->translate->_("Time"); ?></th>
    <th class="text-center"><?php print $this->translate->_("Week Day"); ?></th>
    <th class="text-center"><?php print $this->translate->_("Day"); ?></th>
    <th class="text-center"><?php print $this->translate->_("Month"); ?></th>
    <th class="text-center"><?php print $this->translate->_("Week Month"); ?></th>
    <th class="text-center"><?php print $this->translate->_("Week Year"); ?></th>
    <th><?php print $this->translate->_("Pool"); ?></th>
    <th><?php print $this->translate->_("Storage"); ?></th>
    <th><?php print $this->translate->_("Device"); ?></th>
    <th class="text-center"><?php print $this->translate->_("Enabled"); ?></th>
</tr>
</thead>
<tbody>
<?php foreach($this->schedule as $value1) : ?>
<?php    
          $rowspan =  count($value1['schedule'])+1; 
          $i=0;
?>


<tr>
     <td rowspan="<?php echo $rowspan;?>" class="vertical-center">
        <a href="<?php echo $this->baseUrl, "/schedule/show/name/", $this->escape($value1['name']); ?>" title="<?php echo $this->translate->_("Show Schedule");?>">
		  <?php echo $this->escape($value1['name']);?>
		</a>	 
	 </td>
     <?php foreach($value1['schedule'] as $value2) : ?>
      <tr>
         <td><?php echo $this->escape($value2['level']);?></td>
         <td class="text-center"><?php echo $this->escape($value2['hour']);?></td>
         <td class="text-center"><?php echo $this->escape($value2['weekday']);?></td>
         <td class="text-center"><?php echo $this->escape($value2['day']);?></td>
         <td class="text-center"><?php echo $this->escape($value2['month']);?></td>
         <td class="text-center"><?php echo $this->escape($value2['weekmonth']);?></td>
         <td class="text-center"><?php echo $this->escape($value2['weekyear']);?></td>


         <?php if ( isset($value2['pool'] )): ?>
                  <td><?php echo $this->escape($value2['pool']); ?></td>
         <?php else : ?>
                  <td>&nbsp;-&nbsp;</td>
         <?php endif; ?>
       
 
         <?php if ( isset($value2['storage'] )): ?>
                  <td><?php echo $this->escape($value2['storage']); ?></td>
         <?php else : ?>
                  <td>&nbsp;-&nbsp;</td>
         <?php endif; ?>


         <?php if ( isset($value2['device'] )): ?>
                  <td><?php echo $this->escape($value2['device']); ?></td>
         <?php else : ?>
                  <td>&nbsp;-&nbsp;</td>
         <?php endif; ?>


         <?php if ( $i == 0 ): ?>
                  <td class="text-center vertical-center" rowspan="<?php echo $rowspan;?>"><?php echo $this->translate->_($this->int2Char($this->escape($value1['status']))); ?></td>
         <?php endif; ?>
         <?php $i++; ?>
</tr>
     <?php endforeach; ?>
</tr>
<?php endforeach; ?>
</tbody>
</table>
</div><!-- end div table-responsive -->

<?php endif; ?>

	   </p><!-- close p -->
    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->

</div><!-- fim div col-md-10 -->
</div><!-- fim da div row -->
