
<?php $translate = Zend_Registry::get('translate'); ?>

<!-- footer menu -->
<div id="center_for_ie2">
<div id="bottommenu">
    <div class="bottommenua">
<b><a href="<?php echo $this->baseUrl;?>"><?php print $translate->_("Desktop"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/director/statusdir"><?php print $translate->_("Director"); ?></a></b>&nbsp;|&nbsp;
<b><?php print $translate->_("Job"); ?> : </b>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/last"><?php print $translate->_("Last"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/running"><?php print $translate->_("Running Jobs"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/next"><?php print $translate->_("Next"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/problem"><?php print $translate->_("Problem"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/run-job"><?php print $translate->_("Run Job"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/find-form"><?php print $translate->_("Search"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/timeline"><?php print $translate->_("Timeline"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/restorejob/main-form"><?php print $translate->_("Restore"); ?></a>&nbsp;|&nbsp;
<b><?php print $translate->_("Pool/Volume"); ?> : </b>&nbsp;
<a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $translate->_("Overview"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/volume/problem"><?php print $translate->_("Problem"); ?></a>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/client/all"><?php print $translate->_("Client"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/storage/storage"><?php print $translate->_("Storage"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/wblogbook/index"><?php print $translate->_("Logbook"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/help/"><?php print $translate->_("Help"); ?></a></b>
    </div>
</div>
</div> <!-- end of ieCenter div -->

<!-- Page generated in : <?php if ( $this->time_pgen ) { echo $this->time_pgen; } ?> sec -->

</body>
</html>
