<?php
header("Expires: Thu, 01 Jan 1970 00:00:01 GMT");               // Date in the past
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");  // Always modified
header("Cache-Control: no-cache, must-revalidate");             // HTTP/1.1
header("Pragma: no-cache");                                     // HTTP/1.0

$translate = Zend_Registry::get('translate');
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title><?php echo $this->escape($this->title); ?></title>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/default/site.css" />
		<meta http-equiv="Pragma" content="no-cache">
	    <meta http-equiv="expires" content="0">

</head>
<body style="margin: 0">
<div align="center"><a href="<?php echo $this->baseUrl ?>/wblogbook/index"><?php print $translate->_("Back"); ?></a></div>
