<?php $translate = Zend_Registry::get('translate'); ?>
<ul id="main-menu" class="sf-menu">
   	<li><a href="<?php echo $this->baseUrl;?>/"><?php print $translate->_("Desktop"); ?></a>
       	<ul>
           	<li><a href="<?php echo $this->baseUrl;?>/director/listjobtotals"><?php print $translate->_("Job Totals"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/director/statusdir"><?php print $translate->_("Director"); ?></a></li>
    <li class="current"><a href="<?php echo $this->baseUrl;?>/job/terminated"><?php print $translate->_("Job"); ?></a>
		<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/job/terminated"><?php print $translate->_("Terminated"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/running"><?php print $translate->_("Running"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/next"><?php print $translate->_("Next"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/problem"><?php print $translate->_("Problem"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/run-job"><?php print $translate->_("Run"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/find-form"><?php print $translate->_("Search"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/timeline"><?php print $translate->_("Timeline"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/restorejob/main-form"><?php print $translate->_("Restore"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $translate->_("Pool/Volume"); ?></a>
    	<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $translate->_("Overview"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/volume/problem"><?php print $translate->_("Problem"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/client/all"><?php print $translate->_("Client"); ?></a>
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/storage/storage"><?php print $translate->_("Storage"); ?></a>
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/wblogbook/index"><?php print $translate->_("Logbook"); ?></a>
    	<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/feed/feed"><?php print $translate->_("RSS"); ?></a></li>
        </ul>	
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/help/"><?php print $translate->_("Help"); ?></a>
    </li>
</ul>
<br style="clear: both;" />

<div style="margin: 10px;">&nbsp;</div>