<!-- paginationControl -->
<?php $this->translate = Zend_Registry::get('translate'); ?>

<div class="rows">
<?php if ($this->pageCount): ?>

   <div class="panel">
      <div class="panel-body">
      <?php
          echo "<label>" . $this->translate->_('Showing') . ": " . $this->firstItemNumber, ' - ', $this->lastItemNumber, ' ', $this->translate->_('of'), ' ', $this->totalItemCount . "</label>";
          //$this->translate->_('file(s)');
      ?>
      </div>
   </div>
   
   <div>
     <ul class="pagination">

      <!-- Link to the first page -->
      <?php if (isset($this->previous)): ?>
        <?php echo '<li class="page-item"><a href="', $this->url(array('page' => $this->first)),'">', $this->translate->_('First page'), '</a></li>'; ?>
      <?php endif; ?>
      
      <!-- Link to the previous page -->
      <?php if (isset($this->previous)): ?>
        <?php echo '<li class="page-item"><a href="', $this->url(array('page' => $this->previous)), '">', $this->translate->_('Previous page'), '</a></li>'; ?>
      <?php endif; ?>
      
      <!-- Numbered links to pages -->
      <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
          <?php echo '<li class="page-item"><a href="', $this->url(array('page' => $page)), '"> ', $page, '</a></li>'; ?>
        <?php else: ?>
          <?php echo '<li class="active page-item"><a href="', $this->url(array('page' => $page)), '"> ', $page, '</a></li>'; ?>
        <?php endif; ?>
      <?php endforeach; ?>
      
      <!-- Link to the next page -->
      <?php if (isset($this->next)): ?>
        <?php echo '<li class="page-item"><a href="', $this->url(array('page' => $this->next)), '">', $this->translate->_('Next page'), '</a></li>'; ?>
      <?php endif; ?>
      
      <!-- Link to the last page -->
      <?php if (isset($this->next)): ?>
        <?php echo '<li class="page-item"><a href="', $this->url(array('page' => $this->last)), '">', $this->translate->_('Last page'), '</a></li>'; ?>
      <?php endif; ?>

     </ul>
   </div>

<?php endif; ?>


</div><!-- end div rows -->
<!-- paginationControl -->