<!-- decorators/formFilesetACL.phtml -->
<form  action="<?php echo $this->form_fileset->getAction(); ?>"
       method="<?php echo $this->form_fileset->getMethod(); ?>">
    <?php echo $this->form_fileset->role_id; ?>
    <?php echo $this->form_fileset->role_name; ?>
    <?php echo $this->form_fileset->action_id; ?>
    <?php echo $this->form_fileset->order; ?>
    <?php echo $this->form_fileset->name; ?>
    <?php echo $this->form_fileset->submit; ?>
    <?php echo $this->form_fileset->reset; ?>
</form>
<!-- end decorators/formFilesetACL.phtml -->