<!-- decorators/formUser.phtml -->
<form  action="<?php echo $this->form->getAction();  ?>"
       method="<?php echo $this->form->getMethod();  ?>">
    <?php echo $this->form->user_id; ?>
    <?php echo $this->form->action_id; ?>
    <?php echo $this->form->active; ?>
    <?php echo $this->form->login; ?>
    <?php echo $this->form->pwd; ?>
    <?php echo $this->form->name; ?>
    <?php echo $this->form->email; ?>
    <?php echo $this->form->role_id; ?>
    <?php echo $this->form->submit; ?>
    <?php echo $this->form->reset; ?>
</form>
<!-- end decorators/formUser.phtml -->