<!-- decorators/formClientACL.phtml -->
    <form  action="<?php echo $this->form_client->getAction();  ?>"
            method="<?php echo $this->form_client->getMethod();  ?>">
        <?php echo $this->form_client->role_id; ?>
        <?php echo $this->form_client->role_name; ?>
        <?php echo $this->form_client->action_id; ?>
        <?php echo $this->form_client->order; ?>
        <?php echo $this->form_client->name; ?>
        <?php echo $this->form_client->client_id; ?>
        <?php echo $this->form_client->submit; ?>
        <?php echo $this->form_client->reset; ?>
    </form>
<!-- end decorators/formClientACL.phtml -->