<!-- decorators/formUser.phtml -->
<form  action="<?php echo $this->form->getAction();  ?>"
       method="<?php echo $this->form->getMethod();  ?>">
    <?php echo $this->form->user_id; ?>
    <?php echo $this->form->action_id; ?>
    <?php echo $this->form->active; ?>
    <?php echo $this->form->login; ?>
    <?php echo $this->form->pwd; ?>
    <?php echo $this->form->name; ?>
    <?php echo $this->form->email; ?>
    <?php echo $this->form->role_id; ?>
<br/>
<table>
<tr>
<td>
    <?php echo $this->form->submit_button; ?>
</form>
</td>
<td>&nbsp;&nbsp;&nbsp;</td>
<td>
<!-- end decorators/formUser.phtml -->
<form  action="<?php echo $this->form->getActionCancel();  ?>"
       method="<?php echo $this->form->getMethod();  ?>">
   <?php echo $this->form->cancel_button; ?>
</form>
</td>
</tr>
</table>