<!-- application/views/scripts/decorators/formRestoreoptions.phtml -->
<?php $this->translate = Zend_Registry::get('translate'); ?>

<script type="text/javascript">
$(function() {
   var current_tab = <?php echo (int)($this->tabs_selected + 1); ?>;
   $('.nav-tabs a[href="#tab' + current_tab + '"]').tab('show');
});
</script>

<style type="text/css">
    #link_dialog {padding: .4em 1em .4em 20px;text-decoration: none;position: relative;}
    #link_dialog span.ui-icon {margin: 0 5px 0 0;position: absolute;left: .2em;top: 50%;margin-top: -8px;}
</style>

<script type="text/javascript">
$(function() {
	// tabs
    //$("#tabs").tabs();

    // Dialog
    $('#info_dialog').dialog({
        autoOpen: false,
        width: 680,
        height: 480
    });

    // helps for advanced options
    $('#link_dialog').click(function(){
        $('#info_dialog').dialog('open');
        return false;
    });
});
</script>

<script type="text/javascript">
$(document).ready(function() {
	$('#ok1').click(function() {
    	$.blockUI({
        	message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
        	css: { backgroundColor: '#f3fcf2' },
        	centerX: true,
        	centerY: true
        });
    });
});
</script>

<script type="text/javascript">
  // select
  $(function(){
      $('select').each(function() {
         $(this).addClass("select-overflow").addClass("form-control");
      });
  });
</script>


<div>
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation"><a href="#tab1" aria-controls="tab" role="tab" data-toggle="tab"><?php print $this->translate->_("Standard options"); ?></a></li>
  <li role="presentation"><a href="#tab2" aria-controls="tab" role="tab" data-toggle="tab"><?php print $this->translate->_("Advanced options"); ?></a></li>
</ul>

<br/>
<!-- Tab panes -->
<div class="tab-content">

   <!-- tab1 Role -->
   <div role="tabpanel" class="tab-pane" id="tab1">
   <div class="container-fluid">
   <div class="row">
      <div class="col-md-12">
         <!-- tabs-standard-options -->
         <div id="tabs-standard-options">
         <form method="<?php echo $this->escape($this->form->getMethod()); ?>"
               action="<?php echo $this->escape($this->form->getAction()); ?>"
               name="formRestoreoptions" id="formRestoreoptions">
         
         <?php
             // hidden fields
             echo $this->form->from_form;
             echo $this->form->type_restore; // TODO not used ?
             echo $this->form->jobid;
             echo $this->form->fileid;
         ?>
         
         <table class="table table-condensed table-borderless">
            <tr>
               <!-- client -->
               <td class="text-right">
                  <label for="client_name"><b><?php print $this->translate->_("Client"); ?></b></label>
               </td>
               <td class="text-left">
                  <?php echo $this->form->client_name;?>
               </td>
               <td class="text-right">
                   <label for="pool"><?php print $this->translate->_("Pool"); ?></label>
               </td>
               <td class="text-left">
                   <?php echo $this->form->pool;?>
               </td>
            </tr>
            <tr>
               <!-- restoreclient -->
               <td class="text-right">
                  <label for="client_name_to"><b><?php print $this->translate->_("Restore client"); ?></b></label>
               </td>
               <td class="text-left">
                  <?php echo $this->form->client_name_to;?>
               </td>
               <!-- Fileset -->
               <td class="text-right">
                  <label for="fileset"><?php print $this->translate->_("Fileset"); ?></label>
               </td>
               <td class="text-left">
                  <?php echo $this->form->fileset;?>
               </td>
            </tr>
            <tr>
               <?php if ( $this->form->restore_job_select ) : ?>
               <!-- if have multiple Restore Job resources -->
               <td class="text-right">
                   <label for="restore_job_select"><b><?php print $this->translate->_("Restore Job Resource"); ?></b></label>
               </td>
               <td class="text-left">
                   <?php echo $this->form->restore_job_select;?>
               </td>
               <?php else: ?>
                 <td colspan="2">&nbsp;</td>
               <?php endif; ?>            
               <!-- Storage -->
               <td class="text-right">
                 <label for="storage"><?php print $this->translate->_("Storage"); ?></label>
               </td>
               <td class="text-left">
                 <?php echo $this->form->storage;?>
               </td>
            </tr>
         </table>
         </div><!-- end div tabs-standard-options -->
         <!-- end tabs-standard-options -->
      
      
      </div><!-- end div col-md-6 -->
   </div><!-- end div row -->
   </div><!-- end div container-fluid -->
   </div><!-- end div tab1 -->
   <!-- end tab1 Role -->
   
   <!-- tab2 Role -->
   <div role="tabpanel" class="tab-pane" id="tab2">
   <div class="container-fluid">
   <div class="row">
      <!-- role form -->
      <div class="col-md-12">

         <div id="tabs-advanced-options">
         
         <p>
         <a href="#" id="link_dialog" class="btn btn-default">
             <span class="glyphicon glyphicon-alert"></span>
             <?php print $this->translate->_("Help"); ?>
         </a>
         </p>
         
         <table class="table table-condensed table-borderless">
            <tr>
               <!-- Where -->
               <td class="text-right"><label for="where"><?php print $this->translate->_("Where"); ?></label> </td>
               <td class="text-left"><?php echo $this->form->where;?> </td>
               <td class="text-left text-vcenter"><?php print $this->translate->_("Restore files in <b>where</b> directory."); ?></td>
            </tr>
            <tr>
               <!-- strip_prefix -->
               <td  class="text-right"><label for="strip_prefix"><?php print $this->translate->_("Strip&nbsp;prefix"); ?></label> </td>
               <td  class="text-left"><?php echo $this->form->strip_prefix;?> </td>
               <td  class="text-left text-vcenter"><?php print $this->translate->_("Remove a part of the filename when restoring."); ?></td>
            </tr>
            <tr>
               <!-- add_prefix -->
               <td  class="text-right"><label for="add_prefix"><?php print $this->translate->_("Add&nbsp;prefix"); ?></label> </td>
               <td  class="text-left"><?php echo $this->form->add_prefix; ?> </td>
               <td  class="text-left text-vcenter"><?php print $this->translate->_("Add a prefix to all files when restoring (like where) (can't be used with <b>where</b>)."); ?></td>
            </tr>
            <tr>
               <!-- add_suffix -->
               <td  class="text-right"><label for="add_suffix"><?php print $this->translate->_("Add&nbsp;suffix"); ?></label> </td>
               <td  class="text-left"><?php echo $this->form->add_suffix; ?> </td>
               <td  class="text-left text-vcenter"><?php print $this->translate->_("Add a suffix to all your files."); ?></td>
            </tr>
            <tr>
               <!-- regexwhere -->
               <td  class="text-right"><label for="regexwhere"><?php print $this->translate->_("RegexWhere"); ?></label> </td>
               <td  class="text-left"><?php echo $this->form->regexwhere; ?> </td>
               <td  class="text-left text-vcenter"><?php print $this->translate->_("Do complex filename manipulation like with sed unix command. Will overwrite other filename manipulation."); ?></td>
            </tr>
         </table>
         </div>
         <!-- END tabs-advanced-options -->      
      
      </div><!-- end div col-md-6 -->
      <!-- end role form -->   
   </div><!-- end div row -->
   </div><!-- end div container-fluid -->
   </div><!-- end div tab1 -->
   <!-- end tab1 Role -->


</div><!-- end div nav -->
</div><!-- end div tabcontent -->


<!-- From Bacula manuals main/Restore_Command.html -->
<div id="info_dialog" title="<?php echo $this->translate->_("Help"); ?>">

<h3>Using File Relocation</h3>
<p>For example, many users use OS snapshot features so that file
<tt>/home/eric/mbox</tt> will be backed up from the directory
<tt>/.snap/home/eric/mbox</tt>, which can complicate restores.  If you use
<b>where=/tmp</b>, the file will be restored to
<tt>/tmp/.snap/home/eric/mbox</tt> and you will have to move the file to
<tt>/home/eric/mbox.bkp</tt> by hand.

</p><p>
However, case, you could use the
<b>strip_prefix=/.snap</b> and <b>add_suffix=.bkp</b> options and
Bacula will restore the file to its original location - that is

<tt>/home/eric/mbox</tt>.


<h3>RegexWhere Format</h3>
<p>The format is very close to that used by sed or Perl (<tt>s/replace this/by that/</tt>) operator.
A valid regexwhere expression has three fields :
<ol>
    <li>a search expression (with optional submatch)</li>
    <li>a replacement expression (with optional back references $1 to $9)</li>
    <li>a set of search options (only case-insensitive 'i' at this time)</li>
</ol>
</p><p>Each field is delimited by a separator specified by the user as the first
character of the expression. The separator can be one of the following:
<pre>
  &lt;separator-keyword&gt; = / ! ; % : , ~ # = &amp;
</pre>
</p><P>You can use several expressions separated by a commas.<p>

<h3>Examples</h3>
<p>
<table border="1" cellpadding="3">
<thead>
    <th>Orignal filename</th>
    <th>New filename</th>
    <th>RegexWhere</th>
    <th>Comments</th>
</thead>
<tbody>
<tr>
<td class="text-center"><tt>c:/system.ini</tt></td>
<td class="text-center"><tt>c:/system.old.ini</tt></td>
<td class="text-center"><tt>/.ini$/.old.ini/</tt></td>
<td class="text-left">$ matches end of name</td>
</tr>
<tr>
<td class="text-center"><tt>/prod/u01/pdata/</tt></td>
<td class="text-center"><tt>/rect/u01/rdata</tt></td>
<td class="text-center"><tt>/prod/rect/,/pdata/rdata/</tt></td>
<td class="text-left">uses two regexp</td>
</tr>
<tr>
<td class="text-center"><tt>/prod/u01/pdata/</tt></td>
<td class="text-center"><tt>/rect/u01/rdata</tt></td>
<td class="text-center"><tt>!/prod/!/rect/!,/pdata/rdata/</tt></td>
<td class="text-left">use <tt>!</tt> as separator</td>
</tr>
<tr>
<td class="text-center"><tt>C:/WINNT</tt></td>
<td class="text-center"><tt>d:/WINNT</tt></td>
<td class="text-center"><tt>/c:/d:/i</tt></td>
<td class="text-left">case insensitive pattern match</td>
</tr>
</tbody></table>
</p>

</div>


<table>
   <tr>
      <td>
          <?php echo $this->form->submit_button; ?>
          </form>
      </td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td>
         <form method="<?php echo $this->escape($this->form->getMethod()); ?>"
               action="<?php echo $this->escape($this->form->getActionCancel()); ?>"
               name="formRestoreoptionsCancel" id="formRestoreoptionsCancel">
            <?php echo $this->form->cancel_button; ?>
         </form>
      </td>
   </tr>
</table>
<hr>
<!-- application/views/scripts/decorators/formRestoreoptions.phtml -->