<!-- decorators/formWebaculaACL.phtml -->
    <form  action="<?php echo $this->form_webacula->getAction();  ?>"
            method="<?php echo $this->form_webacula->getMethod();  ?>">
        <?php echo $this->form_webacula->role_id; ?>
        <?php echo $this->form_webacula->role_name; ?>
        <?php echo $this->form_webacula->action_id; ?>
        <?php echo $this->form_webacula->webacula_resources; ?>
        <?php echo $this->form_webacula->submit; ?>
        <?php echo $this->form_webacula->reset; ?>
    </form>
<!-- end decorators/formWebaculaACL.phtml -->