<!-- application/views/scripts/decorators/formJobrun.phtml -->
<form  action="<?php echo $this->escape($this->form->getAction()); ?>"
        method="<?php echo $this->escape($this->form->getMethod()); ?>"
        name="form1" id="form1">

<?php echo $this->form->from_form; ?>
<?php $this->translate = Zend_Registry::get('translate'); ?>

<table border="0" cellpadding="4" cellspacing="0" align="center" style="padding: 1em;">
<tr><td style="text-align: right;">
    <label for="jobname" class="ui-select"><b><?php echo $this->translate->_("Job Name"); ?></b></label>
</td><td>
    <?php echo $this->form->jobname;?>
</td></tr><tr><td style="text-align: right;">
    <label for="client" class="ui-select"><b><?php echo $this->translate->_("Client"); ?></b></label>
</td><td>
    <?php echo $this->form->client;?>
</td></tr><tr><td style="text-align: right;">
    <label for="fileset" class="ui-select"><b><?php echo $this->translate->_("Fileset"); ?></b></label>
</td><td>
    <?php echo $this->form->fileset;?>
</td></tr><tr><td style="text-align: right;">
    <label for="storage" class="ui-select"><b><?php echo $this->translate->_("Storage"); ?></b></label>
</td><td>
    <?php echo $this->form->storage;?>
</td></tr><tr><td style="text-align: right;">
    <label for="level" class="ui-select"><b><?php echo $this->translate->_("Level"); ?></b></label>
</td><td>
    <?php echo $this->form->level;?>
</td></tr><tr><td style="text-align: right;">
    <label for="spool" class="ui-select"><b><?php echo $this->translate->_("Spool"); ?></b></label>
</td><td>
    <?php echo $this->form->spool;?>
</td></tr><tr><td style="text-align: right;">
    <label for="date_when" class="ui-select"><b><?php echo $this->translate->_("When"); ?></b></label>
</td><td>
    <?php echo $this->translate->_("Now"); ?>
    <?php echo $this->form->checkbox_now;?>
    <br>
    <?php echo $this->form->date_when;?>
    <?php echo $this->form->time_when;?>
    <br>
    <div style="font-size:0.6em;"><?php echo $this->translate->_("YYYY-MM-DD HH:MM:SS"); ?></div>
</td></tr><tr><td colspan="2">
    <div style="text-align: center; margin-left: auto; margin-right: auto;">
        <?php echo $this->form->submit; ?>
    </div>
</td></tr>
</table>
</form>
