<!-- decorators/formRole.phtml -->
    <form  action="<?php echo $this->form_role->getAction();  ?>"
            method="<?php echo $this->form_role->getMethod();  ?>">
        <?php echo $this->form_role->role_id; ?>
        <?php echo $this->form_role->action_id; ?>
        <?php echo $this->form_role->order_role; ?>
        <?php echo $this->form_role->role_name; ?>
        <?php echo $this->form_role->description_role; ?>
        <?php echo $this->form_role->inherit_id; ?>
        <?php echo $this->form_role->submit; ?>
        <?php echo $this->form_role->reset; ?>
    </form>
<!-- end decorators/formRoleACL.phtml -->