<!-- decorators/formBaculaCommandACL.phtml -->
<form  action="<?php echo $this->form->getAction();  ?>"
       method="<?php echo $this->form->getMethod();  ?>">
    <?php echo $this->form->role_id; ?>
    <?php echo $this->form->role_name; ?>
    <?php echo $this->form->acl; ?>
    <?php echo $this->form->bacula_commands; ?>
    <?php echo $this->form->submit; ?>
    <?php echo $this->form->reset; ?>
</form>
<!-- end decorators/formBaculaCommandACL.phtml -->