<!-- decorators/formBaculaACL.phtml -->
<form  action="<?php echo $this->form->getAction(); ?>"
       method="<?php echo $this->form->getMethod(); ?>">
    <?php echo $this->form->role_id;   ?>
    <?php echo $this->form->role_name; ?>
    <?php echo $this->form->acl; ?>
    <?php echo $this->form->order; ?>
    <?php echo $this->form->name;  ?>
    <?php echo $this->form->id;    ?>

<table>
<tr>
<td>
    <?php echo $this->form->submit_button; ?>
</form>
</td>
<td>
<!-- end decorators/formBaculaACL.phtml -->
<form  action="<?php echo $this->form->getActionCancel();  ?>"
       method="<?php echo $this->form->getMethod();  ?>">
   <?php echo $this->form->cancel_button; ?>
</form>
</td>
</tr>
</table>
