
	<p>&nbsp;</p><p>&nbsp;</p>

<hr>
Copyright 2007, 2008, 2009 Yuri Timofeev <a href="mailto:tim4dev@gmail.com">tim4dev@gmail.com</a>

<IMG src="<?php echo $this->baseUrl; ?>/images/gplv3-127x51.png" alt="GPL3" width="127" height="51" hspace="15" vspace="15" align="left" border="0">

<p>This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.</p>

<p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.</p>

<p>You should have received a copy of the GNU General Public License along with this program.  If not, see <A href="http://www.gnu.org/licenses/" name="GPL3" target="_blank">http://www.gnu.org/licenses/</A>.</p>


<p>&nbsp;</p>
<div align="left">
<a href="http://framework.zend.com/" target="zfwindow"><img src="<?php echo $this->baseUrl; ?>/images/PoweredBy_ZF_4LightBG.png" border="0"></a>&nbsp;&nbsp;&nbsp;
<a href="http://jquery.com/" target="_blank"><img src="<?php echo $this->baseUrl; ?>/images/jquery_logo.png" border="0"></a>
</div>
</div>

