<!-- index_en.phtml -->
<img src="<?php echo $this->baseUrl; ?>/images/Webacula_logo.png">

<h1 style="color : #002244;">v<?php echo Zend_Registry::get('webacula_version'); ?></h1>
<p><strong>
<a href="http://webacula.sourceforge.net/" name="webacula" target="_blank">
Webacula</a>
</strong> - <strong>We</strong>b + <strong>Bacula</strong> -
web interface of a
<a href="http://www.bacula.org/" name="Bacula" target="_blank">Bacula backup system</a>.</p>

<p>&nbsp;</p>
<h1>Legend</h1>
<p>
<font  style="background-color : #ffff00;">Yellow color</font> - warnings.
</p>
<p>
<font  style="background-color : #ff0000; color : #ffffff;">Red color</font> - errors.
</p>
<p>&nbsp;</p>
<h1>Information</h1>
<p>
<ul>
    <li>DB Bacula : <?php echo $this->db_adapter_bacula, " ", $this->db_server_version_bacula; ?></li>
    <li>DB Webacula : <?php echo $this->db_adapter_webacula, " ", $this->db_server_version_webacula; ?></li>
    <li>Zend Framework : <?php echo $this->zend_version; ?></li>
    <li>Locale : <?php echo $this->locale; ?></li>
    <li><a href="<?php echo $this->baseUrl, '/help/my-php-info/' ?>" target="_blank">php info</a> (in separate window)</li>
    <li><a href="<?php echo $this->baseUrl, '/help/my-id/' ?>" target="_blank">id</a> (in separate window)</li>
</ul>