<!-- index_ru.phtml -->
<img src="<?php echo $this->baseUrl; ?>/images/Webacula_logo.png">

<h1 style="color : #002244;">v<?php echo Zend_Registry::get('webacula_version'); ?></h1>
<p><strong>
<a href="http://webacula.sourceforge.net/" name="webacula" target="_blank">
Webacula</a>
</strong> - <strong>We</strong>b + <strong>Bacula</strong> -
веб-интерфейс для
<a href="http://www.bacula.org/" name="Bacula" target="_blank">Bacula backup system</a>.</p>

<p>&nbsp;</p>
<h1>Условные обозначения</h1>
<p>
<font  style="background-color : #ffff00;">Желтый цвет</font> - предупреждения.
</p>
<p>
<font  style="background-color : #ff0000; color : #ffffff;">Красный цвет</font> - ошибки, сбои.
</p>
<p>&nbsp;</p>
<h1>Информация</h1>
<p>
<table id="box-table-one-column" border="0" width="100%">
    <colgroup><col class="col-first"></colgroup>
    <colgroup><col style="width: 30em;"></colgroup>
    <thead>
    </thead>
    <tbody>
<tr><td>БД Bacula </td><td> <?php echo $this->db_adapter_bacula, " ", $this->db_server_version_bacula; ?></td><tr>
<tr><td>Версия БД Каталога Bacula </td><td> <?php echo $this->catalog_version_bacula; ?></td><tr>
<tr><td>Директор Bacula </td><td> <?php echo $this->director_version; ?></td><tr>
<tr><td>Bconsole </td><td> <?php echo $this->bconsole_version; ?></td><tr>
<tr><td>БД Webacula </td><td> <?php echo $this->db_adapter_webacula, " ", $this->db_server_version_webacula; ?></td><tr>
<tr><td>Zend Framework </td><td> <?php echo $this->zend_version; ?></td><tr>
<tr><td>Locale </td><td> <?php echo $this->locale; ?></td><tr>
<tr><td>PHP info</td><td> <?php echo phpversion(); ?> (<a href="<?php echo $this->baseUrl, '/help/my-php-info/' ?>" target="_blank">в отдельном окне</a>)</td><tr>
<tr><td>id</td><td><?php system('id');?></td><tr>
    </tbody>
</table>