<!-- index_ru.phtml -->
<img src="<?php echo $this->baseUrl; ?>/images/Webacula_logo.png">

<h1 style="color : #002244;">v<?php echo Zend_Registry::get('webacula_version'); ?></h1>
<p><strong>
<a href="http://webacula.sourceforge.net/" name="webacula" target="_blank">
Webacula</a>
</strong> - <strong>We</strong>b + <strong>Bacula</strong> -
веб-интерфейс для
<a href="http://www.bacula.org/" name="Bacula" target="_blank">Bacula backup system</a>.</p>

<p>&nbsp;</p>
<h1>Условные обозначения</h1>
<p>
<font  style="background-color : #ffff00;">Желтый цвет</font> - предупреждения.
</p>
<p>
<font  style="background-color : #ff0000; color : #ffffff;">Красный цвет</font> - ошибки, сбои.
</p>
<p>&nbsp;</p>
<h1>Информация</h1>
<p>
<ul>
    <li>БД Bacula   : <?php echo $this->db_adapter_bacula, " ", $this->db_server_version_bacula; ?></li>
    <li>БД Webacula : <?php echo $this->db_adapter_webacula, " ", $this->db_server_version_webacula; ?></li>
    <li>Zend Framework : <?php echo $this->zend_version; ?></li>
    <li><a href="<?php echo $this->baseUrl, '/help/my-php-info/' ?>" target="_blank">php info</a> (в отдельном окне)</li>
    <li><a href="<?php echo $this->baseUrl, '/help/my-id/' ?>" target="_blank">id</a> (в отдельном окне)</li>
</ul>