<!-- file/list.phtml -->
<div class="rows">
   <div class="col-md-12">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->titleFile); ?>
         </div>
         <div class="panel-body">
            <p>
            
            <?php if (count($this->paginator)): ?>
            <?php $decode = new MyClass_HomebrewBase64; ?>
            
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                           <th colspan="4"> <?php print $this->translate->_("Attribute"); ?></th>
                           <th> <?php print $this->translate->_("Name File"); ?></th>
                           <th> <?php print $this->translate->_("File Id"); ?> </th>
                           <th class="text-center"> <?php print $this->translate->_("Status"); ?></th>
                        </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->paginator as $line): ?>
                        <tr>
                        <?php
                        	// LStat example:
                        	// MI OfON IGk B Bk Bl A e BAA I BGkZWg BGkZWg BGkZWg A A E
                        	list($st_dev, $st_ino, $st_mode, $st_nlink, $st_uid, $st_gid, $st_rdev, $st_size, $st_blksize,
                        		$st_blocks, $st_atime, $st_mtime, $st_ctime) = preg_split("/[\s]+/", $line['lstat']);
                        
                        	if ( $decode->homebrewBase64($st_dev) == 0 ){
                        		// OS : windows
                        		echo '<td>' , date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)) , '</td><td>' ,
                        			$this->convBytes($decode->homebrewBase64($st_size)) , '</td>',
                        			'<td></td><td></td>';
                        	}
                        	else {
                        		// OS : linux/unix
                        		echo '<td>' , $this->permissionOctal2String(($decode->homebrewBase64($st_mode))), '</td><td>' ,
                        			$decode->homebrewBase64($st_uid), " &nbsp;",  $decode->homebrewBase64($st_gid),'</td><td>',
                        			date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)),'</td><td>',
                        			$this->convBytes($decode->homebrewBase64($st_size)), '</td>';
                        	}
                        ?>
                        
                        	<td><?php echo $this->escape($line['path'] . $line['name']);?></td>
                        	<td>&nbsp; <?php echo $this->escape($line['fileid']) ?> &nbsp;</td>
                        	<td class="text-center"> &nbsp; <?php echo $this->escape($this->translate->_($line['status'])) ?> &nbsp;</td>
                        </tr>
                     <?php endforeach; ?>
                     <?php 
                         // only to keep translation in file .po
                         $deleted = $this->translate->_('deleted'); 
                     ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
               
               <!-- start paginationControl -->
               <?php echo $this->paginationControl($this->paginator, 'Sliding', 'file/list_pagination_ctrl.phtml'); ?>
               <!-- end paginationControl -->
               
               <?php else: ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                  <span class="glyphicon glyphicon-alert"></span>
                  <?php print $this->translate->_("No Files found.");; ?>
                  </p>
               </div>
               <!-- end div alert -->
            
            <?php endif; ?>
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-12 -->
</div><!-- end div rows -->
<!-- end file/list.phtml -->
