<!-- views/scripts/wbjobdesc/add.phtml -->
<div class="rows">
   <div class="col-md-6">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
      	 <div class="panel-body">
            <p>
               <?php if ( !empty($this->exception) ) : ?>         
                  <div class="alert alert-warning">
                    <p>
                    <span class="glyphicon glyphicon-info-sign"></span>
                    <?php print $this->exception; ?>
                    </p>
                  </div>
               <?php else: ?>

               <fieldset>
                   <!--<legend><?php echo $this->title; ?></legend>-->
                    <?php
                    $this->form->setAction( $this->url() );
                    $this->form->setActionCancel( $this->view->baseUrl .'/wbjobdesc/index' );
                    echo $this->form;
                    ?>
               </fieldset>
<?php endif;?>
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-6 -->
</div><!-- end div row -->
<!-- end views/scripts/wbjobdesc/add.phtml -->














<!--
<div class="roundcorner-wjd">
<div id="jobdesc-form">

<?php if ( !empty($this->exception) ) : ?>
<div class="ui-widget">
    <div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;">
        <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
        <strong><?php echo $this->exception; ?></strong></p>
    </div>
</div>
<br>

<?php endif;?>

<fieldset>
    <legend><?php echo $this->title; ?></legend>
<?php
$this->form->setAction( $this->url() );
echo $this->form;
?>
</fieldset>
</div>
</div>-->
