<!-- wbjobdesc/index.phtml -->

<script type="text/javascript">
$(document).ready(
    function() {
	$('a.confirm').click(function(e) {
		var targetUrl = $(this).attr("href");
		
		$('#dialog-confirm').dialog({
           buttons : {
                  <?php echo $this->translate->_('Yes'); ?> : function() {
                    window.location.href = targetUrl;
                  },
                  <?php echo $this->translate->_('No'); ?> : function() {
                    $(this).dialog("close");
                  }
                }		
		});
		e.preventDefault();
	});
  
});
</script>
<h1><?php echo $this->escape($this->title); ?></h1>

<div id="dialog-confirm" title="<?php echo $this->translate->_("Message"); ?>" style="display:none">
  <p><span class="ui-icon ui-icon-alert"></span><?php echo $this->translate->_("Are you sure you want to delete the jobdesc?"); ?></p>
</div>

<div style="width: 200px; margin-top: 30px; margin-bottom: 20px;">
<form method="POST" action="<?php echo $this->baseUrl ?>/wbjobdesc/add">
    <input type="submit" name="name1" value="<?php echo $this->translate->_("+ Add New Record"); ?>" class="ui-button ui-widget ui-corner-all">
</form>
</div>

<?php if ($this->result): ?>

<table id="box-table">
<thead>
<tr>
    <th scope="col">&nbsp;</th>
    <th scope="col" width="20%"> <?php echo $this->translate->_("Job Name"); ?> </th>
    <th scope="col"> <?php echo $this->translate->_("Short Job Description"); ?> </th>
	<th scope="col"> <?php echo $this->translate->_("Job Description"); ?> </th>
    <th scope="col"> <?php echo $this->translate->_("Retention period"); ?> </th>
    
    <th scope="col" width="50px">&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach($this->result as $line) : ?>
<tr>
    
	<td style="padding: 0px;">
        <?php

            if ( isset($line['name_job']) && ($line['exists'] == 1) )    {
                // re-run button
                echo '<a href="';
                echo $this->baseUrl, '/job/run-job/jobname/', $this->escape($line['name_job']);
                echo '" title="', $this->translate->_("Run Job"), '">';
                echo '<img src="', $this->baseUrl, '/images/re-run-job.png" alt="', $this->translate->_("Run Job"), '">';
            } else {
                echo '<span class="ui-icon ui-icon-alert"></span>';
            }
        ?>
    </td>
    <td>
        <a href="<?php echo $this->baseUrl . "/job/show-job/jobname/" . $this->escape($line['name_job']);?>" title="<?php echo $this->translate->_("Show Job resource") ?>"> 
            <?php echo $line['name_job'] ?>
        </a>
    </td>
    <td><?php echo $line['short_desc'] ?></td>
    <td><?php echo $line['description'] ?></td>
    <td><?php echo $line['retention_period'] ?></td>
    <td>
        <a href="<?php echo $this->baseUrl ?>/wbjobdesc/modify/desc_id/<?php echo $line['desc_id'] ?>" title="<?php echo $this->translate->_("Modify record") ?>">
           <img src="<?php echo $this->baseUrl ?>/images/document-edit.png" alt="<?php echo $this->translate->_("Modify record") ?>">
		</a>
		<a href="<?php echo $this->baseUrl ?>/wbjobdesc/delete/desc_id/<?php echo $line['desc_id'] ?>" title="<?php echo $this->translate->_("Delete record") ?>" class="confirm">
        <img src="<?php echo $this->baseUrl ?>/images/edit-delete.png" alt="<?php echo $this->translate->_("Delete record") ?>">
		</a>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<?php else: ?>
<div class="ui-widget" style="width: 40%; margin-left: auto; margin-right: auto;">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("No records found."); ?></strong></p>
	</div>
</div>
<?php endif; ?>
