<!-- wbjobdesc/index.phtml -->
<script type="text/javascript">
$(document).ready(function() {
   $('a.confirm').click(function(e){
      var targetUrl = $(this).attr("href");
      $('#dialog-confirm').dialog({
           modal: true,
           buttons : [
              {  
               'text' : '<?php echo $this->translate->_('Yes'); ?>',
               'class' : 'btn btn-default',
               'width' : '75px',
               click: function(){ window.location.href = targetUrl; }
              },
              {
               'text' : '   <?php echo $this->translate->_('No'); ?>   ',
               'class' : 'btn btn-default',
               'width' : '75px',
               click: function(){ $(this).dialog("close"); }
              }  
           ],
           open: function(event){
              $('.ui-dialog-buttonpane').find('button').removeClass('ui-button ui-corner-all ui-widget');
           }
      });
      e.preventDefault();
   });
});
</script>

<!-- dialog confirm -->
<div id="dialog-confirm" title="<?php echo $this->translate->_("Message"); ?>" style="display:none">
  <p><span class="ui-icon ui-icon-alert"></span><?php echo $this->translate->_("Are you sure you want to delete the jobdesc?"); ?></p>
</div>
<!-- end dialog confirm -->

<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
               
            <?php if ($this->result): ?>
            
            <div class="table-responsive">
               <table class="table table-striped table-hover table-condensed">
                  <thead>
                     <tr>
                        <th>&nbsp;</th>
                        <th> <?php echo $this->translate->_("Job Name"); ?> </th>
                        <th> <?php echo $this->translate->_("Short Job Description"); ?> </th>
                        <th> <?php echo $this->translate->_("Job Description"); ?> </th>
                        <th> <?php echo $this->translate->_("Retention period"); ?> </th>
                        <th>&nbsp;</th>
                     </tr>
                  </thead>
                  <tbody>
                  <?php foreach($this->result as $line) : ?>
                     <tr>
                        <td>
                        <?php
                            if ( isset($line['name_job']) && ($line['exists'] == 1) ){
                                // re-run button
                                echo '<a href="';
                                echo $this->baseUrl, '/job/run-job/jobname/', $this->escape($line['name_job']);
                                echo '" title="', $this->translate->_("Run Job"), '">';
                                echo '<img src="', $this->baseUrl, '/images/re-run-job.png" alt="', $this->translate->_("Run Job"), '" border="0" hspace="2">';
                            } else {
                                echo '<span class="glyphicon glyphicon-alert"></span>';
                            }
                        ?>
                        </td>
                        <td>
                        <?php
                           if ( isset($line['name_job']) && ($line['exists'] == 1) ){
                              echo '<a href="' , $this->baseUrl , '/job/show-job/jobname/' , $this->escape($line['name_job']) , '" title="' , $this->translate->_("Show Job resource") , '">';
                              echo $line['name_job'] . '</a>';
                           } else {
                              echo $line['name_job'];
                           }
                        ?>
                        </td>
                        <td><?php echo $line['short_desc'] ?></td>
                        <td><?php echo $line['description'] ?></td>
                        <td><?php echo $line['retention_period'] ?></td>
                        <td>
                           <a href="<?php echo $this->baseUrl ?>/wbjobdesc/modify/desc_id/<?php echo $line['desc_id'] ?>" title="<?php echo $this->translate->_("Modify record") ?>">
                           <img src="<?php echo $this->baseUrl ?>/images/document-edit.png" alt="<?php echo $this->translate->_("Modify record") ?>" border="0" hspace="2">
                           </a>
                     
                           <a href="<?php echo $this->baseUrl ?>/wbjobdesc/delete/desc_id/<?php echo $line['desc_id'] ?>" title="<?php echo $this->translate->_("Delete record") ?>" id="confirm" class="confirm">
                               <img src="<?php echo $this->baseUrl ?>/images/edit-delete.png" alt="<?php echo $this->translate->_("Delete record") ?>" border="0" hspace="2">
                           </a>
                        </td>
                     </tr>
                  <?php endforeach; ?>
                  </tbody>
               </table>
            </div><!-- end div table-responsive -->

            
            <?php else: ?>
            
            <!-- div alert -->
            <div class="alert alert-danger">
               <p>
               <span class="glyphicon glyphicon-alert"></span>
               <?php print $this->translate->_("No records found!"); ?>
               </p>
            </div>
            <!-- end div alert -->
            
            <?php endif; ?>
            
            <div>
               <form method="POST" action="<?php echo $this->baseUrl ?>/wbjobdesc/add">
                   <input type="submit" name="name1" value="<?php echo $this->translate->_("Add New Record"); ?>" class="btn btn-default">
               </form>
               <br />
            </div>               
               
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-8 -->
</div><!-- end div rows -->
<!-- wbjobdesc/index.phtml -->