<!-- views/scripts/wbjobdesc/modify.phtml -->
<style>
  .select-overflow { height: auto; max-height: 200px;}
</style>
<script type="text/javascript">
  // select
  $(function(){
      $('select').each(function() {
//          var t = $(this).selectmenu().selectmenu("menuWidget").addClass("select-overflow");
//          eval(t);
          $(this).selectmenu().selectmenu("menuWidget").addClass("select-overflow");
      });
  });
</script>
<div class="roundcorner-wjd">
<div id="jobdesc-form">

<?php if ( !empty($this->exception) ) : ?>
<div class="ui-widget">
    <div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;">
        <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
        <strong><?php echo $this->exception; ?></strong></p>
    </div>
</div>
<br>
<?php endif;?>

<fieldset>
    <legend><?php echo $this->title; ?></legend>
<?php
$this->form->setAction( $this->url() );
$this->form->setActionCancel( $this->view->baseUrl .'/wbjobdesc/index' );
echo $this->form;
?>
</fieldset>
</div>
</div>