<!-- wbjobdesc/modify.phtml -->
<div class="rows">
   <div class="col-md-6">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
      	 <div class="panel-body">
            <p>
               <?php if ( !empty($this->exception) ) : ?>

                  <div class="alert alert-danger">
                    <p>
                    <span class="glyphicon glyphicon-alert"></span>
                    <?php print $this->exception; ?>
                    </p>
                  </div>

               <?php else: ?>

                  <form  action="<?php echo $this->form->getAction();  ?>"
                         method="<?php echo $this->form->getMethod();  ?>" >
                    <?php echo $this->form->desc_id; ?>
                    <?php echo $this->form->form1; ?>
                    <?php echo $this->form->name_job; ?>
                    <br/>
                    <?php echo $this->form->short_desc; ?>
                    <br/>
                    <?php echo $this->form->description; ?>
                    <br/>
                    <?php echo $this->form->retention_period; ?>
                    <br/>
                    <table>
                       <tr>
                          <td>
                              <?php echo $this->form->submit_button; ?>
                          </form>
                          </td>
                          <td>&nbsp;&nbsp;&nbsp;</td>
                          <td>
                          <form  action="<?php echo $this->form->getActionCancel();  ?>"
                                 method="<?php echo $this->form->getMethod();  ?>">
                             <?php echo $this->form->cancel_button; ?>
                          </form>
                          </td>
                       </tr>
                    </table>

               <?php endif;?>

            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-6 -->
</div><!-- end div row -->
<!-- end wbjobdesc/modify.phtml -->
