#!/bin/sh
#
# Script to drop Webacula ACLs tables in Bacula database
#

if mysql -u root bacula -f <<END-OF-DATA

DROP TABLE webacula_users;
DROP TABLE webacula_roles;
DROP TABLE webacula_resources;
DROP TABLE webacula_dt_resources;
DROP TABLE webacula_storage_acl;
DROP TABLE webacula_pool_acl;
DROP TABLE webacula_command_acl;
DROP TABLE webacula_dt_commands;
DROP TABLE webacula_client_acl;
DROP TABLE webacula_fileset_acl;
DROP TABLE webacula_where_acl;
DROP TABLE webacula_job_acl;


END-OF-DATA
then
   echo "Succeeded."
else
   echo "Failed."
fi
exit 0
