#!/bin/sh

echo Refresh Bacula Job table...

mysql -u root bacula  -f <<END-OF-DATA
update Job set SchedTime=now();
END-OF-DATA

echo .
sleep 70

mysql -u root bacula  -f <<END-OF-DATA
update Job set StartTime=now();
END-OF-DATA

echo .
sleep 70

mysql -u root bacula  -f <<END-OF-DATA
update Job set EndTime=now();
update Job set RealEndTime=now();
END-OF-DATA

echo End
