<!-- restorejob/list-restore.phtml -->
<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>

               <?php $decode = new MyClass_HomebrewBase64; ?>
               <?php if ($this->result): ?>
               
               <?php
                   echo "<b>", $this->translate->_("Total"), ": ", $this->total_rows,
                       " ", $this->translate->_("file(s)"), ", ", $this->convBytes($this->total_size), "</b>" ;
               ?>
               
                   <?php if ( !empty($this->msgNoValid) ) : ?>
                   
                  <!-- div alert -->
                  <div class="alert alert-danger">
                     <p>
                     <span class="glyphicon glyphicon-alert"></span>
                     <?php print $this->msgNoValid; ?>
                     </p>
                  </div>
                  <!-- end div alert -->                   
                   
                   <?php endif;?>
               
               <?php echo $this->form;?>
               <br/>    
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                     <tr>
                        <th class="text-left" colspan="4"> <?php print $this->translate->_("Attribute"); ?> </th>
                        <th class="text-left"> <?php print $this->translate->_("Name File"); ?> </th>
                        <th class="text-center"> <?php print $this->translate->_("File Id"); ?> </th>
                     </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->result as $line) : ?>
                        <tr>
                        <?php
                           // LStat example:
                           // MI OfON IGk B Bk Bl A e BAA I BGkZWg BGkZWg BGkZWg A A E
                           list($st_dev, $st_ino, $st_mode, $st_nlink, $st_uid, $st_gid, $st_rdev, $st_size, $st_blksize,
                              $st_blocks, $st_atime, $st_mtime, $st_ctime) = preg_split("/[\s]+/", $line['lstat']);
                        
                           if ( $decode->homebrewBase64($st_dev) == 0 )     {
                              // OS : windows
                              echo '<td>' , date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)) , '</td><td>' ,
                                 $this->convBytes($decode->homebrewBase64($st_size)) , '</td>',
                                 '<td></td><td></td>';
                           }
                           else {
                              // OS : linux/unix
                              echo '<td>' , $this->permissionOctal2String(($decode->homebrewBase64($st_mode))), '</td><td>' ,
                                 $decode->homebrewBase64($st_uid), " &nbsp;",  $decode->homebrewBase64($st_gid),'</td><td>',
                                 date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)),'</td><td>',
                                 $this->convBytes($decode->homebrewBase64($st_size)), '</td>';
                           }
                        ?>
                           </td>
                           <td class="text-left"><?php echo $this->escape($line['path'] . $line['name']);?>
                           <td class="text-center"><?php echo $this->escape($line['fileid']) ?></td>
                           </td>
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->

               <div>
                  <ul class="pagination">
                  <?php
                  // pager
                  if ( $this->total_pages > 1 )   {
                     // Make links
                     for( $i = 1 ; $i <= $this->total_pages ; $i++ ) {
                        if ( $i == $this->current_page ){
                           echo '<li class="page-item active"><a href="' . $this->baseUrl .'/restorejob/list-restore/page/' . $i . '">' . $i . "</a></li>";
                        } else {
                           echo '<li class="page-item"><a href="' . $this->baseUrl .'/restorejob/list-restore/page/' . $i . '">' . $i . "</a></li>";
                        }
                     }
                  }
                  ?>
                  </ul>
               </div>
               
               <?php else: ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                  <span class="glyphicon glyphicon-alert"></span>
                  <?php print $this->translate->_("No Files found."); ?>
                  </p>
               </div>
               <!-- end div alert -->
               
               <?php endif; ?>

            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-12 -->
</div><!-- end div rows -->
<!-- end file/list.phtml -->