<!-- restorejob/msg01.phtml -->

<script type="text/javascript">
$(document).ready(function() {
	$('#ok1').click(function() {
    	$.blockUI({
        	message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
        	css: { backgroundColor: '#f3fcf2' },
        	centerX: true,
        	centerY: true
        });
    });
});
</script>

<h1><?php echo $this->escape($this->title . ' ' . $this->jobid); ?></h1>

<div class="ui-state-error ui-corner-all" style="width: 42em; text-align: left;">

<form action="<?php  echo $this->baseUrl.'/restorejob/old-tmp-table';?>" method="post" style="margin: 2em;">
<p><?php print $this->translate->_("Found existing temporary tables for the Restore Job with JobId"); ?>
    <?php echo $this->jobid; ?>.</p>
<p>
<?php print $this->translate->_("Probably someone already works above a choice of files for restoration, or these tables have not been removed since time of your last task for restoration for this JobId."); ?>
</p>
<p><b><?php print $this->translate->_("Choose the action:"); ?> </b></p>

<?php echo $this->formRadio('choice', 'recreate_tmp', null,
    array(
        'recreate_tmp'  => $this->translate->_('Recreate temporary tables (recommended)'),
	    'continue_tmp'  => $this->translate->_('Continue with the old temporary tables'),
		'goto_homepage' => $this->translate->_('Exit')
    ));
?>
    <div style="text-align: center; margin: 5px;">
		<br /><br /><?php echo $this->formSubmit('ok1', 'OK'); ?>
	</div>
</form>

</div>