<!-- restorejob/msg02session.phtml -->
<div class="ui-widget" style="width: 30%; margin-top: 3em;">
    <div class="ui-state-highlight ui-corner-all">
        <p class="dashboard"><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
        <?php
            print $this->translate->_("Session of Restore backup is expired.<br />Increase <b>ttl_restore_session</b> in your config.ini.");
        ?>
        </p>
    </div>
    <div align="center" style="margin-top: 1em;">
        <form action="<?php  echo $this->baseUrl.'/restorejob/main-form';?>" method="post">
            <?php echo $this->formSubmit('ok1', 'OK'); ?>
        </form>
    </div>
</div>