<!-- restorejob/restore-recent-all.phtml -->

<h1><?php echo $this->escape($this->title), ' ', $this->client_from_restore, ' ', $this->fileset_restore; ?></h1>

<?php if ( !empty($this->msgNoValid) ) : ?>
<div class="ui-widget" style="float: left;">
	<div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;">
		<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php echo $this->msgNoValid; ?></strong></p>
	</div>
</div>
<div style="clear: both;"><!--  --></div>
<?php endif;?>

<?php echo $this->form;?>
<br style="clear: both;" />