<!-- restore-all.phtml -->

<script type="text/javascript">
$(document).ready(function() {
	$('#ok1').click(function() {
    	$.blockUI({
        	message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
        	css: { backgroundColor: '#f3fcf2' },
        	centerX: true,
        	centerY: true
        });
    });
});
</script>

<script type="text/javascript">
  // select
  $(function(){
      $('select').each(function() {
          var t = $(this).selectmenu({maxHeight: 300});
          eval(t);
      });
  });
</script>

<h1 align="center"><?php echo $this->escape($this->title), ' '; ?>
<a href="<?php echo $this->baseUrl; ?>/job/detail/jobid/<?php echo $this->escape($this->jobid); ?>">
    <?php echo $this->escape($this->jobid); ?>
<a/></h1>



<?php
    $this->form->setAction( $this->baseUrl .'/restorejob/restore-all' );
    $this->form->setActionCancel( $this->baseUrl .'/restorejob/cancel-restore' );
    echo $this->form;
?>
<br style="clear: both;" />
