<!-- restore-recent-all.phtml -->

<script type="text/javascript">
$j(document).ready(function() {
	$j('#ok').click(function() { 
    	$j.blockUI({ 
        	message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
        	css: { backgroundColor: '#f3fcf2' },
        	centerX: true,
        	centerY: true 
        }); 
    }); 
});
</script>

<h1 align="center"><?php echo $this->escape($this->title), ' ', $this->client_from_restore, ', ', $this->fileset_restore; ?></h1>

<?php
    // create array clients for Form
    foreach($this->clients as $client) {
	   $aclients[$this->escape($client->name)] = $this->escape($client->name);
    }
?>

<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/default/roundcorner1.css" />

<div class="roundedcornr_box_1" style="width: 680px; margin-left: auto; margin-right: auto; text-align: left;">
   <div class="roundedcornr_top_1"><div></div></div>
      <div class="roundedcornr_content_1">

<div style="text-align: left; padding: 10px; border-width: 1px;">
<form method="POST" action="<?php echo $this->baseUrl .'/restorejob/restore-recent-all'; ?>">
   <p><b><?php print $this->translate->_("Where to Restore"); ?> :</b></p>
   <?php print $this->translate->_("Client"); ?>&nbsp;:&nbsp;
   <?php echo $this->formSelect('client_to_restore', $this->client_name, null, $aclients) ?>&nbsp;&nbsp;<br>
   <?php print $this->translate->_("Path"); ?> : <?php echo $this->formText('path_to_restore', '', array('size' => 50)) ?>
   
	<input type="hidden" name="client_from_restore" id="client_from_restore" value="<?php echo $this->client_from_restore; ?>">
	<input type="hidden" name="fileset_restore"     id="fileset_restore"     value="<?php echo $this->fileset_restore; ?>">
	<input type="hidden" name="date_before"         id="date_before"         value="<?php echo $this->date_before; ?>">
    <input type="hidden" name="choice_form" id="choice_form"  value="1">

	<span onclick="progressbar()">&nbsp;</span>
<table border="0" align="center" cellpadding="10px" cellspacing="10px">
	<tr>	
<td>    
    <?php echo $this->formSubmit('ok', $this->translate->_('Run Restore Job'), array('class' => 'prefer_btn') );	?>
</form>
</td><td>
<form method="POST" action="<?php echo $this->baseUrl .'/restorejob/cancel-restore-recent'; ?>">
	<input type="hidden" name="choice_form" id="choice_form"  value="1">
	<?php echo $this->formSubmit('cancel1', $this->translate->_('Cancel') ); ?>
</form>
</td>
</tr>
</table>   
</div>

</div>
   <div class="roundedcornr_bottom_1"><div></div></div>
</div>