<!-- restore-all.phtml -->

<script type="text/javascript">
$j(document).ready(function() {
	$j('#ok1').click(function() {
    	$j.blockUI({
        	message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>',
        	css: { backgroundColor: '#f3fcf2' },
        	centerX: true,
        	centerY: true
        });
    });
});
</script>

<script type="text/javascript">
  // select
  $j(function(){
      $j('select').each(function() {
          var t = $j(this).selectmenu({maxHeight: 300});
          eval(t);
      });
  });
</script>

<h1 align="center"><?php echo $this->escape($this->title), ' '; ?>
<a href="<?php echo $this->baseUrl; ?>/job/detail/jobid/<?php echo $this->escape($this->jobid); ?>">
    <?php echo $this->escape($this->jobid); ?>
<a/></h1>

<?php
    // create array clients for Form
    foreach($this->clients as $client) :
	   $aclients[$this->escape($client->name)] = $this->escape($client->name);
    endforeach;

    // create array filesets for Form
    $afilesets[''] = 'default'; // do not for translate. не переводить
    foreach($this->filesets as $fileset) :
	   $afilesets[$this->escape($fileset->fileset)] = $this->escape($fileset->fileset);
    endforeach;
    $afilesets[''] = 'default';	// if empty FileSet exists in database. do not for translate

    // create array storages for Form  // do not for translate. не переводить
    $astorages[''] = 'default'; // значение не менять! используется далее в runRestoreAction()
    foreach($this->storages as $storage) :
	   $astorages[$this->escape($storage->name)] = $this->escape($storage->name);
    endforeach;
                                // do not for translate. не переводить
    $astorages[''] = 'default';	// if empty FileSet exists in database  // значение не менять! используется далее в runRestoreAction()

    // create array pools for Form
    $apools[''] = 'default';
    foreach($this->pools as $pool) :
	   $apools[$this->escape($pool->name)] = $this->escape($pool->name);
    endforeach;
                                // do not for translate. не переводить
    $apools[''] = 'default';	// if empty FileSet exists in database
?>

<div class="roundcorner1" style="width: 54em;">

<form method="POST" action="<?php echo $this->baseUrl .'/restorejob/restore-all'; ?>">
<table border="0" cellpadding="4" cellspacing="0" align="center" width="100%">
<tr>
    <td align="right" class="search1">
        <label for="client" class="ui-select"><b><?php print $this->translate->_("Client"); ?></b></label>
    </td>
   	<td class="search1" align="left">
       	<?php echo $this->formSelect('client', $this->client_name, array('class' => 'ui-select', 'style' => 'width: 18em;'), $aclients) ?>
    </td>

    <td align="right" class="search1">
        <label for="pool" class="ui-select"><?php print $this->translate->_("Pool"); ?></label>
    </td>
   	<td align="left" class="search1">
       	<?php echo $this->formSelect('pool', null, array('class' => 'ui-select', 'style' => 'width: 18em;'), $apools) ?>
    </td>
</tr>
<tr>
    <td align="right" class="search1" valign="top"><?php print $this->translate->_("Where"); ?></td>
    <td align="left" class="search1" valign="top"><?php echo $this->formText('where', '', array('size' => 30)) ?></td>

    <td align="right" class="search1">
        <label for="fileset" class="ui-select"><?php print $this->translate->_("Fileset"); ?></label>
    </td>
    <td align="left" class="search1">
        <?php echo $this->formSelect('fileset', null, array('class' => 'ui-select', 'style' => 'width: 18em;'), $afilesets) ?>
    </td>
</tr>
<tr>
    <td align="right" class="search1" colspan="2">&nbsp;</td>

    <td align="right" class="search1">
        <label for="storage" class="ui-select"><?php print $this->translate->_("Storage"); ?></label>
     </td>
   	<td align="left" class="search1">
       	<?php echo $this->formSelect('storage', null, array('class' => 'ui-select', 'style' => 'width: 18em;'), $astorages) ?>
    </td>
</tr>
<tr>
    <td class="search1" colspan="2" align="center">
            <input type="hidden" name="jobid"  id="jobid"  value="<?php echo $this->jobid; ?>">
            <input type="hidden" name="client_name"  id="client_name"  value="<?php echo $this->client_name; ?>">
            <input type="hidden" name="choice_form"  id="choice_form"  value="1">
		    <?php echo $this->formSubmit('ok1', $this->translate->_('Run Restore Job'), array('class' => 'prefer_btn') ); ?>
        </form>
    </td>
    <td class="search1" colspan="2" align="center">
        <form method="POST" action="<?php echo $this->baseUrl .'/restorejob/cancel-restore'; ?>">
            <input type="hidden" name="jobid"  id="jobid"  value="<?php echo $this->jobid; ?>">
            <?php echo $this->formSubmit('cancel1', $this->translate->_('Cancel') ); ?>
        </form>
    </td>
</tr>
</table>

</div>
