<!-- restorejob/restore-single-file.phtml -->
<script type="text/javascript">
$(document).ready(function() {
   $('#ok1').click(function() {
      $.blockUI({
         message: '<h4><?php print $this->translate->_("Please wait"); ?>...</h4>',
         css: {border: 'none', padding: '15px',  backgroundColor: '#000',  '-webkit-border-radius': '10px', '-moz-border-radius': '10px', opacity: .5,  color: '#fff' }
        });
    });
});
</script>

<script type="text/javascript">
  // select
  $(function(){
      $('select').each(function(){
         $(this).addClass("select-overflow").addClass("form-control");
      });
  });
</script>

<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               <?php if ($this->file): ?>
               <?php echo $this->form;?>
               
               <?php $decode = new MyClass_HomebrewBase64; ?>
               <br/>
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                     <tr>
                        <th class="text-left" colspan="4"> <?php print $this->translate->_("Attribute"); ?></th>
                        <th class="text-left"><?php print $this->translate->_("Name File"); ?></th>
                        <th class="text-center"><?php print $this->translate->_("File Id"); ?></th>
                        <th class="text-center"><?php print $this->translate->_("Job Id"); ?></th>
                     </tr>
                     </thead>
                     <tbody>
                        <tr>
                        <?php
                           // LStat example:
                           // MI OfON IGk B Bk Bl A e BAA I BGkZWg BGkZWg BGkZWg A A E
                           list($st_dev, $st_ino, $st_mode, $st_nlink, $st_uid, $st_gid, $st_rdev, $st_size, $st_blksize,
                              $st_blocks, $st_atime, $st_mtime, $st_ctime) = preg_split("/[\s]+/", $this->file[0]['lstat']);
                        
                           if ( $decode->homebrewBase64($st_dev) == 0 )     {
                              // OS : windows
                              echo '<td>' , date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)) , '</td><td>' ,
                                 $this->convBytes($decode->homebrewBase64($st_size)) , '</td>',
                                 '<td></td><td></td>';
                           }
                           else {
                              // OS : linux/unix
                              echo '<td>' , $this->permissionOctal2String(($decode->homebrewBase64($st_mode))), '</td><td>' ,
                                 $decode->homebrewBase64($st_uid), "&nbsp;",  $decode->homebrewBase64($st_gid),'</td><td>',
                                 date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)),'</td><td>',
                                 $this->convBytes($decode->homebrewBase64($st_size)), '</td>';
                           }
                        ?>
                           </td>
                           <td class="text-left"><?php echo $this->escape($this->file[0]['path'] . $this->file[0]['filename']);?>
                           <td class="text-center"><?php echo $this->escape($this->file[0]['fileid']) ?></td>
                           <td class="text-center"><?php echo $this->escape($this->file[0]['jobid']) ?></td>
                           </td>
                        </tr>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
               <?php else: ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                  <span class="glyphicon glyphicon-alert"></span>
                  <?php print $this->translate->_("No Files found."); ?>
                  </p>
               </div>
               <!-- end div alert -->
               
               <?php endif; ?>

            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-12 -->
</div><!-- end div rows -->
<!-- restorejob/restore-single-file.phtml -->