<!-- restorejob/restore-all.phtml -->
<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
            <a href="<?php echo $this->baseUrl, '/job/detail/jobid/', $this->escape($this->jobid); ?>">
                <?php echo $this->escape($this->jobid); ?>
            </a>
         </div>
         <div class="panel-body">
            <p>
               <?php if ( !empty($this->msgNoValid) ) : ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                  <p>
                  <span class="glyphicon glyphicon-alert"></span>
                  <?php print $this->msgNoValid; ?>
                  </p>
               </div>
               <!-- end div alert -->
               
               <?php endif;?>
               
               <?php echo $this->form; ?>

            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-12 -->
</div><!-- end div rows -->
<!-- end file/list.phtml -->
<!-- restorejob/restore-all.phtml -->