<!-- single-file-restore.phtml -->

<script type="text/javascript">
$(document).ready(function() {
	$('#ok1').click(function() {
    	$.blockUI({
        	message: '<h2><?php print $this->translate->_("Please wait"); ?>...</h2>'
        });
    });
});
</script>

<script type="text/javascript">
  // select
  $(function(){
      $('select').each(function() {
          var t = $(this).selectmenu({maxHeight: 300});
          eval(t);
      });
  });
</script>

<h1 align="center"><?php echo $this->escape($this->title); ?></h1>

<?php if ($this->file): ?>

<?php
    // create array clients for Form
    $aclients[''] = 'default';
    foreach($this->clients as $client) :
        $aclients[$this->escape($client->name)] = $this->escape($client->name);
    endforeach;
?>


<div class="roundcorner1" style="width: 50em;">

<form method="POST" action="<?php echo $this->baseUrl .'/restorejob/run-restore-single-file';?>">
<?php echo $this->formHidden('fileid', $this->escape($this->file[0]['fileid']), null); ?>
<table border="0" cellpadding="4" cellspacing="0" align="center" width="100%">
<tr>
    <td align="right" class="search1">
        <label for="client_name_to" class="ui-select"><?php print $this->translate->_("Client"); ?>
            (<?php print $this->translate->_("Where"); ?>)</label>
    </td>
   	<td class="search1" align="left">
       	<?php echo $this->formSelect('client_name_to', $this->client_name_to, array('class' => 'ui-select', 'style' => 'width: 23em;'), $aclients) ?>
    </td>
</tr>
<tr>
    <td align="right" class="search1"><label for="client_name" class="ui-select"><?php print $this->translate->_("Path"); ?>
        (<?php print $this->translate->_("Where"); ?>)</label>
        </td>
    <td class="search1" align="left" valign="top"><?php echo $this->formText('where', '', array('size' => 54)) ?></td>
</tr>
<tr>
    <td align="right" class="search1">
        <label for="client_name" class="ui-select"><?php print $this->translate->_("Client"); ?></label>
    </td>
    <td class="search1" align="left">
        <?php echo $this->formSelect('client_name', $this->client_name, array('class' => 'ui-select', 'style' => 'width: 20em;'), $aclients) ?>
    </td>
</tr>
<tr>
    <td class="search1" colspan="2" align="center">
		    <?php echo $this->formSubmit('ok1', $this->translate->_('Run Restore'), array('class' => 'prefer_btn') ); ?>
        </form>
    </td>
</tr>
</table>

</div>

<br style="clear: both;" />

<?php $decode = new MyClass_HomebrewBase64; ?>

<div align="center">
<table id="box-table-minimalist" border="0">
<thead>
<tr>
     <th scope="col" colspan="4"> <?php print $this->translate->_("Attribute"); ?> </th>
     <th scope="col"> <?php print $this->translate->_("Name File"); ?> </th>
     <th scope="col"> <?php print $this->translate->_("File Id"); ?> </th>
     <th scope="col"> <?php print $this->translate->_("Job Id"); ?> </th>
</tr>
</thead>
<tbody>
<tr>
<?php
	// LStat example:
	// MI OfON IGk B Bk Bl A e BAA I BGkZWg BGkZWg BGkZWg A A E
	list($st_dev, $st_ino, $st_mode, $st_nlink, $st_uid, $st_gid, $st_rdev, $st_size, $st_blksize,
		$st_blocks, $st_atime, $st_mtime, $st_ctime) = preg_split("/[\s]+/", $this->file[0]['lstat']);

	if ( $decode->homebrewBase64($st_dev) == 0 )     {
		// OS : windows
		echo '<td>' , date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)) , '</td><td>' ,
			$this->convBytes($decode->homebrewBase64($st_size)) , '</td>',
			'<td></td><td></td>';
	}
	else {
		// OS : linux/unix
		echo '<td>' , $this->permissionOctal2String(($decode->homebrewBase64($st_mode))), '</td><td>' ,
			$decode->homebrewBase64($st_uid), " &nbsp;",  $decode->homebrewBase64($st_gid),'</td><td>',
			date("d-M-y H:i:s", $decode->homebrewBase64($st_mtime)),'</td><td>',
			$this->convBytes($decode->homebrewBase64($st_size)), '</td>';
	}
?>
</td>

	<td><?php echo $this->escape($this->file[0]['path'] . $this->file[0]['filename']);?>&nbsp;&nbsp;
	<td> &nbsp; <?php echo $this->escape($this->file[0]['fileid']) ?> &nbsp;</td>
	<td> &nbsp; <?php echo $this->escape($this->file[0]['jobid']) ?> &nbsp;</td>
	</td>
</tr>
</tbody>
</table>

</div>

<?php else: ?>
	<div align="center"><p><b><?php print $this->translate->_("No Files found."); ?></b></p></div>
<?php endif; ?>
