#!/bin/sh
#
# $Id: webacula_mysql_fill_logbook 405 2009-08-17 19:51:14Z tim4dev $
#

if mysql -f <<END-OF-DATA

USE bacula;


INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES (ADDTIME(NOW(),'-58:05:03'),NULL,'Текст по русски.',20,NULL);



INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES (ADDTIME(NOW(),'-48:15:10'),NULL,'Financial information (accounts, tax details) 2008
   This an additional full backup to the full backup BACULA_JOBID=3
   This backup is done manually at the command of John Smith.

   The weather today is good ;)

   -- William Hackerson',20,NULL);



INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES (ADDTIME(NOW(),'-20:40:30'),NULL,'Today was a <b>power failure</b>.
   Not accomplished nightly backups job.test.1, job.test.2 BACULA_JOBID=4, BACULA_JOBID=5
   Problem with power has been resolved in 02:00 pm.

   -- Michael Foobar',255,0);



INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES (ADDTIME(NOW(),'-10:30:25'),NULL,'<b>Warning</b> record (for example).\r\n\r\nSee BACULA_JOBID=1 for more details.',30,0);



INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
	VALUES (ADDTIME(NOW(),'-1:10:55'), NOW(),'<h1>Header 1</h1>\r\n<h2>Header 2</h2>\r\n<h3>Header 3</h3>\r\n<pre>Preformatted text</pre>\r\n<i>Italic text</i>\r\n\r\nBACULA_JOBID=1\r\n\r\nLOGBOOK_ID=1\r\n\r\n<a href=\"http://webacula.sourceforge.net/\">External link</a>',10,0);



END-OF-DATA
then
   echo "succeeded."
else
   echo "failed."
fi

exit 0
