#!/bin/sh

db_name="bacula"

if mysql -u root -f bacula <<END-OF-DATA

-- roles
INSERT INTO webacula_roles (id, name, description, inherit_id) VALUES (3, 'user_role',  'for tests', NULL);
INSERT INTO webacula_roles (id, name, description, inherit_id) VALUES (4, 'user2_role', 'for Roles tests', 3);
INSERT INTO webacula_roles (id, name, description, inherit_id) VALUES (5, 'user3_role', 'for Roles tests', 4);

-- users
INSERT INTO webacula_users (id, login, pwd, email, active, create_login, role_id)
    VALUES (1001, 'user2', MD5('1'), 'root@localhost',   1, NOW(), 2);
INSERT INTO webacula_users (id, login, pwd, email, active, create_login, role_id)
    VALUES (1002, 'user3', MD5('1'), 'nobody@localhost', 1, NOW(), 3);


-- Bacula ACLs

-- storage
INSERT INTO webacula_storage_acl (name, order_acl, role_id) VALUES ('storage.file.2', 1, 2);
INSERT INTO webacula_storage_acl (name, order_acl, role_id) VALUES ('LTO1',           2, 2);
INSERT INTO webacula_storage_acl (name, order_acl, role_id) VALUES ('storage.file.1', 3, 3);

-- pool
INSERT INTO webacula_pool_acl (name, order_acl, role_id) VALUES ('Default',      1, 2);
INSERT INTO webacula_pool_acl (name, order_acl, role_id) VALUES ('pool.file.7d', 2, 3);

-- client
INSERT INTO webacula_client_acl (name, order_acl, role_id) VALUES ('local.fd', 1, 2);
INSERT INTO webacula_client_acl (name, order_acl, role_id) VALUES ('*all*',    2, 3);

-- file set
INSERT INTO webacula_fileset_acl (name, order_acl, role_id) VALUES ('fileset.test.1',   1, 2);
INSERT INTO webacula_fileset_acl (name, order_acl, role_id) VALUES ('fileset test 2',   2, 3);

-- where
INSERT INTO webacula_where_acl (name, order_acl, role_id) VALUES ('/tmp',   1, 2);
INSERT INTO webacula_where_acl (name, order_acl, role_id) VALUES ('/tmp/test',   1, 3);

-- command
INSERT INTO webacula_command_acl (dt_id, order_acl, role_id) VALUES (290, 1, 2); -- status
INSERT INTO webacula_command_acl (dt_id, order_acl, role_id) VALUES (240, 2, 2); -- restore

-- job
INSERT INTO webacula_job_acl (name, order_acl, role_id) VALUES ('job.name.test.1', 1, 2);
INSERT INTO webacula_job_acl (name, order_acl, role_id) VALUES ('job name test 2', 2, 2);


-- Webacula ACLs

INSERT INTO webacula_resources (dt_id, role_id) VALUES (10, 3);  -- index
INSERT INTO webacula_resources (dt_id, role_id) VALUES (30, 3);  -- Menu Client
INSERT INTO webacula_resources (dt_id, role_id) VALUES (100,3);  -- Menu Storage





END-OF-DATA
then
   echo "OK."
else
   echo "Failed."
fi
exit 0
