#!/bin/sh

if /usr/bin/psql -q  -f - -d bacula <<END-OF-DATA

INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES ((NOW() - time '23:15:10'),NULL, 'Текст по русски.',20,NULL);

INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES ((NOW() - time '21:15:10'),NULL, 'The weather today is good ;)',20,NULL);

INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES ((NOW() - time '20:40:30'),NULL, E'<b>Error</b> record (for example).\r\n\r\nSerious errors in  BACULA_JOBID=2',255,0);

INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
   VALUES ((NOW() - time '10:30:25'),NULL, E'<b>Warning</b> record (for example).\r\n\r\nSee BACULA_JOBID=1 for more details.',30,0);

INSERT INTO webacula_logbook (logDateCreate, logDateLast, logTxt, logTypeId, logIsDel)
	VALUES ((NOW() - time '01:10:55'), NOW(), E'<h1>Header 1</h1>\r\n<h2>Header 2</h2>\r\n<h3>Header 3</h3>\r\n<pre>Preformatted text</pre>\r\n<i>Italic text</i>\r\n\r\nBACULA_JOBID=1\r\n\r\nLOGBOOK_ID=1\r\n\r\n<a href=\"http://webacula.sourceforge.net/\">External link</a>',10,0);


END-OF-DATA
then
   echo "PostgreSql : fill logbook succeeded"
else
   echo "PostgreSql : fill logbook failed !"
fi

exit 0
