#!/bin/sh

PWD='$P$BJiE/eBQo5eVNV3HN55TdAutIsq0UE/'

if /usr/bin/psql -q  -f - -d bacula <<END-OF-DATA

-- roles
INSERT INTO webacula_roles (id, name, description, inherit_id) VALUES (3, 'user_role',  'for tests', NULL);
INSERT INTO webacula_roles (id, name, description, inherit_id) VALUES (4, 'user4_role', 'for Roles tests', 3);
INSERT INTO webacula_roles (id, name, description, inherit_id) VALUES (5, 'user5_role', 'for Roles tests', 4);


-- users
UPDATE webacula_users SET pwd='$PWD' WHERE id=1000;
INSERT INTO webacula_users (id, login, pwd, name, email, active, create_login, role_id)
    VALUES (1001, 'user2', '$PWD', 'John Smith', 'root@localhost',   1, NOW(), 2);
INSERT INTO webacula_users (id, login, pwd, name, email, active, create_login, role_id)
    VALUES (1002, 'user3', '$PWD', 'Ivan Ivanov', 'nobody@localhost', 1, NOW(), 3);
INSERT INTO webacula_users (id, login, pwd, name, email, active, create_login, role_id)
    VALUES (1003, 'user4', '$PWD', 'User Name', 'nobody@localhost', 1, NOW(), 4);
INSERT INTO webacula_users (id, login, pwd, name, email, active, create_login, role_id)
    VALUES (1004, 'user5', '$PWD', 'Имя пользователя', 'nobody@localhost', 1, NOW(), 5);



-- clean 'operator_role' Bacula ACLs
DELETE FROM webacula_storage_acl WHERE role_id=2;
DELETE FROM webacula_pool_acl    WHERE role_id=2;
DELETE FROM webacula_client_acl  WHERE role_id=2;
DELETE FROM webacula_fileset_acl WHERE role_id=2;
DELETE FROM webacula_where_acl   WHERE role_id=2;
DELETE FROM webacula_command_acl WHERE role_id=2;
DELETE FROM webacula_job_acl     WHERE role_id=2;




-- Bacula ACLs

-- storage
INSERT INTO webacula_storage_acl (name, order_acl, role_id) VALUES ('storage.file.2', 1, 2);
INSERT INTO webacula_storage_acl (name, order_acl, role_id) VALUES ('LTO1',           2, 2);
INSERT INTO webacula_storage_acl (name, order_acl, role_id) VALUES ('storage.file.1', 3, 3);

-- pool
INSERT INTO webacula_pool_acl (name, order_acl, role_id) VALUES ('Default',      1, 2);
INSERT INTO webacula_pool_acl (name, order_acl, role_id) VALUES ('pool.file.7d', 2, 3);

-- client
INSERT INTO webacula_client_acl (name, order_acl, role_id) VALUES ('local.fd', 1, 2);
INSERT INTO webacula_client_acl (name, order_acl, role_id) VALUES ('*all*',    2, 3);

-- file set
INSERT INTO webacula_fileset_acl (name, order_acl, role_id) VALUES ('fileset.test.1',   1, 2);
INSERT INTO webacula_fileset_acl (name, order_acl, role_id) VALUES ('fileset test 2',   2, 3);

-- where
INSERT INTO webacula_where_acl (name, order_acl, role_id) VALUES ('/tmp',   1, 2);
INSERT INTO webacula_where_acl (name, order_acl, role_id) VALUES ('/tmp/test',   1, 3);

-- command
INSERT INTO webacula_command_acl (dt_id, role_id) VALUES (290, 2); -- status
INSERT INTO webacula_command_acl (dt_id, role_id) VALUES (240, 2); -- restore

-- job
INSERT INTO webacula_job_acl (name, order_acl, role_id) VALUES ('job.name.test.1', 1, 2);
INSERT INTO webacula_job_acl (name, order_acl, role_id) VALUES ('job name test 2', 2, 2);


-- Webacula ACLs

INSERT INTO webacula_resources (dt_id, role_id) VALUES (10, 3);  -- index
INSERT INTO webacula_resources (dt_id, role_id) VALUES (30, 3);  -- Menu Client
INSERT INTO webacula_resources (dt_id, role_id) VALUES (100,3);  -- Menu Storage


-- for delete role test
INSERT INTO webacula_roles (id, name, description, inherit_id) VALUES (6, 'user6_role', 'for delete Roles tests', NULL);
INSERT INTO webacula_resources   (dt_id, role_id)           VALUES (20, 6);  -- bconsole
INSERT INTO webacula_client_acl  (name, order_acl, role_id) VALUES ('client',  99, 6);
INSERT INTO webacula_command_acl (dt_id, role_id)           VALUES (70, 6);
INSERT INTO webacula_fileset_acl (name, order_acl, role_id) VALUES ('fileset', 99, 6);
INSERT INTO webacula_job_acl     (name, order_acl, role_id) VALUES ('job',     99, 6);
INSERT INTO webacula_pool_acl    (name, order_acl, role_id) VALUES ('pool',    99, 6);
INSERT INTO webacula_storage_acl (name, order_acl, role_id) VALUES ('storage', 99, 6);
INSERT INTO webacula_where_acl   (name, order_acl, role_id) VALUES ('where',   99, 6);


-- probe infinite recursion of roles
INSERT INTO webacula_roles (id, name, description, order_role, inherit_id) VALUES (99, 'rolezzz', 'crack', 99, 99);



END-OF-DATA
then
   echo "PostgreSql : ACLs fill OK"
else
   echo "PostgreSql : ACLs fill failed !"
fi
exit 0
