<!-- bacula-access-denied.phtml -->

<p><div class="noteclassic">
    <h1 class="text-left"><?php echo $this->escape($this->title); ?></h1>
    <p><?php echo $this->escape($this->msg); ?></p>
	<p class="text-center"><b>Bacula ACLs : <?php echo $this->translate->_('Access denied.'); ?></b></p>
	<p class="text-center"><input type="button" value="<?php echo $this->translate->_('Back'); ?>" onClick="history.go(-1);"></p>
</div></p>