<h1 align="center">An error occurred</h1>

<h2>Message :</h2>
<p><?php echo $this->err_message; ?></p>

<?php if ($this->err_custom_message) : ?>
	<h2>Custom Message :</h2>
	<p><?php echo $this->err_custom_message; ?></p>
<?php endif; ?>

<h2>Trace:</h2>
<pre>
<?php echo $this->err_trace; ?>
</pre>

<h2>System Information:</h2>
<ul>
<li></>Webacula version   : <?php echo Zend_Registry::get('webacula_version'), "\n"; ?></li>
<li>Webacula Database : <?php echo $this->db_adapter_webacula, " ", $this->db_server_version_webacula, "\n"; ?></li>
<li>Bacula Database   : <?php echo $this->db_adapter_bacula, " ", $this->db_server_version_bacula, "\n"; ?></li>
<li>Zend Framework : <?php echo $this->zend_version, "\n"; ?></li>
<li><a href="<?php echo $this->baseUrl, '/help/my-php-info/' ?>" target="_blank">PHP</a> : <?php echo phpversion(), "\n"; ?></li>
</ul>

<h2><?php echo $this->translate->_('What to do next?'); ?></h2>
<p>
Please help me improve the software you use by filing a report at
<a href="https://sourceforge.net/tracker/?group_id=201199&atid=976599" target="_blank">Webacula bugtracker</a>.
Useful details include how to reproduce the error, and information (error message, trace) which is shown above, bacula version, etc.
</p>