<!-- webacula-access-denied.phtml -->

<p>
<div class="noteclassic">
    <h1 align="left"><?php echo $this->escape($this->title); ?></h1>
    <p><?php echo $this->escape($this->msg); ?></p>
    <p align="center"><b><font color="#00008B">We</font><font color="#A80000">bacula</font> ACLs : <?php echo $this->translate->_('Access denied.'); ?></b></p>
	<p align="center"><input type="button" value="<?php echo $this->translate->_('Back'); ?>" onClick="history.go(-1);"></p>
</div>
</p>