<!-- storage/act-mount.phtml -->
<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary panel-logoutput">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
            <?php if ( $this->result_error ): ?>
            
               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon glyphicon-alert"></span>
                   <?php
                       switch ( $this->result_error )
                       {
                           case 'ERROR_BCONSOLE': // Error when bconsole starts
                               $msg = $this->translate->_('ERROR: There was a problem executing bconsole.');
                               break;
                           case 'NOFOUND_BCONSOLE': // Bconsole not found
                               $msg = $this->translate->_('ERROR: bconsole not found.');
                               break;
                           case 'BACULA_ACCESS_DENIED':
                               $msg = $this->translate->_('Bacula ACLs : Access denied.');
                               break;
                           default: $msg = '';
                       }
                       echo $msg;
                       if ( $this->command_output )
                       {
                           foreach ($this->command_output as $line){
                              echo '<br/>', $line, '<br/>';
                           }
                       }
                   ?>
                 </p>
               </div>
               <!-- end div alert -->
            
            <?php else: ?>
            
               <!-- director output -->
               <b><?php print $this->translate->_("Director output:"); ?></b>
               <?php
               if ( $this->command_output ){
                  echo '<pre>';
                  foreach ($this->command_output as $line) {
                     if ( preg_match('/(ERR|not found|invalid|Expected)/i', $line) )   {
                        echo '<div>', $line, '</div><br/>';
                     } else {
                        echo $line, '<br/>';
                     }
                  }
                  echo '</pre>';
               } else{
                  echo '<p><b>', $this->translate->_("No Storage [un]mount."), '</b></p>';
               }
                ?>
               <!-- end director output -->            
            
            <?php endif; ?>
            </p><!-- close p -->
         </div><!-- close div panel-body -->
      </div><!-- close div panel panel-default -->
   </div><!-- fim div col-md-8 -->
</div><!-- fim da div rows -->
<!-- storage/act-mount.phtml -->