<!-- storage/status-id.phtml -->

<div class="rows">
  <div class="col-md-10">


<div class="panel panel-default panel-primary panel-logoutput">
	<div class="panel-heading">
	   <?php echo $this->escape($this->title); ?>
	</div>
	<div class="panel-body">

<!--<h1><?php echo $this->escape($this->title); ?></h1>-->

<?php if ( $this->result_error ): ?>

<div class="alert alert-danger">
  <p>
  <span class="glyphicon glyphicon glyphicon-alert"></span>
<!--
    <div class="ui-widget" style="float: left;">
        <div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;">
            <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
            <strong>
            -->
    <?php
        switch ( $this->result_error )
        {
            case 'ERROR_BCONSOLE': // ошибка при запуске bconsole
                $msg = $this->translate->_('ERROR: There was a problem executing bconsole.');
                break;
            case 'NOFOUND_BCONSOLE': // bconsole не найден
                $msg = $this->translate->_('ERROR: bconsole not found.');
                break;
            case 'BACULA_ACCESS_DENIED':
                $msg = $this->translate->_('Bacula ACLs : Access denied.');
                break;
            default: $msg = '';
        }
        echo $msg;
        if ( $this->command_output )
        {
            foreach ($this->command_output as $line) {
             echo '<br>', $line, '<br>';
          }
        }
    ?>
    <!--
            </strong></p>
        </div>
    </div>
    <div style="clear: both;"></div>
    -->
    
  </p>
</div>
    
<?php else: ?>

<!-- director output -->
<!--
<table id="table-dir-output" >
<tr><td>-->
    <b><?php print $this->translate->_("Director output:"); ?></b>
	<?php
    if ( $this->command_output )
    {
        echo '<pre>';
        foreach ($this->command_output as $line) {
            if ( strpos($line, 'ERR') || strpos($line, 'not found') )   {
                echo '<div style="color: white; background-color: red;">' . $line . '</div><br>';
            } else {
                echo $line . '<br>';
            }
		}
		echo '</pre>';
    } else {
        echo '<p><b>', $this->translate->_("No Storage status found."), '</b></p>';
    }
    ?>
<!--
</td></tr>
</table>
-->
<?php endif; ?>

    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->

</div><!-- fim div col-md-8 -->
</div><!-- fim da div row -->