<!-- storage/storage.phtml -->
<div class="rows">
   <div class="col-md-4">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                           <th class="text-center"><?php print $this->translate->_("Mount"); ?></th>
                           <th class="text-center"><?php print $this->translate->_("Name Storage"); ?></th>
                           <th class="text-center"><?php print $this->translate->_("AutoChanger"); ?></th>
                           <th class="text-center"><?php print $this->translate->_("Unmount"); ?></th>
                        </tr>
                     </thead>
                     <tbody>
                     <?php foreach($this->storages as $storage) : ?>
                        <tr>
                           <td class="text-center">
                           <?php if ( $storage['autochanger'] > 0 ) : ?>

                              <!-- autochanger block begin -->
                              <script type="text/javascript">
                              $(document).ready(function(){
	                                 $('#trigger-mount<?php echo $this->escape($storage['storageid']); ?>').click(function(e){
                                       $('#mount<?php echo $this->escape($storage['storageid']); ?>').dialog({
                                            modal: true,
                                            buttons : [{
                                                 'text' : '<?php echo $this->translate->_('Mount Storage'); ?>',
                                                 'class' : 'btn btn-default',
                                                 'type' : 'submit',
                                                 click: function(){ $(this).find('form').submit(); }
                                            }],
                                            'title' : '<?php echo $this->translate->_('Mount Storage'); ?>',
                                            open: function(event) {
                                                 $('.ui-dialog-buttonpane').find('button:contains("<?php echo $this->translate->_('Mount Storage'); ?>")').removeClass('ui-button ui-corner-all ui-widget');
                                            }
	                                 	});
	                                 	e.preventDefault();
	                                 });                                  
                              });
                              </script>                              
                              <a href="#" id="trigger-mount<?php echo $this->escape($storage['storageid']); ?>" title="<?php print $this->translate->_("Mount Storage"); ?>">
                                 <img src="<?php echo $this->baseUrl; ?>/images/connected.png" alt="<?php echo $this->translate->_("Mount Storage"); ?>">
                              </a>
                              <div id="mount<?php echo $this->escape($storage['storageid']); ?>" style="display:none;">
                                 <br/>
                                 <b><?php echo $this->escape($storage['name']); ?></b>
                                
                                 <div class="form-control-inline">
                                    <form action="<?php  echo $this->baseUrl.'/storage/act-mount';?>" method="post">
                                       <?php echo $this->formHidden('autochanger', '1', null); ?>
                                       <?php echo $this->formHidden('act', 'mount', null); ?>
                                       <?php echo $this->formHidden('name', $this->escape($storage['name']), null); ?>
                                       
                                       <br/>
                                       <?php print $this->translate->_("Enter autochanger drive"); ?>
                                       <?php echo $this->formText('drive', null, array('size' => 3, 'class' => 'form-control')); ?>
                                       
                                       <br/>
                                       <b>*</b><?php print $this->translate->_("Enter autochanger slot"); ?>
                                       <?php echo $this->formText('slot', null, array('size' => 3, 'class' => 'form-control')); ?>
                                    </form>
                                 </div>
                              </div>
                              <!-- autochanger block end -->
                        
                           <?php else : ?>
                              <a href="<?php echo $this->baseUrl, '/storage/act-mount/act/mount/name/', $this->escape($storage['name']);?>" title="<?php print $this->translate->_("Mount Storage"); ?>">
                                 <img src="<?php echo $this->baseUrl; ?>/images/connected.png" alt="<?php echo $this->translate->_("Mount Storage"); ?>" border="0" hspace="5">
                              </a>
                           <?php endif; ?>
                           </td>
                           <td>
                              <a href="<?php echo $this->baseUrl, "/storage/status-id/id/", $this->escape($storage['storageid']),
                                "/name/", $this->escape($storage['name']);?>" title="<?php print $this->translate->_("Storage Status"); ?>">
                                <?php echo $this->escape($storage['name']);?>
                              </a>
                           </td>
                        
                           <td class="text-center">
                              <?php if ( $storage['autochanger'] > 0 ) : ?>
                              <a href="<?php echo $this->baseUrl, '/storage/autochanger-content/name/', $this->escape($storage['name']);?>" title="<?php print $this->translate->_("Display autochanger content"); ?>">
                                 <img src="<?php echo $this->baseUrl;?>/images/media-tape-changer.png" border="0" hspace="5">
                              </a>
                              <?php else : ?>
                                 -
                              <?php endif; ?>
                           </td>
                        
                           <td class="text-center">
                              <?php if ( $storage['autochanger'] > 0 ) : ?>
                              
                              <!-- autochanger block begin -->
                              <script type="text/javascript">
                              $(document).ready(function(){
	                                 $('#trigger-umount<?php echo $this->escape($storage['storageid']); ?>').click(function(e){
                                       $('#umount<?php echo $this->escape($storage['storageid']); ?>').dialog({
                                            modal: true,
                                            buttons : [{
                                                 'text' : '<?php echo $this->translate->_('Unmount Storage'); ?>',
                                                 'class' : 'btn btn-default',
                                                 'type' : 'submit',
                                                 click: function(){ $(this).find('form').submit(); }
                                            }],
                                            'title' : '<?php echo $this->translate->_('Unmount Storage'); ?>',
                                            open: function(event) {
                                                 $('.ui-dialog-buttonpane').find('button').removeClass('ui-button ui-corner-all ui-widget');
                                            }
	                                 	});
	                                 	e.preventDefault();
	                                 });                                  
                              });
                              </script>                              
                              <a href="#" id="trigger-umount<?php echo $this->escape($storage['storageid']); ?>" title="<?php print $this->translate->_("Unmount Storage"); ?>">
                                  <img src="<?php echo $this->baseUrl; ?>/images/disconnected.png" alt="<?php echo $this->translate->_("Unmount Storage"); ?>" border="0" hspace="5">
                              </a>
                              <div id="umount<?php echo $this->escape($storage['storageid']); ?>" style="display:none;">
                                 <br/>
                                 <b><?php echo $this->escape($storage['name']); ?></b>
                                 <div class="form-control-inline">
                                    <form action="<?php  echo $this->baseUrl.'/storage/act-mount';?>" method="post">
                                       <?php echo $this->formHidden('autochanger', '1', null); ?>
                                       <?php echo $this->formHidden('act', 'umount', null); ?>
                                       <?php echo $this->formHidden('name', $this->escape($storage['name']), null); ?>
                                       <br/>
                                       <?php print $this->translate->_("Enter autochanger drive"); ?>
                                       <?php echo $this->formText('drive', null, array('size' => 3,'class' => 'form-control')); ?>
                                       <br/>
                                    </form>
                                 </div>
                              </div>
                              <!-- autochanger block end -->
                        
                           <?php else : ?>
                              <a href="<?php echo $this->baseUrl, '/storage/act-mount/act/umount/name/', $this->escape($storage['name']);?>" title="<?php print $this->translate->_("Unmount Storage"); ?>">
                                 <img src="<?php echo $this->baseUrl; ?>/images/disconnected.png" alt="<?php echo $this->translate->_("Unmount Storage"); ?>">
                              </a>
                           <?php endif; ?>
                           </td>
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
            </p><!-- close p -->
         </div><!-- close div panel-body -->
      </div><!-- close div panel panel-default -->
   </div><!-- fim div col-md-10 -->
</div><!-- fim da div rows -->
<!-- storage/storage.phtml -->