<!-- client/all.phtml -->

<!--<h1><?php echo $this->escape($this->title); ?></h1>-->

<div class="rows">
  <div class="col-md-8">
  
  
<div class="panel panel-default panel-primary">
	<div class="panel-heading">
	   <?php echo $this->escape($this->title); ?>
	</div>
	<div class="panel-body">
	   <p>


<?php if ($this->clients): ?>
<div class="table-responsive">
</table><!-- end table-responsive -->
<table id="box-table-dashboard2" class="table table-striped table-hover table-condensed">
<thead>
<tr>
     <th> <?php print $this->translate->_("Name"); ?> </th>
     <th> <?php print $this->translate->_("Client Version"); ?> </th>
     <th class="text-center"> <?php print $this->translate->_("Auto Prune"); ?> </th>
     <th class="text-center"> <?php print $this->translate->_("Files Retention<br />days"); ?> </th>
     <th class="text-center"> <?php print $this->translate->_("Jobs Retention<br />days"); ?> </th>
</tr>
</thead>
<tbody>
<?php foreach($this->clients as $client) : ?>
<tr>
     <td>
        <a href="<?php echo $this->baseUrl, "/client/status-client-id/id/", $this->escape($client['clientid']),
     	  "/name/", $this->escape($client['name']); ?>" title="<?php echo $this->translate->_("Client Detail");?>">
		  <?php echo $this->escape($client['name']);?>
		</a>
	</td>

     <td><?php echo $this->escape($client['uname']);?></td>
     <td class="text-center"><?php echo $this->translate->_($this->int2Char($this->escape($client['autoprune'])));?></td>
     <td class="text-center"><?php echo $this->convSecondsToDays($this->escape($client['fileretention'])).' '.$this->translate->_('days');?></td>
     <td class="text-center"><?php echo $this->convSecondsToDays($this->escape($client['jobretention'])).' '.$this->translate->_('days');?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
</div><!-- end div table-responsive -->

<?php else: ?>
<div class="ui-widget" style="float: left;">
    <div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
        <p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
        <strong><?php print $this->translate->_("No Clients found.");?></strong></p>
    </div>
</div>
<div style="clear: both;"><!--  --></div>
<?php endif; ?>
	   </p><!-- close p -->
    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->


</div><!-- fim div col-md-8 -->
</div><!-- fim da div row -->
