<!-- wblogbook/add.phtml -->
<style>
  .select-overflow { height: auto; max-height: 200px;}
</style>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/insert_tags.js"></script>
<script type="text/javascript">
  // select
  $(function(){
      $('select').each(function() {
        // $(this).selectmenu().selectmenu("menuWidget").addClass("select-overflow");
      });
  });
</script>

<script type="text/javascript">
$(function() {
    // http://docs.jquery.com/UI/Datepicker/formatDate
    $('#logDateCreate').datepicker({
        dateFormat: 'yy-mm-dd',
        changeMonth: true,
        changeYear: true
    });
    
    $('#logDateCreate').on('change',function(){
        var dt = new Date();
        var currentTime = dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();
        $(this).val($(this).val() +' '+currentTime);
    });
});
</script>

<?php
// create array type record
foreach($this->typs as $t) :
	$atyps[$t->typeid] = $this->translate->_( $t->typedesc );
endforeach;
?>

<div class="rows">
  <div class="col-md-6">

<div class="panel panel-default panel-primary">
	<div class="panel-heading">
	   <?php echo $this->escape($this->title); ?>
	</div>
	<div class="panel-body">
	   <p>




<!--<div class="roundcorner-wlb">-->

<!--<div id="logbook-form">-->

<?php if ($this->amessages): ?>
<!-- display ERRORS -->
<div class="alert alert-danger">
  <p>
  <span class="glyphicon glyphicon-alert"></span>
		<?php
			echo '<b>', $this->translate->_("ERROR: Record has not been added. Reason :"), ' </b><br><ol>';
			foreach ($this->amessages as $msg) {
				echo '<li>' . $msg . '</li>';
			}
			echo '</ol>';
		?>  
   </p>
</div>



<!--<div style="clear: both;"></div>-->
<?php endif; ?>

<form id="logbook2" name="logbook" action="<?php  echo $this->baseUrl.'/wblogbook/add';?>" method="post">

<p><b><?php print "(<b>*</b>) " . $this->translate->_("Field is required to process this form"); ?></b></p>

<!-- logDateCreate -->
<div class="form-group row">
<label class="col-md-1 col-form-label" for="logDateCreate"><?php "<sup>*</sup>"  . print $this->translate->_("Date"); ?></label>&nbsp;
<div class="col-md-3">
<?php echo $this->formText('logDateCreate', $this->wblogbook->logDateCreate, array('size' => 20, 'class' => 'form-control')) ?>
</div>
</div>

<?php echo $this->formHidden('logDateLast', $this->wblogbook->logDateLast, null); ?>
<?php echo $this->formHidden('hiddenNew',   $this->hiddenNew, null); ?>
<?php echo $this->formHidden('jobid',   $this->jobid, null); ?>
<?php echo $this->formHidden('joberrors',  $this->joberrors, null); ?>

<!-- logTypeId -->
<div class="form-group row">
<label class="col-md-1 col-form-label" for="logTypeId"><?php print "<sup>*</sup>"  . $this->translate->_("Type"); ?></label>
<div class="col-md-3">
<?php echo $this->formSelect('logTypeId', $this->wblogbook->logTypeId, array('class' => 'form-control'), $atyps); ?>
</div>
</div>

<!-- reviewed -->
<?php if ($this->joberrors > 0) : ?>
<div class="form-group row">
<label class="col-md-1 col-form-label" for="reviewed"><?php print $this->translate->_("Reviewed"); ?></label>
<div class="col-md-4">
    <?php echo $this->formCheckbox('reviewed', null, array('checked' => 1)) ?>
    (<?php print $this->translate->_("Don't show this Job in 'Jobs with errors' list in future");?>)
</div>
</div>
<?php endif;?>


<!-- textarea -->
<fieldset>
	<!--<legend><b><?php "<sup>*</sup>"  . print $this->translate->_("Text"); ?></b></legend>-->
<label><?php print $this->translate->_("Allowed to use tags"); ?> </label><br/>
<?php
foreach($this->aAllowedTags as $key=>$value) {
	echo '<input type="button" name="bt' . $value . '" value="' . trim($value) .
		"\" onclick=\"insert_tag(document.getElementById('logTxt'), '" . $value . "')\" class='btn btn-default' > ";
}
?>

<noscript>
<?php
foreach($this->aAllowedTags as $key=>$value) {
	echo ' &lt;' . $value . '&gt;';
}
?>
</noscript>
<br /><br />
<label><?php print $this->translate->_("Allowed to use pseudo-tags"); ?></label>
<br />
<input type="button" name="btjobid" value="Bacula JobId" onclick="insert_tag(document.getElementById('logTxt'), 'BACULA_JOBID=')" class='btn btn-default'>
<input type="button" name="btlogid" value="Logbook Id" onclick="insert_tag(document.getElementById('logTxt'), 'LOGBOOK_ID=')" class='btn btn-default'>
<br />
<noscript>
BACULA_JOBID=&lt;id&gt;, LOGBOOK_ID=&lt;id&gt;
</noscript>
<br>

<label><?php "<sup>*</sup>"  . print $this->translate->_("Text"); ?></label>
<?php echo $this->formTextarea('logTxt', $this->wblogbook->logTxt, array('cols' => '80', 'rows' => '10', 'class' => 'form-control')); ?>
</fieldset>
<!-- END textarea -->

<br>
<!--<center>-->
<?php echo $this->formSubmit('ok', $this->translate->_('Submit Form'), array('class' => 'btn btn-default') ); ?>
<!--</center>-->
</form>

<!--</div>--> <!-- logbook-form -->
<!--</div>-->

	   </p><!-- close p -->
    </div><!-- close div panel-body -->
</div><!-- close div panel panel-default -->

</div><!-- fim div col-md-8 -->
</div><!-- fim da div row -->


