<?php
if ( empty($this->unit_test) )
{
	// not tests
	header("Expires: Thu, 01 Jan 1970 00:00:01 GMT");               // Date in the past
	header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");  // Always modified
	header("Cache-Control: no-cache, must-revalidate");             // HTTP/1.1
	header("Pragma: no-cache");                                     // HTTP/1.0
}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?php echo $this->escape($this->title); ?></title>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/default/bootstrap/css/bootstrap.css" />
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="expires" content="0">
</head>
<body>
   <div class="container-fluid">
      <div class="rows">
         <div class="col-md-12">
            <div class="text-center"><a href="<?php echo $this->baseUrl ?>/wblogbook/index"><?php print $this->translate->_("Back"); ?></a></div>
            
            <!-- wblogbook/index-printable.phtml -->
            
            <h3 class="text-center"><?php echo $this->escape($this->title); ?></h3>
            
            <div class="text-center"><p><?php print $this->translate->_("Printable version."); ?>
            <?php echo date($this->datetime_format, strtotime(date('Y-m-d H:i:s'))) ;?></p></div>
                     
            <?php if ($this->result): ?>
            
            <div class="table-responsive">
            <table class="table table-striped table-hover table-condensed table-bordered">
               <thead>
                  <tr>
                     <th class="text-center"> Id </th>
                     <th class="text-center"> <?php print $this->translate->_("Date"); ?></th>
                     <th><?php print $this->translate->_("Text"); ?></th>
                     <th class="text-center"> <?php print $this->translate->_("Type"); ?></th>                    
                  </tr>
               </thead>
               <tbody>
               
               <?php foreach($this->result as $line) : ?>
               <tr>
               	<td class="text-center">
               		<?php echo $line['logid']; ?>
               	</td>
               
               	<td class="text-center">
               		<?php
               			$str = date($this->datetime_format, strtotime($line['logdatecreate']));
               			if ($line['logisdel'] != 0) { $str = '<s>' . $str . '</s>'; }; // record deleted
               			echo $str;
               		?>
               	</td>
               	<td>
               		<?php
               			$str = $line['logtxt'];
               
               			$pattern = "/(BACULA_JOBID=)([0-9]*)/i";
               			$replacement = "<a href=\"" . $this->baseUrl . "/job/detail/jobid/\\2\">Bacula JobId \\2</a>";
               			$str = preg_replace($pattern, $replacement, $str);
               
               			$pattern = "/(LOGBOOK_ID=)([0-9]*)/i";
               			$replacement = "<a href=\"" . $this->baseUrl . "/wblogbook/filterbyid/id_begin/\\2\">Logbook Id \\2</a>";
               			$str = preg_replace($pattern, $replacement, $str);
               
               			// each OS have different ASCII chars for linebreak:
               			// windows = \r\n
               			// unix = \n
               			// mac = \r
               			$str = str_replace(array("\r\n", "\r", "\n"), "<br>", $str);
               			//$str = nl2br($str);
               
               			if ($line['logisdel'] != 0) { $str = '<s>' . $str . '</s>'; }; // record deleted
               
               			echo $str;
               
               			
               		?>
               	</td>
               
               	<?php
               		if ($line['logisdel'] != 0) {
               			// record deleted
               			echo '<td class="text-center">', $this->translate->_("Deleted"), '</td>';
               		} else {
               
               			switch ($line['typeid'])
               			{
               				case '20' : $class = 'class="ok text-center"'; break;
               				case '30' : $class = 'class="warning text-center"'; break;
               				case '255': $class = 'class="danger text-center"';  break;
               				default: $class = 'class="text-center"';
               			}
               			echo '<td ', $class, '>', $this->translate->_($line['typedesc']), '</td>';
               		}
               	?>
               </tr>
               <?php endforeach; ?>
               </tbody>
            </table>
            </div><!-- end div table-responsive -->
            
            
            <?php else: ?>
            
            <!-- div alert -->
            <div class="alert alert-danger">
              <p>
              <span class="glyphicon glyphicon-alert"></span>
              <?php print $this->translate->_("No records found."); ?>
               </p>
            </div>
            <!-- end div alert -->


            <?php endif; ?>
            
         </div><!-- end div col-md-8 -->
      </div><!-- end div rows -->
   </div><!-- end div container -->
</body>
</html>