<!-- wblogbook/index.phtml -->
<script type="text/javascript" src="<?php echo $this->baseUrl , '/scripts/jquery-ui.datepicker-', $this->language, '.js';?>"></script>
<script type="text/javascript">
$(document).ready(function(){
   var dates1 = $( "#date_begin, #date_end" ).datepicker({
          dateFormat: 'yy-mm-dd',
          changeMonth: true,
          changeYear: true,
          autoSize: true,
          onSelect: function( selectedDate ) {
          var option = this.id == "date_begin" ? "minDate" : "maxDate",
              instance = $( this ).data( "datepicker" ),
              date = $.datepicker.parseDate(
                 instance.settings.dateFormat ||
                 $.datepicker._defaults.dateFormat,
                 selectedDate, instance.settings 
              );
          dates1.not( this ).datepicker( "option", option, date );
          }
       });
       $('#date_begin').datepicker('setDate', '-1d' );
       $('#date_begin').datepicker('option', {dateFormat: $.datepicker.ISO_8601} );
});
</script>

<script type="text/javascript">
<!--
   // to display the version for printing
   function triggerPrintable()   {
      if ( document.getElementById("printable_by_date").value = "0" )   {
         document.getElementById("printable_by_date").value = "1";
      } else {
         document.getElementById("printable_by_date").value = "0";
      }

      if ( document.getElementById("printable_by_id").value = "0" )  {
         document.getElementById("printable_by_id").value = "1";
      } else {
         document.getElementById("printable_by_id").value = "0";
      }
      if ( document.getElementById("printable_by_text").value = "0" )   {
         document.getElementById("printable_by_text").value = "1";
      } else {
         document.getElementById("printable_by_text").value = "0";
      }

      return;
   }
//-->
</script>

<script type="text/javascript">
<!--
   // for sorts
   function triggerSortOrder()   {
      if ( document.getElementById("sortorder_by_date").value = "DESC" )   {
         document.getElementById("sortorder_by_date").value = "ASC";
      } else {
         document.getElementById("sortorder_by_date").value = "DESC";
      }

      if ( document.getElementById("sortorder_by_id").value = "DESC" )  {
         document.getElementById("sortorder_by_id").value = "ASC";
      } else {
         document.getElementById("sortorder_by_id").value = "DESC";
      }
      return;
   }
//-->
</script>

<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">

            
               <div class="filter-form">
               <!-- ######################################################################### -->
                  <div>
                     <!-- Nav tabs -->
                     <ul class="nav nav-tabs" role="tablist">
                       <li role="presentation" class="active"><a href="#tab1" aria-controls="tab" role="tab" data-toggle="tab"><?php print $this->translate->_("Filter by date"); ?></a></li>
                       <li role="presentation"><a href="#tab2" aria-controls="tab" role="tab" data-toggle="tab"><?php print $this->translate->_("Filter by Id"); ?></a></li>
                       <li role="presentation"><a href="#tab3" aria-controls="tab" role="tab" data-toggle="tab"><?php print $this->translate->_("Text Search"); ?></a></li>
                     </ul>
                  
                     <!-- Tab panes -->
                     <div class="tab-content">
                        <!-- filter by date -->
                        <div role="tabpanel" class="tab-pane active" id="tab1">
                        <div class="container-fluid">
                        <div class="rows">
                           <div class='form-inline'>
                           <form name="filter_by_date" id="filter_by_date" method="POST"  action="<?php echo $this->baseUrl ?>/wblogbook/filterbydate">
                              <?php print $this->translate->_("Date range"); ?>:
                              <?php print $this->translate->_("from"); ?>
                              <?php echo $this->formText('date_begin', $this->escape($this->date_begin), array('size' => 10, 'class' => 'form-control'));?>
                              &nbsp;&nbsp;<?php print $this->translate->_("to"); ?>&nbsp;&nbsp;
                              <?php echo $this->formText('date_end', $this->escape($this->date_end), array('size' => 10, 'class' => 'form-control') ) ?>
                              <?php echo $this->formHidden('printable_by_date', '0', null); ?>
                              <?php echo $this->formHidden('sortorder_by_date', 'DESC', null); ?>                          
                               <?php
                                   echo $this->formSubmit('filter1', $this->translate->_('Search'),
                                      array('style' => 'margin-top: 15px; margin-bottom: 15px;',
                                          'class' => "btn btn-default") );
                               ?>
                           </form>
                           </div>
                        </div>
                        </div>
                        </div>
                        <!-- end filter by date -->
                     
                       <!-- filter by id -->
                       <div role="tabpanel" class="tab-pane" id="tab2">
                       <div class="container-fluid">
                       <div class="rows">
                          <div class='form-inline'>
                          <form name="filter_by_id" id="filter_by_id" method="POST" action="<?php echo $this->baseUrl ?>/wblogbook/filterbyid/">
                           <?php print $this->translate->_("Id range: from"); ?>
                           <?php echo $this->formText('id_begin', $this->escape($this->id_begin), array('size' => 5, 'maxlength' => 15, 'class' => 'form-control')); ?>
                           &nbsp;&nbsp;<?php print $this->translate->_("to"); ?>&nbsp;&nbsp;
                           <?php echo $this->formText('id_end', $this->escape($this->id_end), array('size' => 5, 'maxlength' => 15, 'class' => 'form-control')); ?>
                           &nbsp;
                           <?php echo $this->formHidden('printable_by_id', '0', null); ?>
                           <?php echo $this->formHidden('sortorder_by_id', 'DESC', null); ?>
                           
                              <?php
                                  echo $this->formSubmit('filter2', $this->translate->_('Search'),
                                      array('style' => 'margin-top: 15px; margin-bottom: 15px;',
                                          'class' => "btn btn-default") );
                              ?>
                          </form>
                          </div>
                       </div>
                       </div>
                       </div>
                       <!-- end filter by id -->
                     
                       <!-- full text search -->
                       <div role="tabpanel" class="tab-pane" id="tab3">
                       <div class="container-fluid">
                       <div class="rows">
                          <div class='form-inline'>
                          <form name="filter_by_text" id="search_text" method="POST" action="<?php echo $this->baseUrl ?>/wblogbook/searchtext/">
                           <?php print $this->translate->_("Text"); ?>
                           <?php echo $this->formText('id_text', $this->escape($this->id_text), array('size' => 50, 'maxlength' => 250, 'class' => 'form-control')); ?>
                           &nbsp;
                           <?php echo $this->formHidden('printable_by_text', '0', null); ?>
                           <?php echo $this->formHidden('sortorder_by_text', 'ASC', null); ?>
                           
                              <?php
                                  echo $this->formSubmit('filter3', $this->translate->_('Search'),
                                      array('style' => 'margin-top: 15px; margin-bottom: 15px;',
                                          'class' => "btn btn-default") );
                              ?>
                          </form>
                          </div>
                       </div>
                       </div>
                       </div>
                       <!-- end full text search -->
                       
                     </div><!-- end div tab-content -->
                  </div>
                  <br/>
               
                  <div>
                     <img src="<?php echo $this->baseUrl; ?>/images/printer1.png"
                     alt="<?php print $this->translate->_("View a printable version"); ?>"
                     title="<?php print $this->translate->_("View a printable version"); ?>" align="absmiddle" border="0" height="16" hspace="1" vspace="1" width="16">
                     <input type="checkbox" name="printable" value="printable" onchange="triggerPrintable()">
                     <?php print $this->translate->_("View a printable version"); ?>
                     <br/>
                     <img src="<?php echo $this->baseUrl; ?>/images/1x1.png"
                     alt="<?php print $this->translate->_("To sort in ascending/descending order"); ?>"
                     title="<?php print $this->translate->_("To sort in ascending/descending order"); ?>" align="absmiddle" border="0" height="16" hspace="1" vspace="1" width="16">
                     <input type="checkbox" name="sortorder" value="sortorder" onchange="triggerSortOrder()">
                     <?php print $this->translate->_("Sort in ascending order"); ?>
                  </div>
               </div> <!-- end div filter-form -->
            
               <?php if ($this->result): ?>
            
               <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                     <thead>
                        <tr>
                           <th>Id</th>
                           <th> <?php print $this->translate->_("Date"); ?></th>
                           <th> <?php print $this->translate->_("Text"); ?></th>
                           <th> <?php print $this->translate->_("Type"); ?></th>
                           <th> <?php print $this->translate->_("Last modified"); ?></th>
                        </tr>
                     </thead>
                     <tbody>
                     
                     <?php foreach($this->result as $line) : ?>
                        <tr>
                           <td> 
                              <?php echo $line['logid']; ?>
                           </td>
                           <td>
                              <?php
                                 $str = date( $this->escape($this->datetime_format), strtotime($line['logdatecreate']));
                                 if ($line['logisdel'] != 0) { $str = '<s>' . $str . '</s>'; }; // record deleted
                                 echo $str;
                              ?>
                           </td>
                           <td>
                              <?php
                                 $str = $line['logtxt'];
                        
                                 $pattern = "/(BACULA_JOBID=)([0-9]*)/i";
                                    $replacement = "<a href=\"" . $this->baseUrl . "/job/detail/jobid/\\2\">Bacula JobId \\2</a>";
                                    $str = preg_replace($pattern, $replacement, $str);
                        
                                    $pattern = "/(LOGBOOK_ID=)([0-9]*)/i";
                                    $replacement = "<a href=\"" . $this->baseUrl . "/wblogbook/filterbyid/id_begin/\\2\">Logbook Id \\2</a>";
                                    $str = preg_replace($pattern, $replacement, $str);
                        
                                 // each OS have different ASCII chars for linebreak:
                                 // windows = \r\n
                                 // unix = \n
                                 // mac = \r
                                 $str = str_replace(array("\r\n", "\r", "\n"), "<br>", $str);
                                 //$str = nl2br($str);
                        
                                 if ($line['logisdel'] != 0) { $str = '<s>' . $str . '</s>'; }; // record deleted
                        
                                 echo $str;
                        
                                 //echo '<br><br>';
                        
                                 /*
                                    echo '<form method="post" action="', $this->baseUrl, '/wblogbook/modify">',
                                     $this->formHidden('logid', $line['logid'], null),
                                     $this->formSubmit('modify', $this->translate->_('Modify Entry'),array('class' => 'btn btn-default') ),
                                     '</form><br>';
                                    */
                              ?>
                           </td>
                        
                           <?php
                              if ($line['logisdel'] != 0) {
                                 // record deleted
                                 echo '<td>', $this->translate->_("Deleted"), '</td>';
                              } else {
                        
                                 switch ($line['typeid'])
                                 {
                                    case '20' : $class = 'class="ok"'; break;
                                    case '30' : $class = 'class="warning"'; break;
                                    case '255': $class = 'class="danger"';  break;
                                    default: $class = '';
                                 }
                                 echo '<td ', $class, '>', $this->translate->_($line['typedesc']), '</td>';
                              }
                           ?>
                        
                           <td>
                              <?php
                              if ( isset($line['logdatelast']) ){
                                    echo date($this->datetime_format, strtotime($line['logdatelast']));
                                 } else {
                                    echo '-';
                                 }
                              ?>
                           </td>
                            <td>
                               <form method="post" action="<?php echo $this->baseUrl?>/wblogbook/modify">
                                  <?php echo $this->formHidden('logid', $line['logid'], null); ?>
                                  <a href="<?php echo $this->baseUrl;?>/wblogbook/modify/logid/<?php echo $line['logid']; ?>">
                                      <img src="<?php echo $this->baseUrl ?>/images/document-edit.png" alt="<?php echo $this->translate->_("Modify record"); ?>" title="<?php echo $this->translate->_("Modify record"); ?>" />
                                  </a>
                               </form>
                            </td>
                            
                        </tr>
                     <?php endforeach; ?>
                     </tbody>
                  </table>
               </div><!-- end div table-responsive -->
               <?php else: ?>
               
               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon-alert"></span>
                     <?php print $this->translate->_("No records found!"); ?>  
                  </p>
               </div>
               <!-- end div alert -->
            
               <?php endif; ?>
               
               <div>
                  <form method="POST" action="<?php echo $this->baseUrl ?>/wblogbook/add">
                     <input type="submit" name="name1" value="<?php print $this->translate->_("Add New Record"); ?>" class="btn btn-default">
                  </form>
               </div>               
            
         </div><!-- close div panel-body -->
      </div><!-- close div panel panel-default -->
   </div><!-- fim div col-md-8 -->
</div><!-- fim da div rows -->
