<!-- wblogbook/modify.phtml -->
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/insert_tags.js"></script>

<?php
// create array clients for Form
foreach($this->typs as $t) :
	$atyps[$t->typeid] = $this->translate->_($t->typedesc);
endforeach;
?>

<div class="rows">
   <div class="col-md-6">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>
               
               <?php if ($this->amessages): ?>
               <!-- display ERRORS -->
               <!-- div alert -->
               <div class="alert alert-danger">
                 <p>
                 <span class="glyphicon glyphicon-alert"></span>
                     <?php
                        echo '<b>', $this->translate->_("Record has not been modified. Reason :"), ' </b><br><ol>';
                        foreach ($this->amessages as $msg) {
                           echo '<li>' . $msg . '</li>';
                        }
                        echo '</ol>';
                     ?>  
                  </p>
               </div>
               <!-- end div alert -->               
               
               <?php endif; ?>
               
               <?php if ($this->wblogbook->logIsDel == 1): ?>
               
               <!-- div alert -->
               <div class="alert alert-warning">
                 <p>
                 <span class="glyphicon glyphicon-info-sign"></span>
                    <?php echo $this->translate->_("This record has been deleted."); ?>  
                 </p>
               </div>
               <!-- end div alert -->
               
               
               <?php endif; ?>
               <form name="logbook" action="<?php  echo $this->baseUrl.'/wblogbook/modify';?>" method="post">
                  <p><b><?php print "(<b>*</b>) " . $this->translate->_("Field is required to process this form"); ?></b></p>
                  
                  <!-- logid -->
                  <div class="form-group row">
                     <label class="col-md-1 col-form-label" for="logDateCreate"><?php "<sup>*</sup>"  . print $this->translate->_("Date"); ?></label>&nbsp;
                     <div class="col-md-4">
                     <p class="form-control-static"><?php echo $this->wblogbook->logId; ?></p>
                     </div>
                  </div>
                  
                  <!-- logDateCreate -->
                  <div class="form-group row">
                     <label class="col-md-1 col-form-label" for="logDateCreate"><?php "<sup>*</sup>"  . print $this->translate->_("Date"); ?></label>&nbsp;
                     <div class="col-md-4">
                     <p class="form-control-static"><?php echo date($this->datetime_format, strtotime($this->wblogbook->logDateCreate)); ?></p>
                     </div>
                  </div>

                  <!-- logDateLast -->
                  <div class="form-group row">
                     <label class="col-md-1 col-form-label" for="logDateCreate"><?php "<sup>*</sup>"  . print $this->translate->_("Date"); ?></label>&nbsp;
                     <div class="col-md-4">
                     <p class="form-control-static"><?php echo date($this->datetime_format, strtotime($this->wblogbook->logDateLast)); ?></p>
                     </div>
                  </div>
                  
                  <!-- Select Action -->
                  <div class="form-group row">
                     <label><b><?php print $this->translate->_("Select action "); ?></b></label>
                     <fieldset>
                     <div class="col-md-8">
                        <input type="radio" checked name="act" value="update" class="custom-radio">
                        <?php print $this->translate->_("Modify this record"); ?><br>
                        <input type="radio" name="act" value="delete" class="custom-radio">
                        <?php print $this->translate->_("Delete this record (physically record will not be removed)"); ?><br>
                        <input type="radio" name="act" value="undelete" class="custom-radio">
                        <?php print $this->translate->_("Undelete this record"); ?>
                      </div>
                     </fieldset>
                  </div>
                  
                  <?php echo $this->formHidden('logid', $this->wblogbook->logId, null); ?>
                  <?php echo $this->formHidden('isdel', $this->wblogbook->logIsDel, null); ?>
                  <?php echo $this->formHidden('hiddenModify',   $this->hiddenModify, null); ?>
                  
                  
                  <!-- logTypeId -->
                  <div class="form-group row">
                  <label class="col-md-1 col-form-label" for="logTypeId"><?php print "<sup>*</sup>"  . $this->translate->_("Type"); ?></label>
                  <div class="col-md-3">
                  <?php echo $this->formSelect('logTypeId', $this->wblogbook->logTypeId, array('class' => 'form-control'), $atyps); ?>
                  </div>
                  </div>
                  
                  <!-- textarea -->
                  <div class="table-responsive">
                  
                  <!--Allowed to use tags-->
                  <label><?php print $this->translate->_("Allowed to use tags"); ?></label><br/>
                  <?php
                  foreach($this->aAllowedTags as $key=>$value) {
                  	echo '<input type="button" name="bt' . $value . '" value="' . trim($value) .
                  		"\" onclick=\"insert_tag(document.getElementById('logTxt'), '" . $value . "')\" class='btn btn-default'> ";
                  }
                  ?>
                  <br/><br/>
                  
                  <!--Allowed to use tags-->
                  <label><?php print $this->translate->_("Allowed to use pseudo-tags"); ?></label>
                  <br/>
                  <input type="button" name="btjobid" value="Bacula JobId" onclick="insert_tag(document.getElementById('logTxt'), 'BACULA_JOBID=');"; class="btn btn-default">
                  <input type="button" name="btlogid" value="Logbook Id" onclick="insert_tag(document.getElementById('logTxt'), 'LOGBOOK_ID=');" class="btn btn-default">
                  <br/>
                  <br/>
                  
                  <label><?php "<sup>*</sup>"  . print $this->translate->_("Text"); ?></label>
                  <?php echo $this->formTextarea('logTxt', $this->wblogbook->logTxt, array('cols' => "80", 'rows' => "10", 'class' => 'form-control')); ?>
                  <br/>
                  </div><!-- end div table-responsive -->
                  <!-- end textarea -->
                  <table>
                     <tr>
                        <td>
                        <?php echo $this->formSubmit('ok', $this->translate->_('Submit Form'), array('class' => 'btn btn-default') ); ?>
               </form>
                        </td>
                        <td>&nbsp;&nbsp;&nbsp;</td>
                        <td>
                        <form action="<?php  echo $this->baseUrl.'/wblogbook/index';?>" method="post">
                           <?php echo $this->formSubmit('cancel', $this->translate->_('Cancel'), array('class' => 'btn btn-default') ); ?>
                        </form>
                        </td>
                     </tr>
                  </table>
            </p><!-- close p -->
         </div><!-- close div panel-body -->
      </div><!-- close div panel panel-default -->
   </div><!-- fim div col-md-8 -->
</div><!-- fim da div rows -->
<!-- wbjobdesc/index.phtml -->