<!-- admin/form-acl.phtml -->
<div class="rows">
   <div class="col-md-6">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
         <?php echo $this->escape($this->title); ?>
         </div>
         <div class="panel-body">
            <p>

               <?php echo $this->render('decorators/formBaculaACL.phtml'); ?>
               
            </p><!-- close p -->
         </div><!-- close div panel-body -->
      </div><!-- close div panel panel-default -->
   </div><!-- end div col-md-6 -->
</div><!-- end da div rows -->
