<!-- admin/form-role.phtml -->
<div class="rows">
   <div class="col-md-6">
      <div class="panel panel-default panel-primary">
         <div class="panel-heading">
            <?php echo $this->escape($this->title); ?>
         </div>
      	 <div class="panel-body">
            <p>
              <?php echo $this->render('decorators/formRole.phtml'); ?>
            </p><!-- end p -->
         </div><!-- end div panel-body -->
      </div><!-- end div panel panel-default -->
   </div><!-- end div col-md-6 -->
</div><!-- end div row -->
<!-- end admin/form-role.phtml -->