<!-- admin/role-update.phtml -->
<div class="ui-widget">
	<h3><?php echo $this->escape($this->title); ?></h3>

<p><b><?php echo $this->translate->_('Inherited roles'); ?> :</b>
<?php if ($this->roles) : ?>
    <?php
        $str = '';
        foreach($this->roles as  $role_id => $role_name) {
            $str .= '<a href="' . $this->baseUrl . '/admin/role-update/role_id/' . $role_id . '">';
            $str .= $this->escape($role_name) . '</a>, ';
        }
        echo substr_replace($str, '', -2); // удалить оставшийся разделитель
    ?>
<?php else : ?>
    <?php echo $this->translate->_('none'); ?>
<?php endif; ?>
</p>

</div>

<!-- role form -->
<div class="ui-widget-content ui-corner-all" style="padding: 2em;">
    <form  action="<?php echo $this->form_role->getAction();  ?>"
            method="<?php echo $this->form_role->getMethod();  ?>">
        <?php echo $this->form_role->role_id; ?>
        <?php echo $this->form_role->action_id; ?>
        <?php echo $this->form_role->order_role; ?>
        <?php echo $this->form_role->name_role; ?>
        <?php echo $this->form_role->description_role; ?>
        <?php echo $this->form_role->inherit_id; ?>
        <?php echo $this->form_role->submit; ?>
        <?php echo $this->form_role->reset; ?>
    </form>
</div>
<!-- end role form -->

<!-- webacula ACLs -->
<div class="ui-widget-content ui-corner-all" style="padding: 2em;">
    <form  action="<?php echo $this->form_webacula->getAction();  ?>"
            method="<?php echo $this->form_webacula->getMethod();  ?>">
        <?php echo $this->form_webacula->role_id; ?>
        <?php echo $this->form_webacula->action_id; ?>
        <?php echo $this->form_webacula->webacula_resources; ?>
        <?php echo $this->form_webacula->submit; ?>
        <?php echo $this->form_webacula->reset; ?>
    </form>
</div>
<!-- end webacula ACLs -->