<!-- admin/role-index.phtml -->
<?php if ( !empty($this->exception) ) : ?>
<!-- database, and other errors-->
<div class="ui-widget" style="width: 58em;">
    <div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;">
        <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
        <strong><?php echo $this->exception; ?></strong></p>
    </div>
</div>
<?php endif;?>

<?php if ($this->result): ?>

<div class="ui-widget">
	<h3><?php echo $this->escape($this->title); ?></h3>

    <form method="POST" action="<?php echo $this->baseUrl;?>/admin/role-add">
        <input type="submit" name="name1" value="<?php echo $this->translate->_('Create new role') ?>" class="ui-button ui-state-default ui-corner-all" />
    </form>
</div>

<table id="box-table-admin" border="0">
<thead>
<tr>
    <th scope="col">id</th>
    <th scope="col"> <?php echo $this->translate->_('Name'); ?> </th>
    <th scope="col"> <?php echo $this->translate->_('Description'); ?> </th>
    <th scope="col"> <?php echo $this->translate->_('Inherited role'); ?> </th>
    <th scope="col"> <?php echo $this->translate->_('Order'); ?> </th>
    <th scope="col">&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach($this->result as $line) : ?>
    <tr>
        <td>
            &nbsp;<?php echo $this->escape($line['id']);?>&nbsp;
        </td>
        <td>
            &nbsp;<?php echo $this->escape($line['name']);?>&nbsp;
        </td>
        <td>&nbsp;
            <?php
                $description = $this->escape($line['description']);
                if ( strlen($description) <= 70 )
                    echo $description;
                else
                    echo substr($description, 0, 70), ' ',
                        '<a href="'. $this->baseUrl .'/admin/role-main-form/role_id/'. $line['id'] .'">',
                        '[...]',
                        '</a>';
            ?>
            &nbsp;
        </td>
        <td>&nbsp;
            <?php
                $inherit_name = $this->escape($line['inherit_name']);
                if ($inherit_name)
                    echo '<a href="'. $this->baseUrl .'/admin/role-main-form/role_id/'. $line['inherit_id'] .'">',
                        $inherit_name,
                        '</a>';
            ?>
            &nbsp;
        </td>
        <td>
            &nbsp;<?php echo $this->escape($line['order_role']);?>&nbsp;
        </td>
        <td>
        <?php if ($line['id'] != 1) : ?>
            <a href="<?php echo $this->baseUrl;?>/admin/role-more-info/role_id/<?php echo $line['id'] ?>">
                <img src="<?php echo $this->baseUrl ?>/images/documentinfo.png" alt="<?php echo $this->translate->_("More info") ?>" title="<?php echo $this->translate->_("More info") ?>" border="0" hspace="2" align="absmiddle" />
            </a>
            <a href="<?php echo $this->baseUrl;?>/admin/role-main-form/role_id/<?php echo $line['id'] ?>">
                <img src="<?php echo $this->baseUrl ?>/images/document-edit.png" alt="<?php echo $this->translate->_("Modify record") ?>" title="<?php echo $this->translate->_("Modify record") ?>" border="0" hspace="2" align="absmiddle" />
            </a>           
            <a href="<?php echo $this->baseUrl;?>/admin/role-delete/role_id/<?php echo $line['id'] ?>" id="confirm" class="confirm" title="<?php echo $this->translate->_("Delete record") ?>">
                <img src="<?php echo $this->baseUrl ?>/images/edit-delete.png" alt="<?php echo $this->translate->_("Delete record") ?>" title="<?php echo $this->translate->_("Delete record") ?>" border="0" hspace="2" align="absmiddle" />
            </a>
        <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php else: ?>
<div class="ui-widget">
	<div class="ui-state-highlight ui-corner-all" style="padding: 0pt 0.7em; margin-top: 20px;">
		<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: 0.3em;"></span>
		<strong><?php print $this->translate->_("No Roles found."); ?></strong></p>
	</div>
</div>
<?php endif; ?>

<!-- end /admin/role-index.phtml -->