<script type="text/javascript">

$(document).ready(
	function() {

	$('a.confirm').click(function(e) {
		var targetUrl = $(this).attr("href");
		$('#dialog-confirm').dialog({
           buttons : {
                  <?php echo $this->translate->_('Yes'); ?> : function() {
                    window.location.href = targetUrl;
                  },
                  <?php echo $this->translate->_('No'); ?> : function() {
                    $(this).dialog("close");
                  }
                }		
		});
		e.preventDefault();
	});	
	
});
</script>

<!-- dialog confirm -->
<div id="dialog-confirm" title="<?php echo $this->translate->_("Message"); ?>" style="display:none">
  <p><span class="ui-icon ui-icon-alert"></span><?php echo $this->translate->_("Are you sure you want to delete the user?"); ?></p>
</div>
<!-- end dialog confirm -->


<div class="rows">
   <div class="col-md-8">
      <div class="panel panel-default panel-primary">
      	<div class="panel-heading">
      	   <?php echo $this->escape($this->title); ?>
      	</div>
      	<div class="panel-body">
      	   <p>
               <!-- admin/user-index.phtml -->
               <?php if ( !empty($this->exception) ) : ?>
               				<!-- div class alert -->
                           <div class="alert alert-danger">
                              <p>
                                 <span class="glyphicon glyphicon-alert"></span>
                                 <?php echo $this->exception; ?>
                              </p>
                           </div>
               				<!-- end div class alert -->
               <?php endif;?>
      
               <?php if ($this->result): ?>
               
                  <div class="table-responsive">
                  <table class="table table-striped table-hover table-condensed">
                  <thead>
                  <tr>
                      <th><a href="<?php echo $this->baseUrl; ?>/admin/user-index/order/id">Id</a> </th>
                      <th><a href="<?php echo $this->baseUrl; ?>/admin/user-index/order/login"><?php echo $this->translate->_('Login'); ?></a> </th>
                      <th><a href="<?php echo $this->baseUrl; ?>/admin/user-index/order/name"><?php echo $this->translate->_('Name'); ?></a> </th>
                      <th><?php echo $this->translate->_('Email'); ?> </th>
                      <th><?php echo $this->translate->_('Role'); ?> </th>
                      <th><?php echo $this->translate->_('Created'); ?> </th>
                      <th><?php echo $this->translate->_('Last login'); ?> </th>
                      <th><?php echo $this->translate->_('Last IP'); ?> </th>   
                      <th>&nbsp;</th>
                  </tr>
                  </thead>
                  <tbody>
                  
                  <?php foreach($this->result as $line) : 
	 
                        if ($line['active'] == 0){
                           $tag_open = "<del>";
                           $tag_close = "</del>";
                        } else {
                           $tag_open = "";
                           $tag_close = "";
                        }
                  ?>
                      <tr>
                          <td>
                              <?php echo $tag_open . $this->escape($line['id']) . $tag_close; ?>
                          </td>
                          <td>
                              <?php echo $tag_open . $this->escape($line['login']) . $tag_close; ?>
                          </td>
                          <td>
                              <?php echo $tag_open . $this->escape($line['name']) . $tag_close; ?>
                          </td>
                          <td>
                              <?php echo $tag_open . $this->escape($line['email']) . $tag_close; ?>
                          </td>
                          <td>
                              <a href="<?php echo $this->baseUrl;?>/admin/role-main-form/role_id/<?php echo $line['role_id'] ?>">
                                  <?php echo $tag_open . $this->escape($line['role_name']) . $tag_close;?>
                              </a>
                          </td>
                          <td>
                              <?php echo $tag_open . $this->escape(date($this->datetime_format,strtotime($line['create_login']))) . $tag_close;?>&nbsp;
                          </td>
                          <td>
                              <?php echo $tag_open . $this->escape(date($this->datetime_format,strtotime($line['last_login']))) . $tag_close;?>&nbsp;
                          </td>
                          <td>
                              <?php echo $tag_open . $this->escape($line['last_ip']) . $tag_close; ?>
                          </td>        
                          <td>
                              <a href="<?php echo $this->baseUrl;?>/admin/user-update/user_id/<?php echo $line['id']; ?>">
                                  <img src="<?php echo $this->baseUrl ?>/images/document-edit.png" alt="<?php echo $this->translate->_("Modify record"); ?>" title="<?php echo $this->translate->_("Modify record"); ?>" />
                              </a>
                          <?php if ($line['id'] != 1000) : ?>
                              <a href="<?php echo $this->baseUrl;?>/admin/user-delete/user_id/<?php echo $line['id']; ?>" class="confirm" title="<?php echo $this->translate->_("Delete record"); ?>">
                                  <img src="<?php echo $this->baseUrl ?>/images/edit-delete.png" alt="<?php echo $this->translate->_("Delete record"); ?>" title="<?php echo $this->translate->_("Delete record"); ?>" />
                              </a>
                          <?php endif; ?>
                          </td>
                      </tr>
                  <?php endforeach; ?>
                  </tbody>
                  </table>
                  </div><!-- end div table-responsive -->
               
                  <div>
                      <form method="POST" action="<?php echo $this->baseUrl;?>/admin/user-add">
                          <input type="submit" name="name1" value="<?php echo $this->translate->_('Create new user') ?>" class="btn btn-default" />
                      </form>
                  </div>
                  
                  <?php else: ?>
						
				      <!-- div class alert -->
                  <div class="alert alert-danger">
                     <p>
                        <span class="glyphicon glyphicon-alert"></span>
                        <?php print $this->translate->_("No Users found."); ?>
                     </p>
                  </div>
				      <!-- end div class alert -->						
						
                  <?php endif; ?>
               
               
            </p><!-- close p -->
         </div><!-- close div panel-body -->
      </div><!-- div panel panel-default panel-primary-->
   </div><!-- end div col-md-8 -->
</div><!-- end div rows -->
<!-- end admin/role-index.phtml -->