<!-- layouts/default/admin-menu.phtml -->
<div style="position: absolute; top: 6em;">
<div class="aclmenu">
<p class="aclheader">Webacula ACLs</p>
<ul>
    <li><a href="#">Roles</a></li>
    <li><a href="#">Users</a></li>
</ul>

<p class="aclheader">Bacula ACLs</p>
<ul>
    <li><a href="#">Clients</a></li>
	<li><a href="#">Commands</a></li>
	<li><a href="#">FileSets</a></li>
	<li><a href="#">Jobs</a></li>
    <li><a href="#">Pools</a></li>
    <li><a href="#">Storages</a></li>
    <li><a href="#">Where</a></li>
</ul>
</div>
</div>
<!-- end layouts/default/admin-menu.phtml -->