<?php echo $this->render('header.phtml') ?>
<body>

<?php echo $this->render('main-menu.phtml') ?>

<div class="update-info">
<div class="container-fluid" >
<div class="rows" >
<div class="col-md-6">
<?php if ( $this->meta_refresh ) : ?>
    <span class="badge badge-default">
       <?php print sprintf( $this->translate->_("Last Updated: %s"), date("r")); ?>
       <?php print sprintf( $this->translate->_("Updated every %s seconds"), $this->meta_refresh); ?>
    </span>
    
<?php else: ?>

    <span class="badge badge-default">
       <?php print sprintf( $this->translate->_("Last Updated: %s"), date("r")); ?>
    </span>

<?php endif; ?>
</div><!-- end div col-md-6 -->
</div><!-- end div rows -->
</div><!-- end div container -->
</div><!-- end div update-info -->

<div id="main-div" class="container-fluid">

<?php
// create array of  content
$aContent = array();
    if ( !empty($this->layout()->job_running) )
        $aContent[] = $this->layout()->job_running;

    if ( !empty($this->layout()->job_next) )
        $aContent[] = $this->layout()->job_next;

    if ( !empty($this->layout()->job_terminated) )
        $aContent[] = $this->layout()->job_terminated;

    if ( !empty($this->layout()->job_timeline) )
        $aContent[] = $this->layout()->job_timeline;

    if ( !empty($this->layout()->job_problem) )
        $aContent[] = $this->layout()->job_problem;

    if ( !empty($this->layout()->volume_problem) )
        $aContent[] = $this->layout()->volume_problem;
?>

<!-- layout content -->
<?php $i = 0; ?>
<div class="rows">
  <div class="col-md-6">
<?php foreach($aContent as $content) : ?>
    <!--<div class="float_panel">-->
        <?php
            echo $content;
            echo "</div><!-- fim div col-md-6 -->";
            $i++;
            
        ?>
    <!--</div>-->
    <?php
        if ( ($i % 2) === 0 ){
            //echo '<br class="clear_both" />';
            echo "</div><!-- fim da div row -->";
            echo "<div class='rows'><div class='col-md-6'>";
        }
        else {
           echo "<div class='col-md-6'>";   
        }
    ?>
<?php endforeach; ?>
</div><!-- fim div col-md-6 -->
</div><!-- fim da div row -->

<!--<p style="clear: both;">&nbsp;</p>-->
</div><!-- end div container-fluid -->
</body>
<?php echo $this->render('footer.phtml') ?>
