<?php
header("Expires: Thu, 01 Jan 1970 00:00:01 GMT");               // Date in the past
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");  // Always modified
header("Cache-Control: no-cache, must-revalidate");             // HTTP/1.1
header("Pragma: no-cache");                                     // HTTP/1.0
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php if ( $this->meta_refresh ) : ?>
    <meta http-equiv="refresh" content="<?php echo $this->meta_refresh; ?>" />
<?php endif; ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="<?php echo $this->baseUrl; ?>/favicon.ico" />
    <title><?php echo $this->escape($this->titleDashboard); ?></title>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/default/site.css" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <link rel="alternate" type="application/rss+xml" title="webacula feed" href="<?php echo $this->baseUrl; ?>/feed/feed" />

<!-- main menu -->
<!-- http://users.tpg.com.au/j_birch/plugins/superfish/ -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/styles/default/superfish.css" media="screen" />
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/hoverIntent.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/superfish.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-blockUI.js"></script>
<style type="text/css">@import url("<?php echo $this->baseUrl; ?>/styles/default/jquery-ui-1.7.2.custom.css");</style>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-ui-1.7.2.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery.tooltip.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('ul.sf-menu').superfish({
            delay:       500,                            // second delay on mouseout
            animation:   {opacity:'show',height:'show'}, // fade-in and slide-down animation
            speed:       'fast',                         // faster animation speed
            autoArrows:  true,                           // disable generation of arrow mark-up
            dropShadows: true                            // disable drop shadows
        });
    });
</script>
<!-- END main menu -->

<?php echo $this->MainmenuFloat($this); ?>

<!-- bottom menu -->
<style type="text/css">
div#bottommenu
{
   margin-top: 8em;
   margin-left: 0;
   margin-right: 0;
   width: 100%;

   text-align: center; /* align left to fix the previous IE css bug */

   font-family: Arial, Helvetica, sans-serif;
   font-size: 11px;
   background-color:#002244;
   color:white;
   padding: 1px 1px;
   clear: both;
}

.bottommenua a {
   padding: 1px 1px;
   background-color: #002244;
   color: white;
}

/* наведение мышкой */
.bottommenua a:hover{
   background-color:#00458A;
   color: #FFFF33;
}

</style>
<!-- END bottom menu -->

<style type="text/css">
.float_panel
{
/*width: 48%;*/
float: left;
margin: 10px 10px 0px 0px;
padding: 5px;
border: 1px solid #8DA0D5;
background-color: #F2F8FF;
}
.clear_both { clear: both; }
</style>

<!-- for bconsole -->
<script language="javascript" type="text/javascript">
<!--
/****************************************************
     Popup window generator provided for free at Hypergurl
     Url: http://www.hypergurl.com
     Author: Eric King
     Url: http://eak.digitalrice.com
     This script is free to use as long
     as this info is left in
****************************************************/
var win=null;
function NewWindow(mypage,myname,w,h,scroll,pos){
    if (pos=="center") {
        LeftPosition=(screen.availWidth) ? (screen.availWidth-w)/2 : 50;
        TopPosition=(screen.availHeight) ? (screen.availHeight-h)/2 : 50;
    }
    if (pos=="default") {
        LeftPosition=50;
        TopPosition=50;
    } else if ((pos!="center" && pos!="random" && pos!="default") || pos==null) {
            LeftPosition=0;
            TopPosition=20;
        }
    settings='width='+w+',height='+h+',top='+TopPosition+',left='+LeftPosition+',scrollbars='+scroll+',location=no,directories=no,status=no,menubar=no,toolbar=no,resizable=no';
    win=window.open(mypage,myname,settings);
    if(win.focus){
        win.focus();
    }
}

function CloseNewWin(){
    if(win!=null && win.open)win.close();
}

window.onfocus=CloseNewWin;

// -->
</script>

<script type="text/javascript">
$(document).ready(function(){
    $('a').tooltip({
        track: true,
        delay: 0,
        showURL: false
    });
    // for image maps
    $('area').tooltip({
        track: true,
        delay: 0,
        showURL: false
    });
    // for images
    $('img').tooltip({
        track: true,
        delay: 0,
        showURL: false
    });
});
</script>

</head>
<body>

<ul id="main-menu" class="sf-menu">
   	<li><a href="<?php echo $this->baseUrl;?>/"><?php print $this->translate->_("Desktop"); ?></a>
       	<ul>
           <li><a href="<?php echo $this->baseUrl;?>/director/listjobtotals"><?php print $this->translate->_("Job Totals"); ?></a></li>
           <li><a href="<?php echo $this->baseUrl;?>/bconsole/wterminal" onclick="NewWindow(this.href,'Webacula bconsole','800','600','yes','center');return false" onfocus="this.blur()">
                <?php print $this->translate->_("Bacula Console"); ?>
            </a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/director/statusdir"><?php print $this->translate->_("Director"); ?></a></li>
    <li class="current"><a href="<?php echo $this->baseUrl;?>/job/terminated"><?php print $this->translate->_("Job"); ?></a>
		<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/job/terminated"><?php print $this->translate->_("Terminated"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/running"><?php print $this->translate->_("Running"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/next"><?php print $this->translate->_("Next"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/problem"><?php print $this->translate->_("Problem"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/run-job"><?php print $this->translate->_("Run"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/find-form"><?php print $this->translate->_("Search"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/timeline"><?php print $this->translate->_("Timeline"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/restorejob/main-form"><?php print $this->translate->_("Restore"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $this->translate->_("Pool/Volume"); ?></a>
    	<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $this->translate->_("Overview"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/volume/problem"><?php print $this->translate->_("Problem"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/client/all"><?php print $this->translate->_("Client"); ?></a>
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/storage/storage"><?php print $this->translate->_("Storage"); ?></a>
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/wblogbook/index"><?php print $this->translate->_("Logbook"); ?></a>
        <ul>
            <li><a href="<?php echo $this->baseUrl;?>/wbjobdesc/index"><?php print $this->translate->_("Job Descriptions"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/feed/feed"><?php print $this->translate->_("RSS"); ?></a></li>
        </ul>
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/help/"><?php print $this->translate->_("Help"); ?></a>
    </li>
    <li><a href="<?php echo $this->url( array('controller'=>'auth', 'action'=>'logout'), 'default', true) ?>">
        <?php print $this->translate->_("Logout"); ?></a>
    </li>
</ul>
<br style="clear: both;" />

<div style="margin-top: 3px;">&nbsp;</div>

<script type="text/javascript">
</script>
<noscript>
<div style="font-weight: bold; padding: 5px; background-color: red; color: white;">
    <?php print $this->translate->_("Enable JavaScript please..."); ?>
</div>
</noscript>

<?php if ( $this->meta_refresh ) : ?>
<div class="update-info">
    <?php print sprintf( $this->translate->_("Last Updated: %s"), date("r")); ?>
    <br />
    <?php print sprintf( $this->translate->_("Updated every %s seconds"), $this->meta_refresh); ?>
</div>
<?php endif; ?>



<?php
// create array of  content
$aContent = array();
    if ( !empty($this->layout()->job_running) )
        $aContent[] = $this->layout()->job_running;

    if ( !empty($this->layout()->job_next) )
        $aContent[] = $this->layout()->job_next;

    if ( !empty($this->layout()->job_terminated) )
        $aContent[] = $this->layout()->job_terminated;

    if ( !empty($this->layout()->job_timeline) )
        $aContent[] = $this->layout()->job_timeline;

    if ( !empty($this->layout()->job_problem) )
        $aContent[] = $this->layout()->job_problem;

    if ( !empty($this->layout()->volume_problem) )
        $aContent[] = $this->layout()->volume_problem;
?>

<!-- layout content -->
<?php $i = 0; ?>
<?php foreach($aContent as $content) : ?>
    <div class="float_panel">
        <?php
            echo $content;
            $i++;
        ?>
    </div>
    <?php
        if ( ($i % 2) === 0 )
            echo '<br class="clear_both" />';
    ?>
<?php endforeach; ?>

<br class="clear_both" />

</body>
</html>
