<?php
header("Expires: Thu, 01 Jan 1970 00:00:01 GMT");               // Date in the past
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");  // Always modified
header("Cache-Control: no-cache, must-revalidate");             // HTTP/1.1
header("Pragma: no-cache");                                     // HTTP/1.0
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="refresh" content="300">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?php echo $this->baseUrl; ?>/favicon.ico" />	
	<title><?php echo $this->escape($this->titleDashboard); ?></title>
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/default/site.css" />
	<meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <link rel="alternate" type="application/rss+xml" title="webacula feed" href="<?php echo $this->baseUrl; ?>/feed/feed">

<!-- main menu -->
<!-- http://users.tpg.com.au/j_birch/plugins/superfish/ -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/styles/default/superfish.css" media="screen">
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/hoverIntent.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/superfish.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-blockUI.js"></script>
<style type="text/css">@import url("<?php echo $this->baseUrl; ?>/styles/default/jquery-ui-1.7.2.custom.css");</style>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-ui-1.7.2.custom.min.js"></script>

<script type="text/javascript">
	$j = jQuery.noConflict();
	$j(document).ready(function() { 
        $j('ul.sf-menu').superfish({ 
            delay:       500,                            // second delay on mouseout 
            animation:   {opacity:'show',height:'show'}, // fade-in and slide-down animation 
            speed:       'fast',                         // faster animation speed 
            autoArrows:  true,                           // disable generation of arrow mark-up 
            dropShadows: true                            // disable drop shadows 
        }); 
    });
</script>
<!-- END main menu -->

<?php echo $this->MainmenuFloat($this); ?>

<!-- bottom menu -->
<style type="text/css">
div#bottommenu
{
   margin-top: 8em;
   margin-left: 0;
   margin-right: 0;
   width: 100%;

   text-align: center; /* align left to fix the previous IE css bug */

   font-family: Arial, Helvetica, sans-serif;
   font-size: 11px;
   background-color:#002244;
   color:white;
   padding: 1px 1px;
   clear: both;
}

.bottommenua a {
   padding: 1px 1px;
   background-color: #002244;
   color: white;
}

/* наведение мышкой */
.bottommenua a:hover{
   background-color:#00458A;
   color: #FFFF33;
}

</style>
<!-- END bottom menu -->

</head>
<body>

<?php $translate = Zend_Registry::get('translate'); ?>

<ul id="main-menu" class="sf-menu">
   	<li><a href="<?php echo $this->baseUrl;?>/"><?php print $translate->_("Desktop"); ?></a>
       	<ul>
           	<li><a href="<?php echo $this->baseUrl;?>/director/listjobtotals"><?php print $translate->_("Job Totals"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/director/statusdir"><?php print $translate->_("Director"); ?></a></li>
    <li class="current"><a href="<?php echo $this->baseUrl;?>/job/terminated"><?php print $translate->_("Job"); ?></a>
		<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/job/terminated"><?php print $translate->_("Terminated"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/running"><?php print $translate->_("Running"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/next"><?php print $translate->_("Next"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/problem"><?php print $translate->_("Problem"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/run-job"><?php print $translate->_("Run"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/find-form"><?php print $translate->_("Search"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/job/timeline"><?php print $translate->_("Timeline"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/restorejob/main-form"><?php print $translate->_("Restore"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $translate->_("Pool/Volume"); ?></a>
    	<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $translate->_("Overview"); ?></a></li>
            <li><a href="<?php echo $this->baseUrl;?>/volume/problem"><?php print $translate->_("Problem"); ?></a></li>
		</ul>
	</li>
    <li><a href="<?php echo $this->baseUrl;?>/client/all"><?php print $translate->_("Client"); ?></a>
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/storage/storage"><?php print $translate->_("Storage"); ?></a>
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/wblogbook/index"><?php print $translate->_("Logbook"); ?></a>
    	<ul>
        	<li><a href="<?php echo $this->baseUrl;?>/feed/feed"><?php print $translate->_("RSS"); ?></a></li>
        </ul>	
    </li>
    <li><a href="<?php echo $this->baseUrl;?>/help/"><?php print $translate->_("Help"); ?></a>
    </li>
</ul>
<br style="clear: both;" />

<div style="margin-top: 3px;">&nbsp;</div>

<script type="text/javascript">
</script>
<noscript>
<div style="font-weight: bold; padding: 5px; background-color: red; color: white;">
    <?php print $translate->_("Enable JavaScript please..."); ?>
</div>
</noscript>

<!-- layout content -->
<table align="left" width="100%" border="0" cellspacing="3" cellpadding="3">
<tr valign="top">
<td bgcolor="#EEEEEE">
	<?php echo $this->layout()->job_running; ?>
</td><td bgcolor="#EEEEEE">
	<?php echo $this->layout()->job_next; ?>
</td></tr><tr valign="top"><td bgcolor="#EEEEEE">
	<?php echo $this->layout()->job_problem; ?>
	<?php echo $this->layout()->volume_problem; ?>
</td><td bgcolor="#EEEEEE">
	<?php echo $this->layout()->job_terminated; ?>
</td></tr>
</table>	

<?php //echo $this->layout()->content ?>

<!-- footer menu -->
<div id="center_for_ie2">
<div id="bottommenu">
    <div class="bottommenua">
<b><a href="<?php echo $this->baseUrl;?>"><?php print $translate->_("Desktop"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/director/statusdir"><?php print $translate->_("Director"); ?></a></b>&nbsp;|&nbsp;
<b><?php print $translate->_("Job"); ?> : </b>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/last"><?php print $translate->_("Last"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/running"><?php print $translate->_("Running Jobs"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/next"><?php print $translate->_("Next"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/problem"><?php print $translate->_("Problem"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/run-job"><?php print $translate->_("Run Job"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/find-form"><?php print $translate->_("Search"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/job/timeline"><?php print $translate->_("Timeline"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/restorejob/main-form"><?php print $translate->_("Restore"); ?></a>&nbsp;|&nbsp;
<b><?php print $translate->_("Pool/Volume"); ?> : </b>&nbsp;
<a href="<?php echo $this->baseUrl;?>/pool/all"><?php print $translate->_("Overview"); ?></a>&nbsp;
<a href="<?php echo $this->baseUrl;?>/volume/problem"><?php print $translate->_("Problem"); ?></a>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/client/all"><?php print $translate->_("Client"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/storage/storage"><?php print $translate->_("Storage"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/wblogbook/index"><?php print $translate->_("Logbook"); ?></a></b>&nbsp;|&nbsp;
<b><a href="<?php echo $this->baseUrl;?>/help/"><?php print $translate->_("Help"); ?></a></b>
    </div>
</div>
</div> <!-- end of ieCenter div -->

</body>
</html>
