<?php
header("Expires: Thu, 01 Jan 1970 00:00:01 GMT");               // Date in the past
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");  // Always modified
header("Cache-Control: no-cache, must-revalidate");             // HTTP/1.1
header("Pragma: no-cache");                                     // HTTP/1.0
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php if ( $this->meta_refresh ) : ?>
    <meta http-equiv="refresh" content="<?php echo $this->meta_refresh; ?>" />
<?php endif; ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="<?php echo $this->baseUrl; ?>/images/favicon.ico" />
    <title>
        <?php
            if ( $this->titleDashboard ) {
                echo $this->escape($this->titleDashboard);
            } else {
                echo $this->escape($this->title);
            }
        ?>
    </title>
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/<?php echo $this->config->layout->path; ?>/site.css" />
	<style type="text/css">@import url("<?php echo $this->baseUrl; ?>/styles/<?php echo $this->config->layout->path; ?>/bootstrap/css/bootstrap.css");</style>
	<style type="text/css">@import url("<?php echo $this->baseUrl; ?>/styles/<?php echo $this->config->layout->path; ?>/bootstrap/css/bootstrap-theme.css");</style>
	<style type="text/css">@import url("<?php echo $this->baseUrl; ?>/styles/<?php echo $this->config->layout->path; ?>/bootstrap/css/font-awesome.css");</style>
   <style type="text/css">@import url("<?php echo $this->baseUrl; ?>/styles/<?php echo $this->config->layout->path; ?>/jquery-ui.css");</style>
   <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl; ?>/styles/<?php echo $this->config->layout->path; ?>/override-css.css" />
   
   <meta http-equiv="Pragma" content="no-cache" />
   <meta http-equiv="expires" content="0" />
   <link rel="alternate" type="application/rss+xml" title="webacula feed" href="<?php echo $this->baseUrl; ?>/feed/feed" />

   <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-3.2.1.js"></script>
   <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/bootstrap.js"></script>
   <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-ui.js"></script>
   <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-blockUI.js"></script>

<script type="text/javascript">
$(document).ready(function() {

});
</script>
<!-- END main menu -->

<?php echo $this->MainmenuFloat($this); ?>

<style type="text/css">

/*
.float_panel
{
width: 48%;
float: left;

padding: 0px 5px;

margin: 10px 10px 0px 0px;

border: 1px solid #DDD;
background-color: #F2F8FF;
background-color: #F2F8FF;
}

.clear_both { clear: both; }

*/

</style>

<script type="text/javascript">
$(document).ready(function(){
    $('a').tooltip({
        track: true,
        delay: 0,
        showURL: false
    });
	
    $('i').tooltip({
        track: true,
        delay: 0,
        showURL: false
    });
	
    // for image maps
    $('area').tooltip({
        track: true,
        delay: 0,
        showURL: false
    });
    // for images
    $('img').tooltip({
        track: true,
        delay: 0,
        showURL: false
    });
});
</script>

</head>
