<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- application/layouts/scripts/login.phtml -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>

    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-3.2.1.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/styles/default/jquery-ui.css" media="screen" />
	

<style type="text/css">
body {background-color: #fff;}

.login-content {
	width: 90%;
    margin-top:    3em;
    margin-bottom: 2.5em;
    margin-left:   auto;
    margin-right:  auto;
    font-family: arial, verdana, sans-serif;
}

#login input
{
    margin-left:    0em;
    padding-top:    0.3em;
    padding-right:  0em;
    padding-bottom: 0.3em;
    padding-left:   0em;
}

.login-btn {
    background-color:#e8edff;
    color:#000;
    border:outset 2px #DDD;
    font-weight : bold;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    width: 8em;
    height: 3em;
}

.forgot-btn {
    background-color:#FFbf4e;
    color:#000;
    border:outset 2px #FFbf4e;
    font-weight : bold;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    height: 3em;
}
</style>

<script type="text/javascript">
$(document).ready(function() {
   var x = "";

});	  


</script>

	
</head>
<body>
    <div class="ui-widget ui-widget-content ui-corner-all" style="width:38em; margin-left:auto; margin-right:auto; margin-top:4em;">
        <div class="login-content" id="login">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</body>
</html>
