<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- application/layouts/scripts/login.phtml -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title><?php echo $this->escape($this->title); ?></title>

    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-3.2.1.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/jquery-ui.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/scripts/bootstrap.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/styles/default/jquery-ui.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/styles/default/bootstrap/css/bootstrap.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl; ?>/styles/default/bootstrap/css/bootstrap-theme.css" media="screen" />
    
	

<style type="text/css">
body {background-color: #fff;}

.login-content {
	width: 90%;
    margin-top:    3em;
    margin-bottom: 2.5em;
    margin-left:   auto;
    margin-right:  auto;
    font-family: arial, verdana, sans-serif;
}

#login input
{
    margin-left:    0em;
    padding-top:    0.3em;
    padding-right:  0em;
    padding-bottom: 0.3em;
    padding-left:   0em;
}

.login-btn {
    background-color:#e8edff;
    color:#000;
    border:outset 2px #DDD;
    font-weight : bold;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    width: 8em;
    height: 3em;
}

.forgot-btn {
    background-color:#FFbf4e;
    color:#000;
    border:outset 2px #FFbf4e;
    font-weight : bold;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    height: 3em;
}

#login2 {
  -webkit-border-radius: 15px;
  -moz-border-radius: 15px;
  -ms-border-radius: 15px;
  -o-border-radius: 15px;
  border-radius: 15px;
  -webkit-box-shadow: 0 0 8px rgba(0, 0, 0, 0.4);
  -moz-box-shadow: 0 0 8px rgba(0, 0, 0, 0.4);
  box-shadow: 0 0 8px rgba(0, 0, 0, 0.4);
  position: relative;
  /*top: 50%;*/
  /*left: 50%;*/
  display: block;
  /*margin-top: -285px;*/
  /*margin-left: -235px;*/
  margin-left: auto;
  margin-right: auto;
  padding: 15px;
  width: 300px;
  height: auto;
  background: white;
  text-align: center;
}


.btn-black {
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    padding: 5px 20px;
    background-color: #222222;
    background-image: none;
    color: white;
    text-shadow: none;
}


</style>

<script type="text/javascript">
$(document).ready(function() {
   var x = "";

});	  


</script>

	
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <!-- 
      <?php echo $this->form->login; ?>
      <?php echo $this->form->pwd; ?>
      <?php echo $this->form->rememberme; ?>
      <?php echo $this->form->submit; ?>
      -->
        <div class="login-content text-center" id="login2">
        <img src="<?php echo $this->baseUrl; ?>/images/bacula_logo.png" style="width:50%;">
            <?php echo $this->layout()->content; ?>
        </div>
    </div><!-- fim da div div class="col-md-12" -->
  </div><!-- fim da div row -->
</div><!-- end div container-fluid -->
</body>
</html>
