<?php echo $this->render('header.phtml') ?>
<body>
<?php echo $this->render('main-menu.phtml') ?>

<div class="update-info">
<div class="container-fluid" >
<div class="rows" >
<div class="col-md-6">
<?php if ( $this->meta_refresh ) : ?>
    <span class="badge badge-default">
       <?php print sprintf( $this->translate->_("Last Updated: %s"), date("r")); ?>
       <?php print sprintf( $this->translate->_("Updated every %s seconds"), $this->meta_refresh); ?>
    </span>
    
<?php else: ?>

    <span class="badge badge-default">
       <?php print sprintf( $this->translate->_("Last Updated: %s"), date("r")); ?>
    </span>

<?php endif; ?>
</div><!-- end div col-md-6 -->
</div><!-- end div rows -->
</div><!-- end div container -->
</div><!-- end div update-info -->


<div id="main-div" class="container-fluid">
<?php echo $this->layout()->content ?>
</div><!-- end div container-fluid -->
</body>
<?php echo $this->render('footer.phtml') ?>
