<?php echo $this->render('header.phtml') ?>
<body>
<?php echo $this->render('main-menu.phtml') ?>
<?php if ( $this->meta_refresh ) : ?>
<div class="update-info">
    <?php print sprintf( $this->translate->_("Last Updated: %s"), date("r")); ?>.
    <?php print sprintf( $this->translate->_("Updated every %s seconds"), $this->meta_refresh); ?>
</div>
<?php else: ?>
<div>&nbsp;</div>
<?php endif; ?>
<div id="main-div" style="border: 1px #000 solid;">
<?php echo $this->layout()->content ?>
<p style="clear: both;">&nbsp;</p>
</div>
</body>
<?php echo $this->render('footer.phtml') ?>
